%% Auto generated by defs from gm.def
%% Don't edit it.

-module(gm_def).
-compile([export_all]).

-include("gm_def.hrl").

%% enum set_gm 
set_gm_to_s(?GM_SET_DAILY_COUNT) -> <<"GM_SET_DAILY_COUNT">>;
set_gm_to_s(?GM_SET_GUILD_COUNT) -> <<"GM_SET_GUILD_COUNT">>;
set_gm_to_s(_) -> invalid_id.

is_valid_set_gm(?GM_SET_DAILY_COUNT) -> true;
is_valid_set_gm(?GM_SET_GUILD_COUNT) -> true;
is_valid_set_gm(_) -> false.
enum_set_gm_all() -> [1 , 2].
enum_set_gm_size() -> 2.
