%% Auto generated by defs from guild.def
%% Don't edit it.

-define(pd_guild_tech_prev_attr, pd_guild_tech_prev_attr).
-define(join_guild, join_guild).
-define(position_change, position_change).
-define(guild_buildings_cfg, guild_buildings_cfg).
-define(quit_guild, quit_guild).
-define(guild_id_tab, guild_id_tab).
-define(player_guild_tech_buildings, player_guild_tech_buildings).
-define(guild_member_lvup_cfg, guild_member_lvup_cfg).
-define(player_apply_tab, player_apply_tab).
-define(guild_player_association_tab, guild_player_association_tab).
-define(player_guild_member, player_guild_member).
-define(guild_member_online_tab, guild_member_online_tab).
-define(guild_tech_cfg, guild_tech_cfg).
-define(guild_tab, guild_tab).
-define(guild_buildings_tab, guild_buildings_tab).
-define(guild_shop_cfg, guild_shop_cfg).
-define(guild_event_tab, guild_event_tab).


-type msg_guild_tech_lvup() :: 591  | 592  | 593 .
%% Enum msg_guild_tech_lvup begin
-define(ERR_GUILD_NO_THIS_TECH_BUILDINGID, 591).
-define(ERR_GUILD_TECH_LV_MAX, 592).
-define(ERR_GUILD_TECH_VERIFY_CONDITION_FAIL, 593).
%% Enum msg_guild_tech_lvup end 

-type msg_guild_shop() :: 571  | 572 .
%% Enum msg_guild_shop begin
-define(ERR_GUILD_VERIFY_CONDITION_ERROR, 571).
-define(ERR_GUILD_NO_GUILD_SHOP_CFG, 572).
%% Enum msg_guild_shop end 

-type msg_guild_apply() :: 561 .
%% Enum msg_guild_apply begin
-define(ERR_GUILD_MAX_NUM, 561).
%% Enum msg_guild_apply end 

-type msg_guild_building_addexp() :: 551  | 552  | 553  | 554  | 555  | 557  | 558 .
%% Enum msg_guild_building_addexp begin
-define(ERR_GUILD_NO_MEMBER_CFG, 551).
-define(ERR_GUILD_NO_THISBUILDINGID, 552).
-define(ERR_GUILD_EXIT_MORE_THISBUILDINGS, 553).
-define(ERR_GUILD_NO_BUILDING_LVUPCFG, 554).
-define(ERR_GUILD_TYPE_IS_ERROR, 555).
-define(ERR_GUILD_LV_LESS_THEN_BUILDINGS, 557).
-define(ERR_GUILD_LV_MAX, 558).
%% Enum msg_guild_building_addexp end 

-type msg_guild_appoint_or_remove_player() :: 531  | 532  | 533  | 541  | 542  | 543  | 544 .
%% Enum msg_guild_appoint_or_remove_player begin
-define(ERR_GUILD_NOT_ENOUGH_POSITION_NUM, 531).
-define(ERR_GUILD_PLAYER_NOT_IN_THIS_GULD, 532).
-define(ERR_GUILD_THIS_POSITION_IS_NULL, 533).
-define(ERR_GUILD_MASTER_CONNOT_REMOVE, 541).
-define(ERR_GUILD_NO_THIS_POSITION, 542).
-define(ERR_GUILD_OTHER_PLAYER_NOT_JOIN_GUILD, 543).
-define(ERR_GUILD_MASTER_CONNOT_CHANGE_POSITION, 544).
%% Enum msg_guild_appoint_or_remove_player end 

-type msg_guild_search() :: 581 .
%% Enum msg_guild_search begin
-define(ERR_GUILD_FIND_GUILD_IS_NULL, 581).
%% Enum msg_guild_search end 

-type msg_guild_create() :: 521  | 522  | 523  | 524  | 525  | 526 .
%% Enum msg_guild_create begin
-define(ERR_GUILD_CREATE_LEVEL_LESS_THAN, 521).
-define(ERR_GUILD_CREATE_DIAMOND_LESS_THAN, 522).
-define(ERR_GUILD_CREATE_ITEM_LESS_THAN, 523).
-define(ERR_GUILD_COST_FAIL, 524).
-define(ERR_GUILD_CREATE_NAME_REPEAT, 525).
-define(ERR_GUILD_CREATE_GOLD_LESS_THAN, 526).
%% Enum msg_guild_create end 

-type guild_event_type() :: 1  | 2  | 3  | 4  | 5 .
%% Enum guild_event_type begin
-define(GUILD_EVENT_TYPE_ADDEXP_ID, 1).
-define(GUILD_EVENT_TYPE_JOIN, 2).
-define(GUILD_EVENT_TYPE_REMOVE, 3).
-define(GUILD_EVENT_TYPE_QUIT, 4).
-define(GUILD_EVENT_TYPE_POSITION, 5).
%% Enum guild_event_type end 

-type guild_operation() :: 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  | 10  | 11  | 12  | 13 .
%% Enum guild_operation begin
-define(GUILD_APPLY_AGREE_OR_REFUSED, 1).
-define(GUILD_REMOVE_MEMBER, 2).
-define(GUILD_REMOVE_VICE_MATER, 3).
-define(GUILD_APPOINT_OR_REMOVE_POSITION, 4).
-define(GUILD_MASTER_TRANSFER, 5).
-define(GUILD_QUIT, 6).
-define(GUILD_VIEW_APPLY_LIST, 7).
-define(GUILD_UPDATE_NOTICE, 8).
-define(GUILD_BOSS_DONATE, 9).
-define(GUILD_BOSS_PHASE, 10).
-define(GUILD_BOSS_CALL, 11).
-define(GUILD_BOSS_DAMAGE, 12).
-define(GUILD_BOSS_REVIVE, 13).
%% Enum guild_operation end 

-type guild_position() :: 1  | 2  | 3 .
%% Enum guild_position begin
-define(GUILD_MASTER_POSITIONID, 1).
-define(GUILD_VICE_MASTER_POSTION, 2).
-define(GUILD_MEMBER_POSTION, 3).
%% Enum guild_position end 

