%% Auto generated by defs from item_bucket.def
%% Don't edit it.

-define(pd_he_cheng_yl, pd_he_cheng_yl).
-define(pd_equip, pd_equip).
-define(pd_depot, pd_depot).
-define(pd_bag, pd_bag).


-type bucket_type() :: 1  | 2  | 3 .
%% Enum bucket_type begin
-define(BUCKET_TYPE_BAG, 1).
-define(BUCKET_TYPE_DEPOT, 2).
-define(BUCKET_TYPE_EQM, 3).
%% Enum bucket_type end 

