%% Auto generated by defs from item_bucket.def
%% Don't edit it.

-module(item_bucket_def).
-compile([export_all]).

-include("item_bucket_def.hrl").

%% enum bucket_type 
bucket_type_to_s(?BUCKET_TYPE_BAG) -> <<"BUCKET_TYPE_BAG">>;
bucket_type_to_s(?BUCKET_TYPE_DEPOT) -> <<"BUCKET_TYPE_DEPOT">>;
bucket_type_to_s(?BUCKET_TYPE_EQM) -> <<"BUCKET_TYPE_EQM">>;
bucket_type_to_s(_) -> invalid_id.

is_valid_bucket_type(?BUCKET_TYPE_BAG) -> true;
is_valid_bucket_type(?BUCKET_TYPE_DEPOT) -> true;
is_valid_bucket_type(?BUCKET_TYPE_EQM) -> true;
is_valid_bucket_type(_) -> false.
enum_bucket_type_all() -> [1 , 2, 3].
enum_bucket_type_size() -> 3.
bucket_type_to_i(pd_bag) -> ?BUCKET_TYPE_BAG;
bucket_type_to_i(pd_depot) -> ?BUCKET_TYPE_DEPOT;
bucket_type_to_i(pd_equip) -> ?BUCKET_TYPE_EQM;
bucket_type_to_i(_) -> badarg.

bucket_type_to_a(?BUCKET_TYPE_BAG) -> pd_bag;
bucket_type_to_a(?BUCKET_TYPE_DEPOT) -> pd_depot;
bucket_type_to_a(?BUCKET_TYPE_EQM) -> pd_equip;
bucket_type_to_a(_) -> badarg.

