%% Auto generated by defs from msg.def
%% Don't edit it.



-type scene_pet() :: pet_idx  | pet_msg_move  | pet_msg_move_stop  | pet_switch_move_mode_msg .
%% Enum Atom scene_pet begin
-define(pet_idx, pet_idx).
-define(pet_msg_move, pet_msg_move).
-define(pet_msg_move_stop, pet_msg_move_stop).
-define(pet_switch_move_mode_msg, pet_switch_move_mode_msg).
%% Enum Atom scene_pet end 

-type scene_player() :: move_msg  | switch_move_mode_msg  | move_stop_msg  | jump_msg  | resize_view_msg  | die_msg  | enter_scene_msg  | leave_scene_msg  | release_skill_msg  | skill_move_msg  | release_buff_msg  | msg_kickout  | msg_relive  | msg_kill_player  | msg_kill_monster  | msg_add_item  | msg_del_item  | msg_add_prize  | msg_pickup_drop_item  | msg_kill_monster_add_exp  | msg_killed_by_agent  | msg_killed_by_device  | msg_game_frame  | msg_update_attr  | msg_add_hp  | msg_del_hp  | msg_full_hp_mp  | msg_full_hp  | msg_full_mp  | msg_update_view_data  | msg_update_equip_efts  | msg_update_shapeshift_data  | msg_update_ride_data  | msg_shapeshift_timer .
%% Enum Atom scene_player begin
-define(move_msg, move_msg).
-define(switch_move_mode_msg, switch_move_mode_msg).
-define(move_stop_msg, move_stop_msg).
-define(jump_msg, jump_msg).
-define(resize_view_msg, resize_view_msg).
-define(die_msg, die_msg).
-define(enter_scene_msg, enter_scene_msg).
-define(leave_scene_msg, leave_scene_msg).
-define(release_skill_msg, release_skill_msg).
-define(skill_move_msg, skill_move_msg).
-define(release_buff_msg, release_buff_msg).
-define(msg_kickout, msg_kickout). %%% 被提下线 
-define(msg_relive, msg_relive). %%% 玩家复活 
-define(msg_kill_player, msg_kill_player).
-define(msg_kill_monster, msg_kill_monster).
-define(msg_add_item, msg_add_item).
-define(msg_del_item, msg_del_item).
-define(msg_add_prize, msg_add_prize).
-define(msg_pickup_drop_item, msg_pickup_drop_item).
-define(msg_kill_monster_add_exp, msg_kill_monster_add_exp).
-define(msg_killed_by_agent, msg_killed_by_agent).
-define(msg_killed_by_device, msg_killed_by_device).
-define(msg_game_frame, msg_game_frame).
-define(msg_update_attr, msg_update_attr).
-define(msg_add_hp, msg_add_hp).
-define(msg_del_hp, msg_del_hp).
-define(msg_full_hp_mp, msg_full_hp_mp).
-define(msg_full_hp, msg_full_hp).
-define(msg_full_mp, msg_full_mp).
-define(msg_update_view_data, msg_update_view_data).
-define(msg_update_equip_efts, msg_update_equip_efts).
-define(msg_update_shapeshift_data, msg_update_shapeshift_data).
-define(msg_update_ride_data, msg_update_ride_data).
-define(msg_shapeshift_timer, msg_shapeshift_timer).
%% Enum Atom scene_player end 

