%% Auto generated by defs from pet.def
%% Don't edit it.

-define(event_reaction_timeout, event_reaction_timeout).
-define(event_stiff_end, event_stiff_end).
-define(event_beat_back_stiff_end, event_beat_back_stiff_end).
-define(event_release_skill_over, event_release_skill_over).
-define(event_release_skill, event_release_skill).
-define(pd_all_pets, pd_all_pets).
-define(pd_prev_add_attr, pd_prev_add_attr).
-define(pd_pet_treasure, pd_pet_treasure).
-define(event_move_step, event_move_step).
-define(pd_fight_pets, pd_fight_pets).
-define(pd_pet_treasure_log, pd_pet_treasure_log).
-define(msg_enter_scene, msg_enter_scene).
-define(event_has_enemy, event_has_enemy).
-define(event_move_over, event_move_over).
-define(event_stroll_wait_timeout, event_stroll_wait_timeout).
-define(event_start, event_start).
-define(event_leave, event_leave).


