%% Auto generated by defs from scene_monster.def
%% Don't edit it.

-define(skill_release_finished, skill_release_finished).


-type m_event() :: event_start  | event_leave  | event_stroll_wait_timeout  | event_reaction_timeout  | event_move_over  | event_move_step  | event_release_skill  | event_release_skill_over  | event_ba_ti_end  | event_stiff_end  | event_beat_back_stiff_end  | event_has_enemy  | event_start_move .
%% Enum Atom m_event begin
-define(event_start, event_start). %%% 开始状态 
-define(event_leave, event_leave). %%% 离开一个状态 
-define(event_stroll_wait_timeout, event_stroll_wait_timeout).
-define(event_reaction_timeout, event_reaction_timeout).
-define(event_move_over, event_move_over). %%% 移动结束 
-define(event_move_step, event_move_step). %%% 移动了一步 
-define(event_release_skill, event_release_skill). %%%释放技能 
-define(event_release_skill_over, event_release_skill_over). %%% 技能释放完成，可以做出下一个动作 
-define(event_ba_ti_end, event_ba_ti_end).
-define(event_stiff_end, event_stiff_end). %%% 僵直状态取消 
-define(event_beat_back_stiff_end, event_beat_back_stiff_end).
-define(event_has_enemy, event_has_enemy). %%% 有敌人 
-define(event_start_move, event_start_move). %%% 开始移动 
%% Enum Atom m_event end 

-type monster_default_set() :: 1  | 100 .
%% Enum monster_default_set begin
-define(monster_min_level, 1).
-define(monster_max_level, 100).
%% Enum monster_default_set end 

-type mon_mtype() :: 1  | 2  | 3  | 4 .
%% Enum mon_mtype begin
-define(MT_QUALITY_1, 1).
-define(MT_QUALITY_2, 2).
-define(MT_QUALITY_3, 3).
-define(MT_QUALITY_4, 4).
%% Enum mon_mtype end 

-type mon_type() :: 1  | 2  | 3  | 4  | 5 .
%% Enum mon_type begin
-define(MT_NORMAL, 1).
-define(MT_CONVOY, 2).
-define(MT_BOOS, 3).
-define(MT_SKILL_OBJ, 4).
-define(MT_PET, 5).
%% Enum mon_type end 

