%% Auto generated by defs from scene.def
%% Don't edit it.

-define(releaseing_skill, releaseing_skill). %%% 被机关杀死
-define(fly_move_step, fly_move_step).
-define(large_move, large_move).
-define(skill_move, skill_move).
-define(pd_monsters_list, pd_monsters_list). %%%场景中的怪物列表
-define(scene_hit_box_ret, scene_hit_box_ret).
-define(pd_cfg_pk_modes, pd_cfg_pk_modes).
-define(scene_group, scene_group).
-define(pd_map_width, pd_map_width).
-define(pd_cfg_commands, pd_cfg_commands).
-define(pd_cfg_free_kill, pd_cfg_free_kill).
-define(pd_monster_index, pd_monster_index). %%% 怪物的唯一编号 integer
-define(pd_cfg_node, pd_cfg_node).
-define(sync_position, sync_position).
-define(pd_cfg_type, pd_cfg_type).
-define(pd_cfg_enter, pd_cfg_enter).
-define(pd_kill_normal_monster_count, pd_kill_normal_monster_count).
-define(pd_cfg_link, pd_cfg_link).
-define(pd_cfg_limit, pd_cfg_limit).
-define(gravity_move, gravity_move).
-define(pd_cfg_id, pd_cfg_id).
-define(pd_agent_list_tmp, pd_agent_list_tmp).
-define(pd_map_id, pd_map_id).
-define(pd_map_height, pd_map_height).
-define(pd_player_free_id, pd_player_free_id). %%% gb_trees
-define(pd_type_mod, pd_type_mod).
-define(pd_cfg_relive, pd_cfg_relive).
-define(pd_scene_count, pd_scene_count).
-define(pd_scene_id, pd_scene_id).
-define(killer_device, killer_device). %%% 碰撞结果
-define(move_stop, move_stop).
-define(pd_player_max_id, pd_player_max_id). %%% 下一个分配给player 的object id
-define(uniform_move, uniform_move).
-define(pd_monster_max_id, pd_monster_max_id). %%% 下一个分配给player 的object id
-define(pd_monster_free_id, pd_monster_free_id). %%% 下一个分配给player 的object id
-define(pd_kill_boss_monster_count, pd_kill_boss_monster_count).


-type main_in_difficulty() :: 1  | 2  | 3 .
%% Enum main_in_difficulty begin
-define(DIFF_EASY, 1).
-define(DIFF_NORMAL, 2).
-define(DIFF_DIFFICULT, 3).
%% Enum main_in_difficulty end 

-type move_type() :: 1  | 2 .
%% Enum move_type begin
-define(MT_MOVE, 1).
-define(MT_RUN, 2).
%% Enum move_type end 

