%% Auto generated by defs from scene.def
%% Don't edit it.

-module(scene_def).
-compile([export_all]).

-include("scene_def.hrl").

%% enum main_in_difficulty 
main_in_difficulty_to_s(?DIFF_EASY) -> <<"DIFF_EASY">>;
main_in_difficulty_to_s(?DIFF_NORMAL) -> <<"DIFF_NORMAL">>;
main_in_difficulty_to_s(?DIFF_DIFFICULT) -> <<"DIFF_DIFFICULT">>;
main_in_difficulty_to_s(_) -> invalid_id.

is_valid_main_in_difficulty(?DIFF_EASY) -> true;
is_valid_main_in_difficulty(?DIFF_NORMAL) -> true;
is_valid_main_in_difficulty(?DIFF_DIFFICULT) -> true;
is_valid_main_in_difficulty(_) -> false.
enum_main_in_difficulty_all() -> [1 , 2, 3].
enum_main_in_difficulty_size() -> 3.
%% enum move_type 
move_type_to_s(?MT_MOVE) -> <<"MT_MOVE">>;
move_type_to_s(?MT_RUN) -> <<"MT_RUN">>;
move_type_to_s(_) -> invalid_id.

is_valid_move_type(?MT_MOVE) -> true;
is_valid_move_type(?MT_RUN) -> true;
is_valid_move_type(_) -> false.
enum_move_type_all() -> [1 , 2].
enum_move_type_size() -> 2.
