%% Auto generated by defs from task.def
%% Don't edit it.

-module(task_def).
-compile([export_all]).

-include("task_def.hrl").

gola_type_module_all() -> [ task_plugin_kill_monster  , task_plugin_npc_talk  , task_plugin_collect_item  , task_plugin_buy_item  , task_plugin_guard_frontier  , task_plugin_single_instance ].
task_type_module_all() -> [ task_type_main  , task_type_branch  , task_type_daily ].
%% enum gola_type 
gola_type_to_s(?TG_KILL_MONSTER) -> <<"TG_KILL_MONSTER">>;
gola_type_to_s(?TG_NPC_TALK) -> <<"TG_NPC_TALK">>;
gola_type_to_s(?TG_COLLECT_ITEM) -> <<"TG_COLLECT_ITEM">>;
gola_type_to_s(?TG_BUY_ITEM) -> <<"TG_BUY_ITEM">>;
gola_type_to_s(?TG_COLLECT_VIRTUAL_GOODS) -> <<"TG_COLLECT_VIRTUAL_GOODS">>;
gola_type_to_s(?TG_GUARD_FRONTIER) -> <<"TG_GUARD_FRONTIER">>;
gola_type_to_s(?TG_SINGLE_INSTANCE) -> <<"TG_SINGLE_INSTANCE">>;
gola_type_to_s(?task_ev_gem_he_cheng) -> <<"task_ev_gem_he_cheng">>;
gola_type_to_s(?task_ev_pet_hatching) -> <<"task_ev_pet_hatching">>;
gola_type_to_s(?task_ev_pet_advance) -> <<"task_ev_pet_advance">>;
gola_type_to_s(?task_ev_pet_skill_level) -> <<"task_ev_pet_skill_level">>;
gola_type_to_s(?task_ev_pet_treasure) -> <<"task_ev_pet_treasure">>;
gola_type_to_s(?task_ev_guild_tech_level) -> <<"task_ev_guild_tech_level">>;
gola_type_to_s(?task_ev_guild_activity) -> <<"task_ev_guild_activity">>;
gola_type_to_s(?task_ev_friend_add) -> <<"task_ev_friend_add">>;
gola_type_to_s(?task_ev_crown_exchange) -> <<"task_ev_crown_exchange">>;
gola_type_to_s(?task_ev_crown_imbue) -> <<"task_ev_crown_imbue">>;
gola_type_to_s(?task_ev_crown_level) -> <<"task_ev_crown_level">>;
gola_type_to_s(?task_ev_arena_pve_fight) -> <<"task_ev_arena_pve_fight">>;
gola_type_to_s(?task_ev_arena_pev_fight_win) -> <<"task_ev_arena_pev_fight_win">>;
gola_type_to_s(?task_ev_seller_buy_item) -> <<"task_ev_seller_buy_item">>;
gola_type_to_s(?task_ev_get_item) -> <<"task_ev_get_item">>;
gola_type_to_s(?task_ev_equ_he_cheng) -> <<"task_ev_equ_he_cheng">>;
gola_type_to_s(?task_ev_equ_ji_cheng) -> <<"task_ev_equ_ji_cheng">>;
gola_type_to_s(?task_ev_equ_qiang_hua) -> <<"task_ev_equ_qiang_hua">>;
gola_type_to_s(?task_ev_equ_xiangqian) -> <<"task_ev_equ_xiangqian">>;
gola_type_to_s(?task_new_wizard) -> <<"task_new_wizard">>;
gola_type_to_s(?task_ev_nine_star_pass_ins) -> <<"task_ev_nine_star_pass_ins">>;
gola_type_to_s(?task_ev_blessing) -> <<"task_ev_blessing">>;
gola_type_to_s(?task_ev_mount) -> <<"task_ev_mount">>;
gola_type_to_s(_) -> invalid_id.

is_valid_gola_type(?TG_KILL_MONSTER) -> true;
is_valid_gola_type(?TG_NPC_TALK) -> true;
is_valid_gola_type(?TG_COLLECT_ITEM) -> true;
is_valid_gola_type(?TG_BUY_ITEM) -> true;
is_valid_gola_type(?TG_COLLECT_VIRTUAL_GOODS) -> true;
is_valid_gola_type(?TG_GUARD_FRONTIER) -> true;
is_valid_gola_type(?TG_SINGLE_INSTANCE) -> true;
is_valid_gola_type(?task_ev_gem_he_cheng) -> true;
is_valid_gola_type(?task_ev_pet_hatching) -> true;
is_valid_gola_type(?task_ev_pet_advance) -> true;
is_valid_gola_type(?task_ev_pet_skill_level) -> true;
is_valid_gola_type(?task_ev_pet_treasure) -> true;
is_valid_gola_type(?task_ev_guild_tech_level) -> true;
is_valid_gola_type(?task_ev_guild_activity) -> true;
is_valid_gola_type(?task_ev_friend_add) -> true;
is_valid_gola_type(?task_ev_crown_exchange) -> true;
is_valid_gola_type(?task_ev_crown_imbue) -> true;
is_valid_gola_type(?task_ev_crown_level) -> true;
is_valid_gola_type(?task_ev_arena_pve_fight) -> true;
is_valid_gola_type(?task_ev_arena_pev_fight_win) -> true;
is_valid_gola_type(?task_ev_seller_buy_item) -> true;
is_valid_gola_type(?task_ev_get_item) -> true;
is_valid_gola_type(?task_ev_equ_he_cheng) -> true;
is_valid_gola_type(?task_ev_equ_ji_cheng) -> true;
is_valid_gola_type(?task_ev_equ_qiang_hua) -> true;
is_valid_gola_type(?task_ev_equ_xiangqian) -> true;
is_valid_gola_type(?task_new_wizard) -> true;
is_valid_gola_type(?task_ev_nine_star_pass_ins) -> true;
is_valid_gola_type(?task_ev_blessing) -> true;
is_valid_gola_type(?task_ev_mount) -> true;
is_valid_gola_type(_) -> false.
enum_gola_type_all() -> [1 , 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32].
enum_gola_type_size() -> 30.
gola_type_to_i(task_plugin_kill_monster) -> ?TG_KILL_MONSTER;
gola_type_to_i(task_plugin_npc_talk) -> ?TG_NPC_TALK;
gola_type_to_i(task_plugin_collect_item) -> ?TG_COLLECT_ITEM;
gola_type_to_i(task_plugin_buy_item) -> ?TG_BUY_ITEM;
gola_type_to_i(task_plugin_guard_frontier) -> ?TG_GUARD_FRONTIER;
gola_type_to_i(task_plugin_single_instance) -> ?TG_SINGLE_INSTANCE;
gola_type_to_i(_) -> badarg.

gola_type_to_a(?TG_KILL_MONSTER) -> task_plugin_kill_monster;
gola_type_to_a(?TG_NPC_TALK) -> task_plugin_npc_talk;
gola_type_to_a(?TG_COLLECT_ITEM) -> task_plugin_collect_item;
gola_type_to_a(?TG_BUY_ITEM) -> task_plugin_buy_item;
gola_type_to_a(?TG_GUARD_FRONTIER) -> task_plugin_guard_frontier;
gola_type_to_a(?TG_SINGLE_INSTANCE) -> task_plugin_single_instance;
gola_type_to_a(_) -> badarg.

%% enum task_type 
task_type_to_s(?TT_MAIN) -> <<"TT_MAIN">>;
task_type_to_s(?TT_BRANCH) -> <<"TT_BRANCH">>;
task_type_to_s(?TT_DAILY) -> <<"TT_DAILY">>;
task_type_to_s(_) -> invalid_id.

is_valid_task_type(?TT_MAIN) -> true;
is_valid_task_type(?TT_BRANCH) -> true;
is_valid_task_type(?TT_DAILY) -> true;
is_valid_task_type(_) -> false.
enum_task_type_all() -> [0 , 1, 2].
enum_task_type_size() -> 3.
task_type_to_i(task_type_main) -> ?TT_MAIN;
task_type_to_i(task_type_branch) -> ?TT_BRANCH;
task_type_to_i(task_type_daily) -> ?TT_DAILY;
task_type_to_i(_) -> badarg.

task_type_to_a(?TT_MAIN) -> task_type_main;
task_type_to_a(?TT_BRANCH) -> task_type_branch;
task_type_to_a(?TT_DAILY) -> task_type_daily;
task_type_to_a(_) -> badarg.

