%% Auto generated by defs from task.def
%% Don't edit it.

-define(task_plugin_single_instance, task_plugin_single_instance).
-define(task_plugin_buy_item, task_plugin_buy_item).
-define(task_plugin_kill_monster, task_plugin_kill_monster).
-define(task_type_daily, task_type_daily).
-define(task_plugin_guard_frontier, task_plugin_guard_frontier).
-define(task_plugin_collect_item, task_plugin_collect_item).
-define(task_type_branch, task_type_branch).
-define(task_plugin_npc_talk, task_plugin_npc_talk).
-define(task_type_main, task_type_main).


-type gola_type_module() :: task_plugin_kill_monster  | task_plugin_npc_talk  | task_plugin_collect_item  | task_plugin_buy_item  | task_plugin_guard_frontier  | task_plugin_single_instance .
%% Enum Atom gola_type_module begin
% -define(task_plugin_kill_monster, task_plugin_kill_monster).
% -define(task_plugin_npc_talk, task_plugin_npc_talk).
% -define(task_plugin_collect_item, task_plugin_collect_item).
% -define(task_plugin_buy_item, task_plugin_buy_item).
% -define(task_plugin_guard_frontier, task_plugin_guard_frontier).
% -define(task_plugin_single_instance, task_plugin_single_instance).
%% Enum Atom gola_type_module end 

-type task_type_module() :: task_type_main  | task_type_branch  | task_type_daily .
%% Enum Atom task_type_module begin
% -define(task_type_main, task_type_main).
% -define(task_type_branch, task_type_branch).
% -define(task_type_daily, task_type_daily).
%% Enum Atom task_type_module end 

-type gola_type() :: 1  | 2  | 3  | 4  | 5  | 7  | 8  | 9  | 10  | 11  | 12  | 13  | 14  | 15  | 16  | 17  | 18  | 19  | 20  | 21  | 22  | 23  | 24  | 25  | 26  | 27  | 28  | 30  | 31  | 32 .
%% Enum gola_type begin
-define(TG_KILL_MONSTER, 1).
-define(TG_NPC_TALK, 2).
-define(TG_COLLECT_ITEM, 3).
-define(TG_BUY_ITEM, 4).
-define(TG_COLLECT_VIRTUAL_GOODS, 5).
-define(TG_GUARD_FRONTIER, 7).
-define(TG_SINGLE_INSTANCE, 8).
-define(task_ev_gem_he_cheng, 9).
-define(task_ev_pet_hatching, 10).
-define(task_ev_pet_advance, 11).
-define(task_ev_pet_skill_level, 12).
-define(task_ev_pet_treasure, 13).
-define(task_ev_guild_tech_level, 14).
-define(task_ev_guild_activity, 15).
-define(task_ev_friend_add, 16).
-define(task_ev_crown_exchange, 17).
-define(task_ev_crown_imbue, 18).
-define(task_ev_crown_level, 19).
-define(task_ev_arena_pve_fight, 20).
-define(task_ev_arena_pev_fight_win, 21).
-define(task_ev_seller_buy_item, 22).
-define(task_ev_get_item, 23).
-define(task_ev_equ_he_cheng, 24).
-define(task_ev_equ_ji_cheng, 25).
-define(task_ev_equ_qiang_hua, 26).
-define(task_ev_equ_xiangqian, 27).
-define(task_new_wizard, 28).
-define(task_ev_nine_star_pass_ins, 30).
-define(task_ev_blessing, 31).
-define(task_ev_mount, 32).
%% Enum gola_type end 

-type task_type() :: 0  | 1  | 2 .
%% Enum task_type begin
-define(TT_MAIN, 0).
-define(TT_BRANCH, 1).
-define(TT_DAILY, 2).
%% Enum task_type end 

