{application,pangzi,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{pangzi_app,[]}},
              {env,[{gen_mod,pangzi_dbcache}]},
              {modules,[pangzi,pangzi_app,pangzi_behaviour,pangzi_gen_code,
                        pangzi_sup,pangzi_worker]}]}.
