%% Auto generated by sproto from robot_debug.sproto
%% Don't edit it.

-define(MSG_DEBUG_SKILL_HIT_AREA, 25345). %% hight:99 id1
-define(MSG_DEBUG_MOVE, 25346). %% hight:99 id2
-define(MSG_DEBUG_ERROR_MSG, 25347). %% hight:99 id3
