%% Auto generated by sproto from robot_player.sproto
%% Don't edit it.

-module(robot_player_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("robot_player_sproto.hrl").

%% id=1  
pkg_msg(?MSG_PLAYER_ACCOUNT_LOGIN, {PlatformPlayerName, Passworld, PlatformId, ServerId, Machine_mac, Machine_id, Machine_style, Machine_info}) ->
<<?MSG_PLAYER_ACCOUNT_LOGIN:16, 
(byte_size(PlatformPlayerName)), PlatformPlayerName/binary,
    (byte_size(Passworld)), Passworld/binary,
    PlatformId,
    ServerId:16,
    (byte_size(Machine_mac)), Machine_mac/binary,
    (byte_size(Machine_id)), Machine_id/binary,
    (byte_size(Machine_style)), Machine_style/binary,
    (byte_size(Machine_info)), Machine_info/binary>>
;

%% id=4  
pkg_msg(?MSG_PLAYER_CREATE_ROLE, {Index, Career, Name}) ->
<<?MSG_PLAYER_CREATE_ROLE:16, 
Index,
    Career,
    Name/binary>>
;

%% id=7  
pkg_msg(?MSG_PLAYER_CLIENT_DATA_POST, {Type, Data}) ->
<<?MSG_PLAYER_CLIENT_DATA_POST:16, 
Type,
    Data/binary>>
;

%% id=8  
pkg_msg(?MSG_PLAYER_CLIENT_DATA_GET, {Type}) ->
<<?MSG_PLAYER_CLIENT_DATA_GET:16, 
Type>>
;

%% id=10  
pkg_msg(?MSG_PLAYER_ECHO, {Msg}) ->
<<?MSG_PLAYER_ECHO:16, 
Msg/binary>>
;

%% id=11  
pkg_msg(?MSG_PLAYER_GET_SERVER_TIME, {}) ->
<<?MSG_PLAYER_GET_SERVER_TIME:16>> 
;

%% id=17  
pkg_msg(?MSG_PLAYER_LOOKUP_PLAYER_ATTR, {Id}) ->
<<?MSG_PLAYER_LOOKUP_PLAYER_ATTR:16, 
Id:64>>
;

%% id=31  
pkg_msg(?MSG_PLAYER_NAME_TO_ID, {Name}) ->
<<?MSG_PLAYER_NAME_TO_ID:16, 
(byte_size(Name)), Name/binary>>
;

%% id=32  
pkg_msg(?MSG_PLAYER_SYS_TIME, {}) ->
<<?MSG_PLAYER_SYS_TIME:16>> 
;

%% id=35  
pkg_msg(?MSG_PLAYER_COST_DIAMOND_BUY_SP, {Count}) ->
<<?MSG_PLAYER_COST_DIAMOND_BUY_SP:16, 
Count>>
;

%% id=36  
pkg_msg(?MSG_VERSION, {DebugId, MainVersionId, AssistVersionId, ResourceVersionId}) ->
<<?MSG_VERSION:16, 
DebugId:16,
    MainVersionId:16,
    AssistVersionId:16,
    ResourceVersionId:16>>
;

%% id=37  
pkg_msg(?MSG_PLAYER_TASK_IS_OPEN, {}) ->
<<?MSG_PLAYER_TASK_IS_OPEN:16>> 
;

%% id=44  
pkg_msg(?MSG_SHOW_NEAR_PLAYER_SET, {Receive}) ->
<<?MSG_SHOW_NEAR_PLAYER_SET:16, 
Receive:16>>
;

%% id=45  
pkg_msg(?MSG_PLAYER_DELETE, {Index}) ->
<<?MSG_PLAYER_DELETE:16, 
Index>>
;

%% id=46  
pkg_msg(?MSG_PLAYER_JOIN_GAME, {Index, Wx, Wy}) ->
<<?MSG_PLAYER_JOIN_GAME:16, 
Index,
    Wx,
    Wy>>
;

%% id=49  
pkg_msg(?MSG_PLAYER_QQ_AUTH_LOGIN, {Openid, AccessToken, PlatformId, ServerId, Machine_mac, Machine_id, Machine_style, Machine_info}) ->
<<?MSG_PLAYER_QQ_AUTH_LOGIN:16, 
(byte_size(Openid)), Openid/binary,
    (byte_size(AccessToken)), AccessToken/binary,
    PlatformId,
    ServerId:16,
    (byte_size(Machine_mac)), Machine_mac/binary,
    (byte_size(Machine_id)), Machine_id/binary,
    (byte_size(Machine_style)), Machine_style/binary,
    (byte_size(Machine_info)), Machine_info/binary>>
;

%% id=50  
pkg_msg(?MSG_PLAYER_PING, {}) ->
<<?MSG_PLAYER_PING:16>> 
;

%% id=51  
pkg_msg(?MSG_PLAYER_RECONNECTION, {PlatformPlayerName, PlatformId, ServerId, Machine_mac, Machine_id, Machine_style, Machine_info, Index, Wx, Wy}) ->
<<?MSG_PLAYER_RECONNECTION:16, 
(byte_size(PlatformPlayerName)), PlatformPlayerName/binary,
    PlatformId,
    ServerId:16,
    (byte_size(Machine_mac)), Machine_mac/binary,
    (byte_size(Machine_id)), Machine_id/binary,
    (byte_size(Machine_style)), Machine_style/binary,
    (byte_size(Machine_info)), Machine_info/binary,
    Index,
    Wx,
    Wy>>
;

%% id=54  
pkg_msg(?MSG_PLAYER_UNDRESS_SHAPESHIFT, {}) ->
<<?MSG_PLAYER_UNDRESS_SHAPESHIFT:16>> 
;

%% id=55  
pkg_msg(?MSG_PLAYER_DO_SURVEY_NOTIFY, {}) ->
<<?MSG_PLAYER_DO_SURVEY_NOTIFY:16>> 
;

%% id=56  
pkg_msg(?MSG_PLAYER_SP_REFRESH_TIME, {}) ->
<<?MSG_PLAYER_SP_REFRESH_TIME:16>> 
;

%% id=57  
pkg_msg(?MSG_PLAYER_CD_KEY, {Cd_key}) ->
<<?MSG_PLAYER_CD_KEY:16, 
(byte_size(Cd_key)), Cd_key/binary>>
;

%% id=58  
pkg_msg(?MSG_PLAYER_ADD_HOURLY_SP, {}) ->
<<?MSG_PLAYER_ADD_HOURLY_SP:16>> 
;

%% id=59  
pkg_msg(?MSG_PLAYER_PUSH_HOURLY_SP_STATUS, {}) ->
<<?MSG_PLAYER_PUSH_HOURLY_SP_STATUS:16>> 
;

%% id=60  
pkg_msg(?MSG_PLAYER_RESET_PLAYER_NAME, {Name}) ->
<<?MSG_PLAYER_RESET_PLAYER_NAME:16, 
(byte_size(Name)), Name/binary>>
;

%% id=61  
pkg_msg(?MSG_PLAYER_PROGRESS_NOTICE, {Progress_id}) ->
<<?MSG_PLAYER_PROGRESS_NOTICE:16, 
Progress_id:16>>
;

%% id=62  
pkg_msg(?MSG_PLAYER_PUSH_SHARE_GAME, {}) ->
<<?MSG_PLAYER_PUSH_SHARE_GAME:16>> 
;

%% id=63  
pkg_msg(?MSG_PLAYER_GET_SHARE_GAME_PRIZE, {Type}) ->
<<?MSG_PLAYER_GET_SHARE_GAME_PRIZE:16, 
Type>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_PLAYER_ACCOUNT_LOGIN, Acc0) ->
<<Finalplayer,
Info/binary>> = Acc0,
 {{Finalplayer,Info}, <<>>};

%% id = 2  
unpkg_msg(?MSG_PLAYER_ERROR, Acc0) ->
<<CmdId:16,
ErrCode:16,
Arg/binary>> = Acc0,
 {{CmdId,ErrCode,Arg}, <<>>};

%% id = 4  
unpkg_msg(?MSG_PLAYER_CREATE_ROLE, Acc0) ->
{{}, Acc0};

%% id = 8  
unpkg_msg(?MSG_PLAYER_CLIENT_DATA_GET, Acc0) ->
<<Type,
Data/binary>> = Acc0,
 {{Type,Data}, <<>>};

%% id = 9  
unpkg_msg(?MSG_PLAYER_ONLINE_FINISH, Acc0) ->
<<Uptime:64,
Acc1/binary>> = Acc0,
 {{Uptime}, Acc1};

%% id = 10  
unpkg_msg(?MSG_PLAYER_ECHO, Acc0) ->
<<Msg/binary>> = Acc0,
 {{Msg}, <<>>};

%% id = 11  
unpkg_msg(?MSG_PLAYER_GET_SERVER_TIME, Acc0) ->
<<TimetampMsec:64,
Acc1/binary>> = Acc0,
 {{TimetampMsec}, Acc1};

%% id = 15  
unpkg_msg(?MSG_PLAYER_DATA_CHANGED, Acc0) ->
<<Type,
Value:32,
Acc1/binary>> = Acc0,
 {{Type,Value}, Acc1};

%% id = 16  
unpkg_msg(?MSG_PLAYER_ATTR_CHANGE, Acc0) ->
{Attr, Acc1} = unpkg_attr__(Acc0)
,
{{Attr}, Acc1};

%% id = 17  
unpkg_msg(?MSG_PLAYER_LOOKUP_PLAYER_ATTR, Acc0) ->
<<Id:64,
NameLen, Name:NameLen/binary,
Career,
Level,
CombatPower:32,
Acc1/binary>> = Acc0,
{Attr, Acc2} = unpkg_attr__(Acc1)
,
<<L__EqmL:16, Acc3/binary>> = Acc2,
{EqmL, Acc4} = unpkg_list_struct__(L__EqmL, Acc3, [], fun unpkg_item_info__/1)
,
<<L__List:16, Acc5/binary>> = Acc4,
{List, Acc6} = unpkg_list_struct__(L__List, Acc5, [], fun unpkg_ano_s__0/1)
,
{{Id,Name,Career,Level,CombatPower,Attr,EqmL,List}, Acc6};

%% id = 30  
unpkg_msg(?MSG_PLAYER_INIT_CLIENT, Acc0) ->
<<PlayerId:64,
NameLen, Name:NameLen/binary,
Career,
Level,
Exp:32,
Fragment:32,
Longwen:32,
Money:32,
Diamond:32,
Honour:32,
Jinxing:32,
Yinxing:32,
Hp:32,
Mp:32,
Sp:16,
Sp_count,
Acc1/binary>> = Acc0,
{Attr, Acc2} = unpkg_attr__(Acc1)
,
<<Combat_power:32,
Yuansu_moli:32,
Guangan_moli:32,
Mingyun_moli:32,
Acc3/binary>> = Acc2,
 {{PlayerId,Name,Career,Level,Exp,Fragment,Longwen,Money,Diamond,Honour,Jinxing,Yinxing,Hp,Mp,Sp,Sp_count,Attr,Combat_power,Yuansu_moli,Guangan_moli,Mingyun_moli}, Acc3};

%% id = 31  
unpkg_msg(?MSG_PLAYER_NAME_TO_ID, Acc0) ->
<<PlayerId:64,
NameLen, Name:NameLen/binary,
Acc1/binary>> = Acc0,
 {{PlayerId,Name}, Acc1};

%% id = 32  
unpkg_msg(?MSG_PLAYER_SYS_TIME, Acc0) ->
<<Time_sec:64,
Acc1/binary>> = Acc0,
 {{Time_sec}, Acc1};

%% id = 33  
unpkg_msg(?MSG_PLAYER_SYNC_SOCIETY_BUFS, Acc0) ->
<<L__society_bufs:16, Acc1/binary>> = Acc0,
{Society_bufs, Acc2} = 
unpkg_list_u16(L__society_bufs, Acc1, []),
{{Society_bufs}, Acc2};

%% id = 34  
unpkg_msg(?MSG_PLAYER_SYNC_FIELD, Acc0) ->
<<L__fields:16, Acc1/binary>> = Acc0,
{Fields, Acc2} = unpkg_list_struct__(L__fields, Acc1, [], fun unpkg_ano_s__1/1)
,
{{Fields}, Acc2};

%% id = 35  
unpkg_msg(?MSG_PLAYER_COST_DIAMOND_BUY_SP, Acc0) ->
<<Reply,
Acc1/binary>> = Acc0,
 {{Reply}, Acc1};

%% id = 36  
unpkg_msg(?MSG_VERSION, Acc0) ->
<<ReplyNum,
Acc1/binary>> = Acc0,
 {{ReplyNum}, Acc1};

%% id = 37  
unpkg_msg(?MSG_PLAYER_TASK_IS_OPEN, Acc0) ->
<<Isopen,
Acc1/binary>> = Acc0,
 {{Isopen}, Acc1};

%% id = 38  
unpkg_msg(?MSG_PLAYER_FIELD_CHANGE, Acc0) ->
<<L__fields:16, Acc1/binary>> = Acc0,
{Fields, Acc2} = unpkg_list_struct__(L__fields, Acc1, [], fun unpkg_ano_s__2/1)
,
{{Fields}, Acc2};

%% id = 39  
unpkg_msg(?MSG_PLAYER_SKILL_CHANGE, Acc0) ->
<<L__skill_change:16, Acc1/binary>> = Acc0,
{Skill_change, Acc2} = 
unpkg_list_u32(L__skill_change, Acc1, []),
{{Skill_change}, Acc2};

%% id = 40  
unpkg_msg(?MSG_PLAYER_EFFECT_CHANGE, Acc0) ->
<<L__effect:16, Acc1/binary>> = Acc0,
{Effect, Acc2} = 
unpkg_list_u16(L__effect, Acc1, []),
{{Effect}, Acc2};

%% id = 41  
unpkg_msg(?MSG_PLAYER_AVATAR_CHANGE, Acc0) ->
<<Job,
L__changeset:16, Acc1/binary>> = Acc0,
{Changeset, Acc2} = 
unpkg_list_u32(L__changeset, Acc1, []),
{{Job,Changeset}, Acc2};

%% id = 42  
unpkg_msg(?MSG_PLAYER_OFFLINE_INFO, Acc0) ->
<<Errorcode,
Acc1/binary>> = Acc0,
 {{Errorcode}, Acc1};

%% id = 43  
unpkg_msg(?MSG_PLAYER_EARNINGS_CHANGE, Acc0) ->
<<Result:16,
Acc1/binary>> = Acc0,
 {{Result}, Acc1};

%% id = 44  
unpkg_msg(?MSG_SHOW_NEAR_PLAYER_SET, Acc0) ->
<<Send:16,
Acc1/binary>> = Acc0,
 {{Send}, Acc1};

%% id = 47  
unpkg_msg(?MSG_DRESS_SHAPESHIFT, Acc0) ->
<<CardId:32,
Acc1/binary>> = Acc0,
 {{CardId}, Acc1};

%% id = 45  
unpkg_msg(?MSG_PLAYER_DELETE, Acc0) ->
<<Isok,
Acc1/binary>> = Acc0,
 {{Isok}, Acc1};

%% id = 48  
unpkg_msg(?MSG_PLAYER_GM, Acc0) ->
<<L__info:16, Acc1/binary>> = Acc0,
{Info, Acc2} = unpkg_list_struct__(L__info, Acc1, [], fun unpkg_ano_s__3/1)
,
{{Info}, Acc2};

%% id = 49  
unpkg_msg(?MSG_PLAYER_QQ_AUTH_LOGIN, Acc0) ->
<<Finalplayer,
Info/binary>> = Acc0,
 {{Finalplayer,Info}, <<>>};

%% id = 50  
unpkg_msg(?MSG_PLAYER_PING, Acc0) ->
{{}, Acc0};

%% id = 51  
unpkg_msg(?MSG_PLAYER_RECONNECTION, Acc0) ->
<<Isok,
Acc1/binary>> = Acc0,
 {{Isok}, Acc1};

%% id = 52  
unpkg_msg(?MSG_PlAYER_RIDE, Acc0) ->
<<RideId:16,
Acc1/binary>> = Acc0,
 {{RideId}, Acc1};

%% id = 53  
unpkg_msg(?MSG_PLAYER_ACTIVITY_LIST, Acc0) ->
<<Info/binary>> = Acc0,
 {{Info}, <<>>};

%% id = 55  
unpkg_msg(?MSG_PLAYER_DO_SURVEY_NOTIFY, Acc0) ->
<<Result,
Acc1/binary>> = Acc0,
 {{Result}, Acc1};

%% id = 56  
unpkg_msg(?MSG_PLAYER_SP_REFRESH_TIME, Acc0) ->
<<Time_sec:32,
Acc1/binary>> = Acc0,
 {{Time_sec}, Acc1};

%% id = 57  
unpkg_msg(?MSG_PLAYER_CD_KEY, Acc0) ->
<<ReplyNum,
Acc1/binary>> = Acc0,
 {{ReplyNum}, Acc1};

%% id = 58  
unpkg_msg(?MSG_PLAYER_ADD_HOURLY_SP, Acc0) ->
<<ReplyNum,
Acc1/binary>> = Acc0,
 {{ReplyNum}, Acc1};

%% id = 59  
unpkg_msg(?MSG_PLAYER_PUSH_HOURLY_SP_STATUS, Acc0) ->
<<Status,
Acc1/binary>> = Acc0,
 {{Status}, Acc1};

%% id = 60  
unpkg_msg(?MSG_PLAYER_RESET_PLAYER_NAME, Acc0) ->
<<Issuc,
Acc1/binary>> = Acc0,
 {{Issuc}, Acc1};

%% id = 62  
unpkg_msg(?MSG_PLAYER_PUSH_SHARE_GAME, Acc0) ->
<<Status,
Prize_status,
Acc1/binary>> = Acc0,
 {{Status,Prize_status}, Acc1};

%% id = 63  
unpkg_msg(?MSG_PLAYER_GET_SHARE_GAME_PRIZE, Acc0) ->
<<Reply,
Acc1/binary>> = Acc0,
 {{Reply}, Acc1};
unpkg_msg(Id, _) -> ok.


unpkg_attr__(Acc0) ->
<<AttId,
AttHp:32,
AttMp:32,
AttSp:32,
AttNp:32,
AttStrength:32,
AttIntellect:32,
AttNimble:32,
AttStrong:32,
AttAtk:32,
AttDef:32,
AttCrit:32,
AttBlock:32,
AttPliable:32,
AttPure_atk:32,
AttBreak_def:32,
AttAtk_deep:32,
AttAtk_free:32,
AttAtk_speed:32,
AttPrecise:32,
AttThunder_atk:32,
AttThunder_def:32,
AttFire_atk:32,
AttFire_def:32,
AttIce_atk:32,
AttIce_def:32,
AttMove_speed:32,
AttRun_speed:32,
AttSuckBlood:32,
AttReverse:32,
AttBati:32,
Acc1/binary>> = Acc0,
 {{AttId,AttHp,AttMp,AttSp,AttNp,AttStrength,AttIntellect,AttNimble,AttStrong,AttAtk,AttDef,AttCrit,AttBlock,AttPliable,AttPure_atk,AttBreak_def,AttAtk_deep,AttAtk_free,AttAtk_speed,AttPrecise,AttThunder_atk,AttThunder_def,AttFire_atk,AttFire_def,AttIce_atk,AttIce_def,AttMove_speed,AttRun_speed,AttSuckBlood,AttReverse,AttBati}, Acc1}.
unpkg_item_info__(Acc0) ->
<<Id:32,
Bid:32,
Pos,
Qly,
Qua:16,
Bind,
IsJd,
SuitId:32,
QhLev,
Power:32,
L__ExtraAttr:16, Acc1/binary>> = Acc0,
{ExtraAttr, Acc2} = unpkg_list_struct__(L__ExtraAttr, Acc1, [], fun unpkg_ano_s__4/1)
,
<<L__GemInfo:16, Acc3/binary>> = Acc2,
{GemInfo, Acc4} = 
unpkg_list_u32(L__GemInfo, Acc3, []),
<<L__ItemEx:16, Acc5/binary>> = Acc4,
{ItemEx, Acc6} = unpkg_list_struct__(L__ItemEx, Acc5, [], fun unpkg_ano_s__5/1)
,
<<L__SkillChanges:16, Acc7/binary>> = Acc6,
{SkillChanges, Acc8} = 
unpkg_list_u32(L__SkillChanges, Acc7, []),
<<L__JDListMax:16, Acc9/binary>> = Acc8,
{JDListMax, Acc10} = 
unpkg_list_u32(L__JDListMax, Acc9, []),
<<L__JDListMin:16, Acc11/binary>> = Acc10,
{JDListMin, Acc12} = 
unpkg_list_u32(L__JDListMin, Acc11, []),
<<Fumo:16,
L__fumoAttrList:16, Acc13/binary>> = Acc12,
{FumoAttrList, Acc14} = unpkg_list_struct__(L__fumoAttrList, Acc13, [], fun unpkg_ano_s__6/1)
,
{{Id,Bid,Pos,Qly,Qua,Bind,IsJd,SuitId,QhLev,Power,ExtraAttr,GemInfo,ItemEx,SkillChanges,JDListMax,JDListMin,Fumo,FumoAttrList}, Acc14}.
unpkg_ano_s__0(Acc0) ->
<<PartType,
QhLevel,
Acc1/binary>> = Acc0,
 {{PartType,QhLevel}, Acc1}.
unpkg_ano_s__1(Acc0) ->
<<Id:16,
Val:32,
Acc1/binary>> = Acc0,
 {{Id,Val}, Acc1}.
unpkg_ano_s__2(Acc0) ->
<<Ids:32,
L__vals:16, Acc1/binary>> = Acc0,
{Vals, Acc2} = 
unpkg_list_u32(L__vals, Acc1, []),
{{Ids,Vals}, Acc2}.
unpkg_ano_s__3(Acc0) ->
<<Index,
Val,
Acc1/binary>> = Acc0,
 {{Index,Val}, Acc1}.
unpkg_ano_s__4(Acc0) ->
<<ExtraModId,
L__Attr:16, Acc1/binary>> = Acc0,
{Attr, Acc2} = unpkg_list_struct__(L__Attr, Acc1, [], fun unpkg_ano_s__7/1)
,
{{ExtraModId,Attr}, Acc2}.
unpkg_ano_s__5(Acc0) ->
<<Key,
Val:32,
Acc1/binary>> = Acc0,
 {{Key,Val}, Acc1}.
unpkg_ano_s__6(Acc0) ->
<<TypeId,
AttrId,
AttrVal:32,
Acc1/binary>> = Acc0,
 {{TypeId,AttrId,AttrVal}, Acc1}.
unpkg_ano_s__7(Acc0) ->
<<AttrCode,
AttrVal:32,
AttrPer,
Acc1/binary>> = Acc0,
 {{AttrCode,AttrVal,AttrPer}, Acc1}.


to_s(?MSG_PLAYER_ACCOUNT_LOGIN) -> <<"MSG_PLAYER_ACCOUNT_LOGIN">>; %% high 1, id 1
to_s(?MSG_PLAYER_ERROR) -> <<"MSG_PLAYER_ERROR">>; %% high 1, id 2
to_s(?MSG_PLAYER_CREATE_ROLE) -> <<"MSG_PLAYER_CREATE_ROLE">>; %% high 1, id 4
to_s(?MSG_PLAYER_CLIENT_DATA_POST) -> <<"MSG_PLAYER_CLIENT_DATA_POST">>; %% high 1, id 7
to_s(?MSG_PLAYER_CLIENT_DATA_GET) -> <<"MSG_PLAYER_CLIENT_DATA_GET">>; %% high 1, id 8
to_s(?MSG_PLAYER_ONLINE_FINISH) -> <<"MSG_PLAYER_ONLINE_FINISH">>; %% high 1, id 9
to_s(?MSG_PLAYER_ECHO) -> <<"MSG_PLAYER_ECHO">>; %% high 1, id 10
to_s(?MSG_PLAYER_GET_SERVER_TIME) -> <<"MSG_PLAYER_GET_SERVER_TIME">>; %% high 1, id 11
to_s(?MSG_PLAYER_DATA_CHANGED) -> <<"MSG_PLAYER_DATA_CHANGED">>; %% high 1, id 15
to_s(?MSG_PLAYER_ATTR_CHANGE) -> <<"MSG_PLAYER_ATTR_CHANGE">>; %% high 1, id 16
to_s(?MSG_PLAYER_LOOKUP_PLAYER_ATTR) -> <<"MSG_PLAYER_LOOKUP_PLAYER_ATTR">>; %% high 1, id 17
to_s(?MSG_PLAYER_INIT_CLIENT) -> <<"MSG_PLAYER_INIT_CLIENT">>; %% high 1, id 30
to_s(?MSG_PLAYER_NAME_TO_ID) -> <<"MSG_PLAYER_NAME_TO_ID">>; %% high 1, id 31
to_s(?MSG_PLAYER_SYS_TIME) -> <<"MSG_PLAYER_SYS_TIME">>; %% high 1, id 32
to_s(?MSG_PLAYER_SYNC_SOCIETY_BUFS) -> <<"MSG_PLAYER_SYNC_SOCIETY_BUFS">>; %% high 1, id 33
to_s(?MSG_PLAYER_SYNC_FIELD) -> <<"MSG_PLAYER_SYNC_FIELD">>; %% high 1, id 34
to_s(?MSG_PLAYER_COST_DIAMOND_BUY_SP) -> <<"MSG_PLAYER_COST_DIAMOND_BUY_SP">>; %% high 1, id 35
to_s(?MSG_VERSION) -> <<"MSG_VERSION">>; %% high 1, id 36
to_s(?MSG_PLAYER_TASK_IS_OPEN) -> <<"MSG_PLAYER_TASK_IS_OPEN">>; %% high 1, id 37
to_s(?MSG_PLAYER_FIELD_CHANGE) -> <<"MSG_PLAYER_FIELD_CHANGE">>; %% high 1, id 38
to_s(?MSG_PLAYER_SKILL_CHANGE) -> <<"MSG_PLAYER_SKILL_CHANGE">>; %% high 1, id 39
to_s(?MSG_PLAYER_EFFECT_CHANGE) -> <<"MSG_PLAYER_EFFECT_CHANGE">>; %% high 1, id 40
to_s(?MSG_PLAYER_AVATAR_CHANGE) -> <<"MSG_PLAYER_AVATAR_CHANGE">>; %% high 1, id 41
to_s(?MSG_PLAYER_OFFLINE_INFO) -> <<"MSG_PLAYER_OFFLINE_INFO">>; %% high 1, id 42
to_s(?MSG_PLAYER_EARNINGS_CHANGE) -> <<"MSG_PLAYER_EARNINGS_CHANGE">>; %% high 1, id 43
to_s(?MSG_SHOW_NEAR_PLAYER_SET) -> <<"MSG_SHOW_NEAR_PLAYER_SET">>; %% high 1, id 44
to_s(?MSG_DRESS_SHAPESHIFT) -> <<"MSG_DRESS_SHAPESHIFT">>; %% high 1, id 47
to_s(?MSG_PLAYER_DELETE) -> <<"MSG_PLAYER_DELETE">>; %% high 1, id 45
to_s(?MSG_PLAYER_JOIN_GAME) -> <<"MSG_PLAYER_JOIN_GAME">>; %% high 1, id 46
to_s(?MSG_PLAYER_GM) -> <<"MSG_PLAYER_GM">>; %% high 1, id 48
to_s(?MSG_PLAYER_QQ_AUTH_LOGIN) -> <<"MSG_PLAYER_QQ_AUTH_LOGIN">>; %% high 1, id 49
to_s(?MSG_PLAYER_PING) -> <<"MSG_PLAYER_PING">>; %% high 1, id 50
to_s(?MSG_PLAYER_RECONNECTION) -> <<"MSG_PLAYER_RECONNECTION">>; %% high 1, id 51
to_s(?MSG_PlAYER_RIDE) -> <<"MSG_PlAYER_RIDE">>; %% high 1, id 52
to_s(?MSG_PLAYER_ACTIVITY_LIST) -> <<"MSG_PLAYER_ACTIVITY_LIST">>; %% high 1, id 53
to_s(?MSG_PLAYER_UNDRESS_SHAPESHIFT) -> <<"MSG_PLAYER_UNDRESS_SHAPESHIFT">>; %% high 1, id 54
to_s(?MSG_PLAYER_DO_SURVEY_NOTIFY) -> <<"MSG_PLAYER_DO_SURVEY_NOTIFY">>; %% high 1, id 55
to_s(?MSG_PLAYER_SP_REFRESH_TIME) -> <<"MSG_PLAYER_SP_REFRESH_TIME">>; %% high 1, id 56
to_s(?MSG_PLAYER_CD_KEY) -> <<"MSG_PLAYER_CD_KEY">>; %% high 1, id 57
to_s(?MSG_PLAYER_ADD_HOURLY_SP) -> <<"MSG_PLAYER_ADD_HOURLY_SP">>; %% high 1, id 58
to_s(?MSG_PLAYER_PUSH_HOURLY_SP_STATUS) -> <<"MSG_PLAYER_PUSH_HOURLY_SP_STATUS">>; %% high 1, id 59
to_s(?MSG_PLAYER_RESET_PLAYER_NAME) -> <<"MSG_PLAYER_RESET_PLAYER_NAME">>; %% high 1, id 60
to_s(?MSG_PLAYER_PROGRESS_NOTICE) -> <<"MSG_PLAYER_PROGRESS_NOTICE">>; %% high 1, id 61
to_s(?MSG_PLAYER_PUSH_SHARE_GAME) -> <<"MSG_PLAYER_PUSH_SHARE_GAME">>; %% high 1, id 62
to_s(?MSG_PLAYER_GET_SHARE_GAME_PRIZE) -> <<"MSG_PLAYER_GET_SHARE_GAME_PRIZE">>; %% high 1, id 63
to_s(_) -> <<"unknown msg">>.
unpkg_list_struct__(0, Bin, List, _Fn) -> {lists:reverse(List), Bin};
unpkg_list_struct__(L, Bin, List, Fn) -> {E, Bin1} = Fn(Bin), unpkg_list_struct__(L-1, Bin1, [E|List], Fn).
unpkg_list_u32(0, Bin, List) -> {lists:reverse(List), Bin};
unpkg_list_u32(Len, Bin, List) -> 
 <<E:32,Bin1/binary>> = Bin,
unpkg_list_u32(Len-1, Bin1, [E|List]).
unpkg_list_u16(0, Bin, List) -> {lists:reverse(List), Bin};
unpkg_list_u16(Len, Bin, List) -> 
 <<E:16,Bin1/binary>> = Bin,
unpkg_list_u16(Len-1, Bin1, [E|List]).
