%%%% Auto generated by gen_proto
%%%% Don't edit it


-module(robot_proto_info).
-export([to_s/1]).

-include("src/auto/robot_proto/robot_all_mods.inl").
to_s(CmdId) ->
    ModId = CmdId bsr 8,
    case get_proto_mod(ModId) of
        nil -> <<"unknonw cmdID">>;
        {_Mod, SprotoMod} ->
             SprotoMod:to_s(CmdId)
    end.
