%%%% Auto generated by gen_proto
%%%% Don't edit it.

-ifndef(GPROTO_INC_).
-define(GPROTO_INC_,1).

-define(ROBOT_PLAYER, 1).
-define(ROBOT_PLAYER, 3).
-define(NIL, 99).

-include("robot_player_sproto.hrl").
-include("robot_item_sproto.hrl").
-include("robot_debug_sproto.hrl").

-define(all_player_mods(), [robot_player, robot_player, nil]).
-define(all_player_eng_mods(), []).
-endif.
