%% Auto generated by sproto from robot_debug.sproto
%% Don't edit it.

-module(robot_debug_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("robot_debug_sproto.hrl").
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_DEBUG_SKILL_HIT_AREA, Acc0) ->
<<Idx:16/signed,
L__ps:16, Acc1/binary>> = Acc0,
{Ps, Acc2} = unpkg_list_struct__(L__ps, Acc1, [], fun unpkg_ano_s__0/1)
,
{{Idx,Ps}, Acc2};

%% id = 2  
unpkg_msg(?MSG_DEBUG_MOVE, Acc0) ->
<<Idx:16/signed,
X:16,
Y:16,
H:16,
Acc1/binary>> = Acc0,
 {{Idx,X,Y,H}, Acc1};

%% id = 3  
unpkg_msg(?MSG_DEBUG_ERROR_MSG, Acc0) ->
<<Msg/binary>> = Acc0,
 {{Msg}, <<>>};
unpkg_msg(Id, _) -> ok.


unpkg_ano_s__0(Acc0) ->
<<X:16/signed,
Y:16/signed,
Acc1/binary>> = Acc0,
 {{X,Y}, Acc1}.


to_s(?MSG_DEBUG_SKILL_HIT_AREA) -> <<"MSG_DEBUG_SKILL_HIT_AREA">>; %% high 99, id 1
to_s(?MSG_DEBUG_MOVE) -> <<"MSG_DEBUG_MOVE">>; %% high 99, id 2
to_s(?MSG_DEBUG_ERROR_MSG) -> <<"MSG_DEBUG_ERROR_MSG">>; %% high 99, id 3
to_s(_) -> <<"unknown msg">>.
unpkg_list_struct__(0, Bin, List, _Fn) -> {lists:reverse(List), Bin};
unpkg_list_struct__(L, Bin, List, Fn) -> {E, Bin1} = Fn(Bin), unpkg_list_struct__(L-1, Bin1, [E|List], Fn).
