%% Auto generated by sproto from abyss.sproto
%% Don't edit it.

-define(GET_SELECT_ABYSS_INFO, 7179). %% hight:28 id11
-define(MSG_ABYSS_AUTO_FIGHT, 7189). %% hight:28 id21
-define(MSG_ABYSS_RESET_COUNT, 7190). %% hight:28 id22
-define(MSG_ABYSS_FIGHT, 7191). %% hight:28 id23
-define(PUSH_ABYSS_PRIZE, 7192). %% hight:28 id24
-define(MSG_ABYSS_COMPLETE, 7194). %% hight:28 id26
-define(MSG_ABYSS_NEW_AUTO_FIGHT, 7195). %% hight:28 id27
-define(MSG_ABYSS_BUY_FIGHT_COUNT, 7196). %% hight:28 id28
-define(MSG_ABYSS_BUY_RESET_COUNT, 7197). %% hight:28 id29
