%% Auto generated by sproto from abyss.sproto
%% Don't edit it.

-module(abyss_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("abyss_sproto.hrl").

%% id=11  
pkg_msg(?GET_SELECT_ABYSS_INFO, {Max_layer1, Max_layer2, Layer1, Layer2, Auto_layer1, Auto_layer2, Fight_count, Buy_fight_count, Fight_reset, Buy_fight_reset, Score, Hard_score, RankIndex}) ->
<<?GET_SELECT_ABYSS_INFO:16, 
Max_layer1:16,
    Max_layer2:16,
    Layer1:16,
    Layer2:16,
    Auto_layer1:16,
    Auto_layer2:16,
    Fight_count,
    Buy_fight_count,
    Fight_reset,
    Buy_fight_reset,
    Score:32,
    Hard_score:32,
    RankIndex:16>>
;

%% id=21  
pkg_msg(?MSG_ABYSS_AUTO_FIGHT, {Score, Prize}) ->
<<?MSG_ABYSS_AUTO_FIGHT:16, 
Score:32,
    (length(Prize)):16, (iolist_to_binary([<<
Item_bid:32,
    Item_count:32>>
|| {Item_bid, Item_count} <- Prize]))/binary >>
;

%% id=22  
pkg_msg(?MSG_ABYSS_RESET_COUNT, {State}) ->
<<?MSG_ABYSS_RESET_COUNT:16, 
State>>
;

%% id=23  
pkg_msg(?MSG_ABYSS_FIGHT, {}) ->
<<?MSG_ABYSS_FIGHT:16>> 
;

%% id=24  
pkg_msg(?PUSH_ABYSS_PRIZE, {Instance_id, Percent, PrizeInfo}) ->
<<?PUSH_ABYSS_PRIZE:16, 
Instance_id:32,
    Percent,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=26  
pkg_msg(?MSG_ABYSS_COMPLETE, {Basescore, Vipscore, Totalscore, PrizeInfo}) ->
<<?MSG_ABYSS_COMPLETE:16, 
Basescore:32,
    Vipscore:32,
    Totalscore:32,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=27  
pkg_msg(?MSG_ABYSS_NEW_AUTO_FIGHT, {Clean_info}) ->
<<?MSG_ABYSS_NEW_AUTO_FIGHT:16, 
(length(Clean_info)):16, (iolist_to_binary([<<
Layer:16,
    Score:32,
    (length(Prize)):16, (iolist_to_binary([<<
Item_bid:32,
    Item_count:32>>
|| {Item_bid, Item_count} <- Prize]))/binary >>
|| {Layer, Score, Prize} <- Clean_info]))/binary >>
;

%% id=28  
pkg_msg(?MSG_ABYSS_BUY_FIGHT_COUNT, {ReplyNum}) ->
<<?MSG_ABYSS_BUY_FIGHT_COUNT:16, 
ReplyNum>>
;

%% id=29  
pkg_msg(?MSG_ABYSS_BUY_RESET_COUNT, {ReplyNum}) ->
<<?MSG_ABYSS_BUY_RESET_COUNT:16, 
ReplyNum>>
;
pkg_msg(Id, _) -> ok.



%% id = 11  
unpkg_msg(?GET_SELECT_ABYSS_INFO, Acc0) ->
{{}, Acc0};

%% id = 21  
unpkg_msg(?MSG_ABYSS_AUTO_FIGHT, Acc0) ->
<<Diff,
Acc1/binary>> = Acc0,
 {{Diff}, Acc1};

%% id = 22  
unpkg_msg(?MSG_ABYSS_RESET_COUNT, Acc0) ->
<<Diff,
Acc1/binary>> = Acc0,
 {{Diff}, Acc1};

%% id = 23  
unpkg_msg(?MSG_ABYSS_FIGHT, Acc0) ->
<<Diff,
Acc1/binary>> = Acc0,
 {{Diff}, Acc1};

%% id = 27  
unpkg_msg(?MSG_ABYSS_NEW_AUTO_FIGHT, Acc0) ->
<<Diff,
Acc1/binary>> = Acc0,
 {{Diff}, Acc1};

%% id = 28  
unpkg_msg(?MSG_ABYSS_BUY_FIGHT_COUNT, Acc0) ->
<<Count,
Acc1/binary>> = Acc0,
 {{Count}, Acc1};

%% id = 29  
unpkg_msg(?MSG_ABYSS_BUY_RESET_COUNT, Acc0) ->
<<Count,
Acc1/binary>> = Acc0,
 {{Count}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?GET_SELECT_ABYSS_INFO) -> <<"GET_SELECT_ABYSS_INFO">>; %% high 28, id 11
to_s(?MSG_ABYSS_AUTO_FIGHT) -> <<"MSG_ABYSS_AUTO_FIGHT">>; %% high 28, id 21
to_s(?MSG_ABYSS_RESET_COUNT) -> <<"MSG_ABYSS_RESET_COUNT">>; %% high 28, id 22
to_s(?MSG_ABYSS_FIGHT) -> <<"MSG_ABYSS_FIGHT">>; %% high 28, id 23
to_s(?PUSH_ABYSS_PRIZE) -> <<"PUSH_ABYSS_PRIZE">>; %% high 28, id 24
to_s(?MSG_ABYSS_COMPLETE) -> <<"MSG_ABYSS_COMPLETE">>; %% high 28, id 26
to_s(?MSG_ABYSS_NEW_AUTO_FIGHT) -> <<"MSG_ABYSS_NEW_AUTO_FIGHT">>; %% high 28, id 27
to_s(?MSG_ABYSS_BUY_FIGHT_COUNT) -> <<"MSG_ABYSS_BUY_FIGHT_COUNT">>; %% high 28, id 28
to_s(?MSG_ABYSS_BUY_RESET_COUNT) -> <<"MSG_ABYSS_BUY_RESET_COUNT">>; %% high 28, id 29
to_s(_) -> <<"unknown msg">>.
