%% Auto generated by sproto from accomplishments.sproto
%% Don't edit it.

-define(MSG_ACCOMPLISHMENT_LIST, 4353). %% hight:17 id1
-define(MSG_ACCOMPLISHMENT_EXTRACT_REWARD, 4354). %% hight:17 id2
-define(MSG_ACCOMPLISHMENTS_ACHIEVEMENT_CHANGE, 4355). %% hight:17 id3
