%% Auto generated by sproto from alchemy.sproto
%% Don't edit it.

-module(alchemy_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("alchemy_sproto.hrl").

%% id=1  
pkg_msg(?MSG_ALCHEMY_INIT_DATA, {Count}) ->
<<?MSG_ALCHEMY_INIT_DATA:16, 
Count>>
;

%% id=2  
pkg_msg(?MSG_ALCHEMY_ROCK, {Count}) ->
<<?MSG_ALCHEMY_ROCK:16, 
Count>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_ALCHEMY_ROCK, Acc0) ->
<<Buy_count,
Acc1/binary>> = Acc0,
 {{Buy_count}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_ALCHEMY_INIT_DATA) -> <<"MSG_ALCHEMY_INIT_DATA">>; %% high 37, id 1
to_s(?MSG_ALCHEMY_ROCK) -> <<"MSG_ALCHEMY_ROCK">>; %% high 37, id 2
to_s(_) -> <<"unknown msg">>.
