%% Auto generated by sproto from arena.sproto
%% Don't edit it.

-define(MSG_ARENA_MATCH, 5121). %% hight:20 id1
-define(MSG_ARENA_PANEL, 5122). %% hight:20 id2
-define(MSG_ARENA_RANK, 5125). %% hight:20 id5
-define(MSG_ARENA_COUNT, 5126). %% hight:20 id6
-define(MSG_ARENA_RESULT, 5127). %% hight:20 id7
-define(MSG_ARENA_MULTI_RESULT, 5129). %% hight:20 id9
-define(MSG_ARENA_CANEL_MATCH, 5128). %% hight:20 id8
-define(MSG_ARENA_PLAYER_INFO_CSC, 5221). %% hight:20 id101
-define(MSG_ARENA_SORE_PLAYERS_CSC, 5222). %% hight:20 id102
-define(MSG_ARENA_CHALLENGE_PLAYER_CSC, 5223). %% hight:20 id103
-define(MSG_ARENA_COMPLETE_CHALLENGE_SC, 5224). %% hight:20 id104
-define(MSG_ARENA_GET_CHALLENGE_PRIZE_CS, 5225). %% hight:20 id105
-define(MSG_ARENA_GET_CHALLENGE_LOG_CSC, 5226). %% hight:20 id106
-define(MSG_ARENA_BUY_CHALLENGE_COUNT_CSC, 5227). %% hight:20 id107
-define(MSG_ARENA_DUEL, 5241). %% hight:20 id121
-define(MSG_ARENA_RECEIVE_DUEL, 5242). %% hight:20 id122
-define(MSG_ARENA_DUEL_RET, 5243). %% hight:20 id123
-define(MSG_ARENA_P2E_RANK, 5240). %% hight:20 id120
-define(MSG_ARENA_DUEL_CLEARING, 5244). %% hight:20 id124
-define(MSG_ARENA_SHOP_BUY, 5245). %% hight:20 id125
-define(MSG_ARENA_P2E_PRIZE_NOTIFY, 5246). %% hight:20 id126
-define(MSG_ARENA_PUSH_PLAYER_INFO, 5247). %% hight:20 id127
