%% Auto generated by sproto from auction.sproto
%% Don't edit it.

-define(MSG_AUCTION_PANEL, 2049). %% hight:8 id1
-define(MSG_AUCTION_PRICE, 2050). %% hight:8 id2
-define(MSG_AUCTION_REFRESH, 2051). %% hight:8 id3
-define(MSG_OPEN_AUCTION_PANEL, 2052). %% hight:8 id4
-define(MSG_AUCTION_LOG_REFRESH, 2053). %% hight:8 id5
