%% Auto generated by sproto from auction.sproto
%% Don't edit it.

-module(auction_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("auction_sproto.hrl").

%% id=1  
pkg_msg(?MSG_AUCTION_PANEL, {Ret, TimeOut, AuctionInfoL}) ->
<<?MSG_AUCTION_PANEL:16, 
Ret,
    TimeOut:64,
    (length(AuctionInfoL)):16, (iolist_to_binary([<<
ItemState,
    AuctionId:32,
    (byte_size(OwnName)), OwnName/binary,
    Item:32,
    ItemNum,
    MoneyType,
    CurPrice:32,
    AddCount:32,
    HighPrice:32,
    BidPlayerId:64,
    (byte_size(BidPlayerName)), BidPlayerName/binary>>
|| {ItemState, AuctionId, OwnName, Item, ItemNum, MoneyType, CurPrice, AddCount, HighPrice, BidPlayerId, BidPlayerName} <- AuctionInfoL]))/binary >>
;

%% id=2  
pkg_msg(?MSG_AUCTION_PRICE, {ReplyNum, AuctionId}) ->
<<?MSG_AUCTION_PRICE:16, 
ReplyNum,
    AuctionId:32>>
;

%% id=3  
pkg_msg(?MSG_AUCTION_REFRESH, {AuctionInfoL}) ->
<<?MSG_AUCTION_REFRESH:16, 
(length(AuctionInfoL)):16, (iolist_to_binary([<<
ItemState,
    AuctionId:32,
    CurPrice:32,
    BidPlayerId:64,
    (byte_size(BidPlayerName)), BidPlayerName/binary>>
|| {ItemState, AuctionId, CurPrice, BidPlayerId, BidPlayerName} <- AuctionInfoL]))/binary >>
;

%% id=4  
pkg_msg(?MSG_OPEN_AUCTION_PANEL, {ReplyNum}) ->
<<?MSG_OPEN_AUCTION_PANEL:16, 
ReplyNum>>
;

%% id=5  
pkg_msg(?MSG_AUCTION_LOG_REFRESH, {LogL}) ->
<<?MSG_AUCTION_LOG_REFRESH:16, 
(length(LogL)):16, (iolist_to_binary([<<
PlayerId:64,
    (byte_size(Name)), Name/binary,
    ItemId:32,
    Money_type,
    Price:32,
    Datetime:32,
    AuctionType>>
|| {PlayerId, Name, ItemId, Money_type, Price, Datetime, AuctionType} <- LogL]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_AUCTION_PANEL, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_AUCTION_PRICE, Acc0) ->
<<AuctionId:32,
Price:32,
Acc1/binary>> = Acc0,
 {{AuctionId,Price}, Acc1};

%% id = 3  
unpkg_msg(?MSG_AUCTION_REFRESH, Acc0) ->
{{}, Acc0};

%% id = 4  
unpkg_msg(?MSG_OPEN_AUCTION_PANEL, Acc0) ->
{{}, Acc0};

%% id = 5  
unpkg_msg(?MSG_AUCTION_LOG_REFRESH, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_AUCTION_PANEL) -> <<"MSG_AUCTION_PANEL">>; %% high 8, id 1
to_s(?MSG_AUCTION_PRICE) -> <<"MSG_AUCTION_PRICE">>; %% high 8, id 2
to_s(?MSG_AUCTION_REFRESH) -> <<"MSG_AUCTION_REFRESH">>; %% high 8, id 3
to_s(?MSG_OPEN_AUCTION_PANEL) -> <<"MSG_OPEN_AUCTION_PANEL">>; %% high 8, id 4
to_s(?MSG_AUCTION_LOG_REFRESH) -> <<"MSG_AUCTION_LOG_REFRESH">>; %% high 8, id 5
to_s(_) -> <<"unknown msg">>.
