%% Auto generated by sproto from bounty.sproto
%% Don't edit it.

-define(MSG_BOUNTY_TASK_LIST, 12033). %% hight:47 id1
-define(MSG_BOUNTY_PUSH_LIVENESS_PRIZE_LIST, 12034). %% hight:47 id2
-define(MSG_BOUNTY_COMPLETE, 12035). %% hight:47 id3
-define(MSG_BOUNTY_LIVENESS_GET_PRIZE, 12036). %% hight:47 id4
