%% Auto generated by sproto from camp.sproto
%% Don't edit it.

-define(MSG_ENEMY_PLAYERS_DATA, 6913). %% hight:27 id1
-define(PUSH_ENEMY_PLAYER_DATA, 6914). %% hight:27 id2
-define(PUSH_TIME_TICK, 6915). %% hight:27 id3
-define(PUSH_CAMP_PRIZE, 6916). %% hight:27 id4
-define(PUSH_CAMP_ID, 6917). %% hight:27 id5
-define(GET_CAMP_PLAYER_DATA, 6923). %% hight:27 id11
-define(GET_CAMP_DATA, 6924). %% hight:27 id12
-define(GET_ENEMY_LIST, 6925). %% hight:27 id13
-define(GET_RANKING_LIST, 6926). %% hight:27 id14
-define(GET_EVENT_LIST, 6927). %% hight:27 id15
-define(MSG_SELECT_CAMP, 6933). %% hight:27 id21
-define(MSG_HUMAN_SELECT_CAMP, 6934). %% hight:27 id22
-define(MSG_PLAYER_ENTER_INSTANCE, 6935). %% hight:27 id23
-define(MSG_PLAYER_ENTER_ENEMY_INSTANCE, 6936). %% hight:27 id24
-define(MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER, 6937). %% hight:27 id25
