%% Auto generated by sproto from camp.sproto
%% Don't edit it.

-module(camp_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("camp_sproto.hrl").

%% id=1  
pkg_msg(?MSG_ENEMY_PLAYERS_DATA, {Player_list}) ->
<<?MSG_ENEMY_PLAYERS_DATA:16, 
(length(Player_list)):16, (iolist_to_binary([<<
Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_power:32,
    Camp_id,
    Exploit:32,
    Instance_id:32>>
|| {Player_id, Player_name, Player_power, Camp_id, Exploit, Instance_id} <- Player_list]))/binary >>
;

%% id=2  
pkg_msg(?PUSH_ENEMY_PLAYER_DATA, {Player_id, Player_name, Player_power, Camp_id, Exploit, Instance_id}) ->
<<?PUSH_ENEMY_PLAYER_DATA:16, 
Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_power:32,
    Camp_id,
    Exploit:32,
    Instance_id:32>>
;

%% id=3  
pkg_msg(?PUSH_TIME_TICK, {}) ->
<<?PUSH_TIME_TICK:16>> 
;

%% id=4  
pkg_msg(?PUSH_CAMP_PRIZE, {Instance_id, PrizeInfo}) ->
<<?PUSH_CAMP_PRIZE:16, 
Instance_id:32,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=5  
pkg_msg(?PUSH_CAMP_ID, {Camp_id}) ->
<<?PUSH_CAMP_ID:16, 
Camp_id>>
;

%% id=11  
pkg_msg(?GET_CAMP_PLAYER_DATA, {Self_camp, Self_enter_count, Enemy_enter_count, Exploit, Camp_value_level, Camp_value, Player_career, God_instance, Magic_instance, Refresh_time}) ->
<<?GET_CAMP_PLAYER_DATA:16, 
Self_camp,
    Self_enter_count,
    Enemy_enter_count,
    Exploit:32,
    Camp_value_level,
    Camp_value:32,
    Player_career,
    (length(God_instance)):16, (iolist_to_binary([<<
Instance_id:32,
    State>>
|| {Instance_id, State} <- God_instance]))/binary ,
    (length(Magic_instance)):16, (iolist_to_binary([<<
Instance_id:32,
    State>>
|| {Instance_id, State} <- Magic_instance]))/binary ,
    (length(Refresh_time)):16, (iolist_to_binary([<<
Hour,
    Minute,
    Second>>
|| {Hour, Minute, Second} <- Refresh_time]))/binary >>
;

%% id=12  
pkg_msg(?GET_CAMP_DATA, {Camp_type, Camp_timestamp, God_camp_point, Magic_camp_point, Instance_state}) ->
<<?GET_CAMP_DATA:16, 
Camp_type,
    Camp_timestamp:32,
    God_camp_point:32,
    Magic_camp_point:32,
    (length(Instance_state)):16, (iolist_to_binary([<<
Instance_id:32,
    State>>
|| {Instance_id, State} <- Instance_state]))/binary >>
;

%% id=13  
pkg_msg(?GET_ENEMY_LIST, {Role}) ->
<<?GET_ENEMY_LIST:16, 
(length(Role)):16, (iolist_to_binary([<<
Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_level,
    Player_power:32,
    Player_carrer>>
|| {Player_id, Player_name, Player_level, Player_power, Player_carrer} <- Role]))/binary >>
;

%% id=14  
pkg_msg(?GET_RANKING_LIST, {Myindex, Player_id, Player_name, Player_level, Self_camp, Exploit, Player_career, Size, Role}) ->
<<?GET_RANKING_LIST:16, 
Myindex,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_level,
    Self_camp,
    Exploit:32,
    Player_career,
    Size,
    (length(Role)):16, (iolist_to_binary([<<
Rank_id,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_level,
    Self_camp,
    Exploit:32,
    Player_career>>
|| {Rank_id, Player_id, Player_name, Player_level, Self_camp, Exploit, Player_career} <- Role]))/binary >>
;

%% id=15  
pkg_msg(?GET_EVENT_LIST, {God_camp_point, Magic_camp_point, Player_money, Player_diamond, Size, Role}) ->
<<?GET_EVENT_LIST:16, 
God_camp_point:32,
    Magic_camp_point:32,
    Player_money:32,
    Player_diamond:32,
    Size,
    (length(Role)):16, (iolist_to_binary([<<
Event_type,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Camp_id,
    Instance_id:32,
    Camp_point:32,
    To_player_id:64,
    (byte_size(To_player_name)), To_player_name/binary>>
|| {Event_type, Player_id, Player_name, Camp_id, Instance_id, Camp_point, To_player_id, To_player_name} <- Role]))/binary >>
;

%% id=21  
pkg_msg(?MSG_SELECT_CAMP, {}) ->
<<?MSG_SELECT_CAMP:16>> 
;

%% id=22  
pkg_msg(?MSG_HUMAN_SELECT_CAMP, {}) ->
<<?MSG_HUMAN_SELECT_CAMP:16>> 
;

%% id=23  
pkg_msg(?MSG_PLAYER_ENTER_INSTANCE, {}) ->
<<?MSG_PLAYER_ENTER_INSTANCE:16>> 
;

%% id=24  
pkg_msg(?MSG_PLAYER_ENTER_ENEMY_INSTANCE, {}) ->
<<?MSG_PLAYER_ENTER_ENEMY_INSTANCE:16>> 
;

%% id=25  
pkg_msg(?MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER, {}) ->
<<?MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER:16>> 
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_ENEMY_PLAYERS_DATA, Acc0) ->
<<Instance_id:32,
Event,
Acc1/binary>> = Acc0,
 {{Instance_id,Event}, Acc1};

%% id = 11  
unpkg_msg(?GET_CAMP_PLAYER_DATA, Acc0) ->
{{}, Acc0};

%% id = 12  
unpkg_msg(?GET_CAMP_DATA, Acc0) ->
{{}, Acc0};

%% id = 13  
unpkg_msg(?GET_ENEMY_LIST, Acc0) ->
<<Instance_id:32,
Acc1/binary>> = Acc0,
 {{Instance_id}, Acc1};

%% id = 14  
unpkg_msg(?GET_RANKING_LIST, Acc0) ->
<<Ranking_type,
Start_pos,
Num,
Acc1/binary>> = Acc0,
 {{Ranking_type,Start_pos,Num}, Acc1};

%% id = 15  
unpkg_msg(?GET_EVENT_LIST, Acc0) ->
<<Start_pos,
Num,
Acc1/binary>> = Acc0,
 {{Start_pos,Num}, Acc1};

%% id = 21  
unpkg_msg(?MSG_SELECT_CAMP, Acc0) ->
<<Camp_id,
Acc1/binary>> = Acc0,
 {{Camp_id}, Acc1};

%% id = 22  
unpkg_msg(?MSG_HUMAN_SELECT_CAMP, Acc0) ->
<<Camp_id,
Acc1/binary>> = Acc0,
 {{Camp_id}, Acc1};

%% id = 23  
unpkg_msg(?MSG_PLAYER_ENTER_INSTANCE, Acc0) ->
<<Instance_id:32,
Acc1/binary>> = Acc0,
 {{Instance_id}, Acc1};

%% id = 24  
unpkg_msg(?MSG_PLAYER_ENTER_ENEMY_INSTANCE, Acc0) ->
<<Instance_id:32,
Acc1/binary>> = Acc0,
 {{Instance_id}, Acc1};

%% id = 25  
unpkg_msg(?MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER, Acc0) ->
<<Instance_id:32,
Enemy_player_id:64,
Acc1/binary>> = Acc0,
 {{Instance_id,Enemy_player_id}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_ENEMY_PLAYERS_DATA) -> <<"MSG_ENEMY_PLAYERS_DATA">>; %% high 27, id 1
to_s(?PUSH_ENEMY_PLAYER_DATA) -> <<"PUSH_ENEMY_PLAYER_DATA">>; %% high 27, id 2
to_s(?PUSH_TIME_TICK) -> <<"PUSH_TIME_TICK">>; %% high 27, id 3
to_s(?PUSH_CAMP_PRIZE) -> <<"PUSH_CAMP_PRIZE">>; %% high 27, id 4
to_s(?PUSH_CAMP_ID) -> <<"PUSH_CAMP_ID">>; %% high 27, id 5
to_s(?GET_CAMP_PLAYER_DATA) -> <<"GET_CAMP_PLAYER_DATA">>; %% high 27, id 11
to_s(?GET_CAMP_DATA) -> <<"GET_CAMP_DATA">>; %% high 27, id 12
to_s(?GET_ENEMY_LIST) -> <<"GET_ENEMY_LIST">>; %% high 27, id 13
to_s(?GET_RANKING_LIST) -> <<"GET_RANKING_LIST">>; %% high 27, id 14
to_s(?GET_EVENT_LIST) -> <<"GET_EVENT_LIST">>; %% high 27, id 15
to_s(?MSG_SELECT_CAMP) -> <<"MSG_SELECT_CAMP">>; %% high 27, id 21
to_s(?MSG_HUMAN_SELECT_CAMP) -> <<"MSG_HUMAN_SELECT_CAMP">>; %% high 27, id 22
to_s(?MSG_PLAYER_ENTER_INSTANCE) -> <<"MSG_PLAYER_ENTER_INSTANCE">>; %% high 27, id 23
to_s(?MSG_PLAYER_ENTER_ENEMY_INSTANCE) -> <<"MSG_PLAYER_ENTER_ENEMY_INSTANCE">>; %% high 27, id 24
to_s(?MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER) -> <<"MSG_PLAYER_ENTER_INSTANCE_FIGHT_ENEMY_PLAYER">>; %% high 27, id 25
to_s(_) -> <<"unknown msg">>.
