%% Auto generated by sproto from card_new.sproto
%% Don't edit it.

-module(card_new_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("card_new_sproto.hrl").

%% id=1  
pkg_msg(?MSG_CARD_NEW_INFO, {Card_list}) ->
<<?MSG_CARD_NEW_INFO:16, 
(length(Card_list)):16, (iolist_to_binary([<<
CardId,
    Use_times,
    Max_times>>
|| {CardId, Use_times, Max_times} <- Card_list]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_CARD_NEW_INFO, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_CARD_NEW_INFO) -> <<"MSG_CARD_NEW_INFO">>; %% high 54, id 1
to_s(_) -> <<"unknown msg">>.
