%% Auto generated by sproto from card.sproto
%% Don't edit it.

-define(MSG_CARD_AWARD, 5889). %% hight:23 id1
-define(MSG_CARD_AWARD_INFO, 5890). %% hight:23 id2
-define(MSG_CARD_BROADCAST_NOTICE, 5891). %% hight:23 id3
