%% Auto generated by sproto from chat.sproto
%% Don't edit it.

-define(MSG_CHAT_P2P, 3329). %% hight:13 id1
-define(MSG_CHAT_GROUP, 3330). %% hight:13 id2
-define(MSG_CHAT_SYSTEM, 3331). %% hight:13 id3
-define(MSG_CHAT_SYSTEM_EX, 3332). %% hight:13 id4
-define(MSG_CHAT_SYSTEM_B, 3333). %% hight:13 id5
-define(MSG_CHAT_SYSTEM_C, 3334). %% hight:13 id6
