%% Auto generated by sproto from course.sproto
%% Don't edit it.

-define(MSG_ENTER_COURSE, 9729). %% hight:38 id1
-define(MSG_COURSE_PRIZE, 9730). %% hight:38 id2
-define(MSG_COURSE_BEST_PRIZE, 9731). %% hight:38 id3
-define(MSG_COURSE_BUY_COUNT, 9732). %% hight:38 id4
-define(MSG_COURSE_CHALLENGE_BOSS_ENTER, 9733). %% hight:38 id5
-define(MSG_COURSE_CHALLENGE_BOSS_PRIZE_INFO, 9734). %% hight:38 id6
-define(MSG_COURSE_USE_COUNT, 9735). %% hight:38 id7
-define(MSG_COURSE_FLUSH_BOSS_INFO, 9736). %% hight:38 id8
-define(MSG_COURSE_FIGHT_DATA_OF_NOT_BOSS, 9737). %% hight:38 id9
