%% Auto generated by sproto from crown_new.sproto
%% Don't edit it.

-define(MSG_CROWN_NEW_INIT_CLIENT, 11521). %% hight:45 id1
-define(MSG_CROWN_SKILL_ACTIVATE, 11522). %% hight:45 id2
-define(MSG_CROWN_SKILL_LEVELUP, 11523). %% hight:45 id3
-define(MSG_CROWN_DRESS_SKILL, 11524). %% hight:45 id4
-define(MSG_CROWN_UNDRESS_SKILL, 11525). %% hight:45 id5
-define(MSG_CROWN_DRESS_CROWN_STAR, 11526). %% hight:45 id6
-define(MSG_CROWN_UNDRESS_CROWN_STAR, 11527). %% hight:45 id7
-define(MSG_CROWN_NEW_ANGER_CHANGE, 11528). %% hight:45 id8
-define(MSG_CROWN_SKILL_ADD_ATTR, 11529). %% hight:45 id9
