%% Auto generated by sproto from crown_new.sproto
%% Don't edit it.

-module(crown_new_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("crown_new_sproto.hrl").

%% id=1  
pkg_msg(?MSG_CROWN_NEW_INIT_CLIENT, {Anger, SkillList, IsUseSkill}) ->
<<?MSG_CROWN_NEW_INIT_CLIENT:16, 
Anger:16,
    (length(SkillList)):16, (iolist_to_binary([<<
SkillId:32,
    SkillLvl>>
|| {SkillId, SkillLvl} <- SkillList]))/binary ,
    (length(IsUseSkill)):16, (iolist_to_binary([<<UseSkill:32>> || UseSkill <- IsUseSkill]))/binary>>
;

%% id=2  
pkg_msg(?MSG_CROWN_SKILL_ACTIVATE, {ReturnRet, SkillId}) ->
<<?MSG_CROWN_SKILL_ACTIVATE:16, 
ReturnRet,
    SkillId:32>>
;

%% id=3  
pkg_msg(?MSG_CROWN_SKILL_LEVELUP, {ReturnRet, SkillInfo}) ->
<<?MSG_CROWN_SKILL_LEVELUP:16, 
ReturnRet,
    (begin {SkillId, SkillLvl}=SkillInfo, <<
SkillId:32,
    SkillLvl>>
 end)/binary>>
;

%% id=4  
pkg_msg(?MSG_CROWN_DRESS_SKILL, {ReturnRet, SkillId}) ->
<<?MSG_CROWN_DRESS_SKILL:16, 
ReturnRet,
    SkillId:32>>
;

%% id=5  
pkg_msg(?MSG_CROWN_UNDRESS_SKILL, {ReturnRet}) ->
<<?MSG_CROWN_UNDRESS_SKILL:16, 
ReturnRet>>
;

%% id=6  
pkg_msg(?MSG_CROWN_DRESS_CROWN_STAR, {ReturnRet, SkillId}) ->
<<?MSG_CROWN_DRESS_CROWN_STAR:16, 
ReturnRet,
    SkillId:32>>
;

%% id=7  
pkg_msg(?MSG_CROWN_UNDRESS_CROWN_STAR, {ReturnRet}) ->
<<?MSG_CROWN_UNDRESS_CROWN_STAR:16, 
ReturnRet>>
;

%% id=8  
pkg_msg(?MSG_CROWN_NEW_ANGER_CHANGE, {Anger_point}) ->
<<?MSG_CROWN_NEW_ANGER_CHANGE:16, 
Anger_point:16>>
;

%% id=9  
pkg_msg(?MSG_CROWN_SKILL_ADD_ATTR, {Attr}) ->
<<?MSG_CROWN_SKILL_ADD_ATTR:16, 
(begin {AttId, AttHp, AttMp, AttSp, AttNp, AttStrength, AttIntellect, AttNimble, AttStrong, AttAtk, AttDef, AttCrit, AttBlock, AttPliable, AttPure_atk, AttBreak_def, AttAtk_deep, AttAtk_free, AttAtk_speed, AttPrecise, AttThunder_atk, AttThunder_def, AttFire_atk, AttFire_def, AttIce_atk, AttIce_def, AttMove_speed, AttRun_speed, AttSuckBlood, AttReverse, AttBati}=Attr, <<
AttId,
    AttHp:32,
    AttMp:32,
    AttSp:32,
    AttNp:32,
    AttStrength:32,
    AttIntellect:32,
    AttNimble:32,
    AttStrong:32,
    AttAtk:32,
    AttDef:32,
    AttCrit:32,
    AttBlock:32,
    AttPliable:32,
    AttPure_atk:32,
    AttBreak_def:32,
    AttAtk_deep:32,
    AttAtk_free:32,
    AttAtk_speed:32,
    AttPrecise:32,
    AttThunder_atk:32,
    AttThunder_def:32,
    AttFire_atk:32,
    AttFire_def:32,
    AttIce_atk:32,
    AttIce_def:32,
    AttMove_speed:32,
    AttRun_speed:32,
    AttSuckBlood:32,
    AttReverse:32,
    AttBati:32>>
 end)/binary>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_CROWN_SKILL_ACTIVATE, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 3  
unpkg_msg(?MSG_CROWN_SKILL_LEVELUP, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 4  
unpkg_msg(?MSG_CROWN_DRESS_SKILL, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 5  
unpkg_msg(?MSG_CROWN_UNDRESS_SKILL, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 6  
unpkg_msg(?MSG_CROWN_DRESS_CROWN_STAR, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 7  
unpkg_msg(?MSG_CROWN_UNDRESS_CROWN_STAR, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 9  
unpkg_msg(?MSG_CROWN_SKILL_ADD_ATTR, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_CROWN_NEW_INIT_CLIENT) -> <<"MSG_CROWN_NEW_INIT_CLIENT">>; %% high 45, id 1
to_s(?MSG_CROWN_SKILL_ACTIVATE) -> <<"MSG_CROWN_SKILL_ACTIVATE">>; %% high 45, id 2
to_s(?MSG_CROWN_SKILL_LEVELUP) -> <<"MSG_CROWN_SKILL_LEVELUP">>; %% high 45, id 3
to_s(?MSG_CROWN_DRESS_SKILL) -> <<"MSG_CROWN_DRESS_SKILL">>; %% high 45, id 4
to_s(?MSG_CROWN_UNDRESS_SKILL) -> <<"MSG_CROWN_UNDRESS_SKILL">>; %% high 45, id 5
to_s(?MSG_CROWN_DRESS_CROWN_STAR) -> <<"MSG_CROWN_DRESS_CROWN_STAR">>; %% high 45, id 6
to_s(?MSG_CROWN_UNDRESS_CROWN_STAR) -> <<"MSG_CROWN_UNDRESS_CROWN_STAR">>; %% high 45, id 7
to_s(?MSG_CROWN_NEW_ANGER_CHANGE) -> <<"MSG_CROWN_NEW_ANGER_CHANGE">>; %% high 45, id 8
to_s(?MSG_CROWN_SKILL_ADD_ATTR) -> <<"MSG_CROWN_SKILL_ADD_ATTR">>; %% high 45, id 9
to_s(_) -> <<"unknown msg">>.
