%% Auto generated by sproto from crown.sproto
%% Don't edit it.

-define(MSG_CROWN_INIT_CLIENT, 3850). %% hight:15 id10
-define(MSG_CROWN_GEM_ADD, 3848). %% hight:15 id8
-define(MSG_CROWN_GEM_SELL, 3841). %% hight:15 id1
-define(MSG_CROWN_GEM_ENCHANT, 3842). %% hight:15 id2
-define(MSG_CROWN_GEM_UPGRADE, 3843). %% hight:15 id3
-define(MSG_CROWN_GEM_DRESS, 3844). %% hight:15 id4
-define(MSG_CROWN_GEM_UNDRESS, 3845). %% hight:15 id5
-define(MSG_CROWN_ANGER_CHANGE, 3846). %% hight:15 id6
