%% Auto generated by sproto from daily_activity.sproto
%% Don't edit it.

-define(PUSH_DAILY_ACTIVITY_INFO, 7435). %% hight:29 id11
-define(MSG_SELECT_IDS, 7436). %% hight:29 id12
-define(MSG_ENTER_SCENE, 7437). %% hight:29 id13
-define(PUSH_PRIZE, 7438). %% hight:29 id14
-define(PUSH_BOSS_PRIZE, 7439). %% hight:29 id15
-define(PUSH_WAVE_PRIZE, 7440). %% hight:29 id16
-define(PUSH_POINT_PRIZE, 7441). %% hight:29 id17
-define(MSG_DAILY_ACTIVITY_SWEEP, 7442). %% hight:29 id18
-define(MSG_DAILY_ACTIVITY_BY_CHALLENGE_TIMES, 7443). %% hight:29 id19
-define(MSG_DAILY_ACTIVITY_GET_NEW_ACTIVITY_INFO, 7444). %% hight:29 id20
-define(MSG_DAILY_ACTIVITY_4_PUSH_POINT_PRIZE, 7445). %% hight:29 id21
-define(MSG_DAILY_ACTIVITY_5_PUSH_POINT_PRIZE, 7446). %% hight:29 id22
-define(MSG_DAILY_ACTIVITY_6_FISHING, 7447). %% hight:29 id23
-define(MSG_DAILY_ACTIVITY_6_BUY_FISHING_COUNT, 7448). %% hight:29 id24
-define(PUSH_MSG_FISHING_INFO, 7449). %% hight:29 id25
-define(PUSH_MSG_FISHING_OVER, 7450). %% hight:29 id26
