%% Auto generated by sproto from debug.sproto
%% Don't edit it.

-module(debug_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("debug_sproto.hrl").

%% id=1  
pkg_msg(?MSG_DEBUG_SKILL_HIT_AREA, {Idx, Ps}) ->
<<?MSG_DEBUG_SKILL_HIT_AREA:16, 
Idx:16/signed,
    (length(Ps)):16, (iolist_to_binary([<<
X:16/signed,
    Y:16/signed>>
|| {X, Y} <- Ps]))/binary >>
;

%% id=2  
pkg_msg(?MSG_DEBUG_MOVE, {Idx, X, Y, H}) ->
<<?MSG_DEBUG_MOVE:16, 
Idx:16/signed,
    X:16,
    Y:16,
    H:16>>
;

%% id=3  
pkg_msg(?MSG_DEBUG_ERROR_MSG, {Msg}) ->
<<?MSG_DEBUG_ERROR_MSG:16, 
Msg/binary>>
;
pkg_msg(Id, _) -> ok.


unpkg_msg(Id, _) -> ok.




to_s(?MSG_DEBUG_SKILL_HIT_AREA) -> <<"MSG_DEBUG_SKILL_HIT_AREA">>; %% high 99, id 1
to_s(?MSG_DEBUG_MOVE) -> <<"MSG_DEBUG_MOVE">>; %% high 99, id 2
to_s(?MSG_DEBUG_ERROR_MSG) -> <<"MSG_DEBUG_ERROR_MSG">>; %% high 99, id 3
to_s(_) -> <<"unknown msg">>.
