%% Auto generated by sproto from dig.sproto
%% Don't edit it.

-module(dig_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("dig_sproto.hrl").

%% id=1  
pkg_msg(?MSG_DIG_RES_CS, {Succ}) ->
<<?MSG_DIG_RES_CS:16, 
Succ>>
;

%% id=2  
pkg_msg(?MSG_USE_DIG_RES_CS, {Succ}) ->
<<?MSG_USE_DIG_RES_CS:16, 
Succ>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_DIG_RES_CS, Acc0) ->
<<Dig_type,
Uid:32,
Acc1/binary>> = Acc0,
 {{Dig_type,Uid}, Acc1};

%% id = 2  
unpkg_msg(?MSG_USE_DIG_RES_CS, Acc0) ->
<<ItemId:32,
Acc1/binary>> = Acc0,
 {{ItemId}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_DIG_RES_CS) -> <<"MSG_DIG_RES_CS">>; %% high 35, id 1
to_s(?MSG_USE_DIG_RES_CS) -> <<"MSG_USE_DIG_RES_CS">>; %% high 35, id 2
to_s(_) -> <<"unknown msg">>.
