%% Auto generated by sproto from equip.sproto
%% Don't edit it.

-define(MSG_EQUIP_DRESS, 1025). %% hight:4 id1
-define(MSG_EQUIP_UNDRESS, 1026). %% hight:4 id2
-define(MSG_EQUIP_JIANDING, 1027). %% hight:4 id3
-define(MSG_EQUIP_EMBED_GEM, 1028). %% hight:4 id4
-define(MSG_EQUIP_UNEMBED_GEM, 1029). %% hight:4 id5
-define(MSG_EQUIP_QIANG_HUA, 1030). %% hight:4 id6
-define(MSG_EQUIP_HE_CHENG, 1031). %% hight:4 id7
-define(MSG_EQUIP_JI_CHENG, 1033). %% hight:4 id9
-define(MSG_EQUIP_UNEMBED_ALL_GEM, 1034). %% hight:4 id10
-define(MSG_EQUIP_JIANDING_ALL, 1035). %% hight:4 id11
-define(MSG_EQUIP_SLOT, 1036). %% hight:4 id12
-define(MSG_EQUIP_EXCHANGE, 1037). %% hight:4 id13
-define(MSG_EQUIP_ONE_KEY_EXCHANGE, 1038). %% hight:4 id14
-define(MSG_EQUIP_ACTIVATE_FUMO_MODE, 1039). %% hight:4 id15
-define(MSG_EQUIP_IMBUE_WEAPON, 1040). %% hight:4 id16
-define(MSG_EQUIP_CUI_QU, 1041). %% hight:4 id17
-define(MSG_EQUIP_FUMO_MODE_LIST, 1042). %% hight:4 id18
-define(MSG_EQUIP_EPIC_SLOT, 1043). %% hight:4 id19
-define(MSG_EQUIP_EPIC_EMBED_GEM, 1044). %% hight:4 id20
-define(MSG_EQUIP_EPIC_UNEMBED_GEM, 1045). %% hight:4 id21
-define(MSG_EQUIP_PART_QAINGHUA_INIT, 1046). %% hight:4 id22
-define(MSG_PART_QIANGHUA, 1047). %% hight:4 id23
-define(MSG_EQUIP_XILIAN, 1048). %% hight:4 id24
