%% Auto generated by sproto from friend.sproto
%% Don't edit it.

-define(MSG_FRIEND_APPLY, 3585). %% hight:14 id1
-define(MSG_FRIEND_REPLY_APPLY, 3586). %% hight:14 id2
-define(MSG_FRIEND_DEL, 3587). %% hight:14 id3
-define(MSG_FRIEND_INFOS, 3588). %% hight:14 id4
-define(MSG_FRIEND_LIST, 3589). %% hight:14 id5
-define(MSG_FRIEND_MY_INFO, 3590). %% hight:14 id6
-define(MSG_FRIEND_MSGS, 3591). %% hight:14 id7
-define(MSG_FRIEND_NEAR, 3592). %% hight:14 id8
-define(MSG_FRIEND_DEL_MSG, 3593). %% hight:14 id9
-define(MSG_FRIEND_GIFT_MSG, 3594). %% hight:14 id10
-define(MSG_FRIEND_APPLY_MSG, 3595). %% hight:14 id11
-define(MSG_FRIEND_SEND_GIFT_MSG, 3602). %% hight:14 id18
-define(MSG_FRIEND_ROB_GIFT, 3596). %% hight:14 id12
-define(MSG_FRIEND_ASK_FOR_GIFT, 3597). %% hight:14 id13
-define(MSG_FRIEND_REP_ASK_FOR_GIFT, 3598). %% hight:14 id14
-define(MSG_FRIEND_SEND_GIFT, 3599). %% hight:14 id15
-define(MSG_FRIEND_ACCEPT_SEND_GIFT, 3603). %% hight:14 id19
-define(MSG_FRIEND_SET_GIFT_STAT, 3600). %% hight:14 id16
-define(MSG_FRIEND_CHANGE, 3601). %% hight:14 id17
-define(MSG_FRIEND_GIFT_APPLYS, 3604). %% hight:14 id20
-define(MSG_FRIEND_ADD_GIFT_APPLY, 3605). %% hight:14 id21
-define(MSG_GIVE_GIFT_TO_FRIEND, 3606). %% hight:14 id22
-define(MSG_GIVE_GIFT_RECIVE_INFO, 3607). %% hight:14 id23
-define(MSG_DEL_GIFT_INFO, 3608). %% hight:14 id24
