%% Auto generated by sproto from friend.sproto
%% Don't edit it.

-module(friend_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("friend_sproto.hrl").

%% id=1  
pkg_msg(?MSG_FRIEND_APPLY, {ReplyNum}) ->
<<?MSG_FRIEND_APPLY:16, 
ReplyNum>>
;

%% id=2  
pkg_msg(?MSG_FRIEND_REPLY_APPLY, {ReplyNum, Id}) ->
<<?MSG_FRIEND_REPLY_APPLY:16, 
ReplyNum,
    Id:64>>
;

%% id=3  
pkg_msg(?MSG_FRIEND_DEL, {Id}) ->
<<?MSG_FRIEND_DEL:16, 
Id:64>>
;

%% id=4  
pkg_msg(?MSG_FRIEND_INFOS, {FriendsInfo}) ->
<<?MSG_FRIEND_INFOS:16, 
(length(FriendsInfo)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    PlayerPower:32,
    GiftQua,
    GiftNum,
    GiftStat,
    Score:16,
    IsOnline>>
|| {Id, Name, Lev, Career, PlayerPower, GiftQua, GiftNum, GiftStat, Score, IsOnline} <- FriendsInfo]))/binary >>
;

%% id=5  
pkg_msg(?MSG_FRIEND_LIST, {FriendsInfo}) ->
<<?MSG_FRIEND_LIST:16, 
(length(FriendsInfo)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    PlayerPower:32,
    GiftQua,
    GiftNum,
    GiftStat,
    Score:16,
    IsOnline>>
|| {Id, Name, Lev, Career, PlayerPower, GiftQua, GiftNum, GiftStat, Score, IsOnline} <- FriendsInfo]))/binary >>
;

%% id=6  
pkg_msg(?MSG_FRIEND_MY_INFO, {Score, GiftQua, SendGiftNum, RecvGiftNum, GiftStat}) ->
<<?MSG_FRIEND_MY_INFO:16, 
Score:16,
    GiftQua,
    SendGiftNum,
    RecvGiftNum,
    GiftStat>>
;

%% id=7  
pkg_msg(?MSG_FRIEND_MSGS, {GiftMsg, ReqGift, FriendMsg, FriendSendFlowers}) ->
<<?MSG_FRIEND_MSGS:16, 
(length(GiftMsg)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    (length(ItemInfoL)):16, (iolist_to_binary([<<
ItemBid:32,
    Count:32>>
|| {ItemBid, Count} <- ItemInfoL]))/binary >>
|| {Id, Name, Lev, Career, ItemInfoL} <- GiftMsg]))/binary ,
    (length(ReqGift)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    GiftQua>>
|| {Id, Name, Lev, Career, GiftQua} <- ReqGift]))/binary ,
    (length(FriendMsg)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career>>
|| {Id, Name, Lev, Career} <- FriendMsg]))/binary ,
    (length(FriendSendFlowers)):16, (iolist_to_binary([<<
Msg_id:16,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_lev,
    Player_career,
    Item_bid:32,
    (byte_size(Msg)), Msg/binary>>
|| {Msg_id, Player_id, Player_name, Player_lev, Player_career, Item_bid, Msg} <- FriendSendFlowers]))/binary >>
;

%% id=8  
pkg_msg(?MSG_FRIEND_NEAR, {FriendsInfo}) ->
<<?MSG_FRIEND_NEAR:16, 
(length(FriendsInfo)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    PlayerPower:32,
    GiftQua,
    GiftNum,
    GiftStat,
    Score:16,
    IsOnline>>
|| {Id, Name, Lev, Career, PlayerPower, GiftQua, GiftNum, GiftStat, Score, IsOnline} <- FriendsInfo]))/binary >>
;

%% id=9  
pkg_msg(?MSG_FRIEND_DEL_MSG, {SendGiftIds, ReqGiftIds, FriendIds}) ->
<<?MSG_FRIEND_DEL_MSG:16, 
(length(SendGiftIds)):16, (iolist_to_binary([<<SendGiftId:64>> || SendGiftId <- SendGiftIds]))/binary,
    (length(ReqGiftIds)):16, (iolist_to_binary([<<ReqGiftId:64>> || ReqGiftId <- ReqGiftIds]))/binary,
    (length(FriendIds)):16, (iolist_to_binary([<<FriendId:64>> || FriendId <- FriendIds]))/binary>>
;

%% id=10  
pkg_msg(?MSG_FRIEND_GIFT_MSG, {Id, Name, Lev, Career, GiftQua}) ->
<<?MSG_FRIEND_GIFT_MSG:16, 
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    GiftQua>>
;

%% id=11  
pkg_msg(?MSG_FRIEND_APPLY_MSG, {Id, Name, Lev, Career}) ->
<<?MSG_FRIEND_APPLY_MSG:16, 
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career>>
;

%% id=18  
pkg_msg(?MSG_FRIEND_SEND_GIFT_MSG, {Id, Name, Lev, Career, ItemInfoL}) ->
<<?MSG_FRIEND_SEND_GIFT_MSG:16, 
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    (length(ItemInfoL)):16, (iolist_to_binary([<<
ItemBid:32,
    Count:32>>
|| {ItemBid, Count} <- ItemInfoL]))/binary >>
;

%% id=12  
pkg_msg(?MSG_FRIEND_ROB_GIFT, {ReplyNum}) ->
<<?MSG_FRIEND_ROB_GIFT:16, 
ReplyNum>>
;

%% id=13  
pkg_msg(?MSG_FRIEND_ASK_FOR_GIFT, {ReplyNum}) ->
<<?MSG_FRIEND_ASK_FOR_GIFT:16, 
ReplyNum>>
;

%% id=14  
pkg_msg(?MSG_FRIEND_REP_ASK_FOR_GIFT, {ReplyNum}) ->
<<?MSG_FRIEND_REP_ASK_FOR_GIFT:16, 
ReplyNum>>
;

%% id=15  
pkg_msg(?MSG_FRIEND_SEND_GIFT, {ReplyNum}) ->
<<?MSG_FRIEND_SEND_GIFT:16, 
ReplyNum>>
;

%% id=19  
pkg_msg(?MSG_FRIEND_ACCEPT_SEND_GIFT, {ReplyNum}) ->
<<?MSG_FRIEND_ACCEPT_SEND_GIFT:16, 
ReplyNum>>
;

%% id=16  
pkg_msg(?MSG_FRIEND_SET_GIFT_STAT, {Stat}) ->
<<?MSG_FRIEND_SET_GIFT_STAT:16, 
Stat>>
;

%% id=17  
pkg_msg(?MSG_FRIEND_CHANGE, {Type, FriendInfo}) ->
<<?MSG_FRIEND_CHANGE:16, 
Type,
    (begin {Id, Name, Lev, Career, PlayerPower, GiftQua, GiftNum, GiftStat, Score, IsOnline}=FriendInfo, <<
Id:64,
    (byte_size(Name)), Name/binary,
    Lev,
    Career,
    PlayerPower:32,
    GiftQua,
    GiftNum,
    GiftStat,
    Score:16,
    IsOnline>>
 end)/binary>>
;

%% id=20  
pkg_msg(?MSG_FRIEND_GIFT_APPLYS, {SendIds, RecvIds, FApplyIds, GApplyIds}) ->
<<?MSG_FRIEND_GIFT_APPLYS:16, 
(length(SendIds)):16, (iolist_to_binary([<<SId:64>> || SId <- SendIds]))/binary,
    (length(RecvIds)):16, (iolist_to_binary([<<RId:64>> || RId <- RecvIds]))/binary,
    (length(FApplyIds)):16, (iolist_to_binary([<<FId:64>> || FId <- FApplyIds]))/binary,
    (length(GApplyIds)):16, (iolist_to_binary([<<GId:64>> || GId <- GApplyIds]))/binary>>
;

%% id=21  
pkg_msg(?MSG_FRIEND_ADD_GIFT_APPLY, {Type, Id}) ->
<<?MSG_FRIEND_ADD_GIFT_APPLY:16, 
Type,
    Id:64>>
;

%% id=22  
pkg_msg(?MSG_GIVE_GIFT_TO_FRIEND, {}) ->
<<?MSG_GIVE_GIFT_TO_FRIEND:16>> 
;

%% id=23  
pkg_msg(?MSG_GIVE_GIFT_RECIVE_INFO, {Msg_id, Player_id, Player_name, Player_lev, Player_career, Item_bid, Msg}) ->
<<?MSG_GIVE_GIFT_RECIVE_INFO:16, 
Msg_id:16,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Player_lev,
    Player_career,
    Item_bid:32,
    (byte_size(Msg)), Msg/binary>>
;

%% id=24  
pkg_msg(?MSG_DEL_GIFT_INFO, {}) ->
<<?MSG_DEL_GIFT_INFO:16>> 
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_FRIEND_APPLY, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 2  
unpkg_msg(?MSG_FRIEND_REPLY_APPLY, Acc0) ->
<<Id:64,
IsAgree,
Acc1/binary>> = Acc0,
 {{Id,IsAgree}, Acc1};

%% id = 3  
unpkg_msg(?MSG_FRIEND_DEL, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 4  
unpkg_msg(?MSG_FRIEND_INFOS, Acc0) ->
<<NameLen, Name:NameLen/binary,
Acc1/binary>> = Acc0,
 {{Name}, Acc1};

%% id = 5  
unpkg_msg(?MSG_FRIEND_LIST, Acc0) ->
{{}, Acc0};

%% id = 6  
unpkg_msg(?MSG_FRIEND_MY_INFO, Acc0) ->
{{}, Acc0};

%% id = 7  
unpkg_msg(?MSG_FRIEND_MSGS, Acc0) ->
{{}, Acc0};

%% id = 8  
unpkg_msg(?MSG_FRIEND_NEAR, Acc0) ->
<<Count,
Acc1/binary>> = Acc0,
 {{Count}, Acc1};

%% id = 12  
unpkg_msg(?MSG_FRIEND_ROB_GIFT, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 13  
unpkg_msg(?MSG_FRIEND_ASK_FOR_GIFT, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 14  
unpkg_msg(?MSG_FRIEND_REP_ASK_FOR_GIFT, Acc0) ->
<<Id:64,
IsAgree,
Acc1/binary>> = Acc0,
 {{Id,IsAgree}, Acc1};

%% id = 15  
unpkg_msg(?MSG_FRIEND_SEND_GIFT, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 19  
unpkg_msg(?MSG_FRIEND_ACCEPT_SEND_GIFT, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 16  
unpkg_msg(?MSG_FRIEND_SET_GIFT_STAT, Acc0) ->
<<Stat,
Acc1/binary>> = Acc0,
 {{Stat}, Acc1};

%% id = 20  
unpkg_msg(?MSG_FRIEND_GIFT_APPLYS, Acc0) ->
{{}, Acc0};

%% id = 22  
unpkg_msg(?MSG_GIVE_GIFT_TO_FRIEND, Acc0) ->
<<Itembid:32,
To_player_id:64,
MsgLen, Msg:MsgLen/binary,
Acc1/binary>> = Acc0,
 {{Itembid,To_player_id,Msg}, Acc1};

%% id = 24  
unpkg_msg(?MSG_DEL_GIFT_INFO, Acc0) ->
<<Msg_id:16,
Acc1/binary>> = Acc0,
 {{Msg_id}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_FRIEND_APPLY) -> <<"MSG_FRIEND_APPLY">>; %% high 14, id 1
to_s(?MSG_FRIEND_REPLY_APPLY) -> <<"MSG_FRIEND_REPLY_APPLY">>; %% high 14, id 2
to_s(?MSG_FRIEND_DEL) -> <<"MSG_FRIEND_DEL">>; %% high 14, id 3
to_s(?MSG_FRIEND_INFOS) -> <<"MSG_FRIEND_INFOS">>; %% high 14, id 4
to_s(?MSG_FRIEND_LIST) -> <<"MSG_FRIEND_LIST">>; %% high 14, id 5
to_s(?MSG_FRIEND_MY_INFO) -> <<"MSG_FRIEND_MY_INFO">>; %% high 14, id 6
to_s(?MSG_FRIEND_MSGS) -> <<"MSG_FRIEND_MSGS">>; %% high 14, id 7
to_s(?MSG_FRIEND_NEAR) -> <<"MSG_FRIEND_NEAR">>; %% high 14, id 8
to_s(?MSG_FRIEND_DEL_MSG) -> <<"MSG_FRIEND_DEL_MSG">>; %% high 14, id 9
to_s(?MSG_FRIEND_GIFT_MSG) -> <<"MSG_FRIEND_GIFT_MSG">>; %% high 14, id 10
to_s(?MSG_FRIEND_APPLY_MSG) -> <<"MSG_FRIEND_APPLY_MSG">>; %% high 14, id 11
to_s(?MSG_FRIEND_SEND_GIFT_MSG) -> <<"MSG_FRIEND_SEND_GIFT_MSG">>; %% high 14, id 18
to_s(?MSG_FRIEND_ROB_GIFT) -> <<"MSG_FRIEND_ROB_GIFT">>; %% high 14, id 12
to_s(?MSG_FRIEND_ASK_FOR_GIFT) -> <<"MSG_FRIEND_ASK_FOR_GIFT">>; %% high 14, id 13
to_s(?MSG_FRIEND_REP_ASK_FOR_GIFT) -> <<"MSG_FRIEND_REP_ASK_FOR_GIFT">>; %% high 14, id 14
to_s(?MSG_FRIEND_SEND_GIFT) -> <<"MSG_FRIEND_SEND_GIFT">>; %% high 14, id 15
to_s(?MSG_FRIEND_ACCEPT_SEND_GIFT) -> <<"MSG_FRIEND_ACCEPT_SEND_GIFT">>; %% high 14, id 19
to_s(?MSG_FRIEND_SET_GIFT_STAT) -> <<"MSG_FRIEND_SET_GIFT_STAT">>; %% high 14, id 16
to_s(?MSG_FRIEND_CHANGE) -> <<"MSG_FRIEND_CHANGE">>; %% high 14, id 17
to_s(?MSG_FRIEND_GIFT_APPLYS) -> <<"MSG_FRIEND_GIFT_APPLYS">>; %% high 14, id 20
to_s(?MSG_FRIEND_ADD_GIFT_APPLY) -> <<"MSG_FRIEND_ADD_GIFT_APPLY">>; %% high 14, id 21
to_s(?MSG_GIVE_GIFT_TO_FRIEND) -> <<"MSG_GIVE_GIFT_TO_FRIEND">>; %% high 14, id 22
to_s(?MSG_GIVE_GIFT_RECIVE_INFO) -> <<"MSG_GIVE_GIFT_RECIVE_INFO">>; %% high 14, id 23
to_s(?MSG_DEL_GIFT_INFO) -> <<"MSG_DEL_GIFT_INFO">>; %% high 14, id 24
to_s(_) -> <<"unknown msg">>.
