%% Auto generated by sproto from gm.sproto
%% Don't edit it.

-module(gm_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("gm_sproto.hrl").

%% id=2  
pkg_msg(?MSG_GM_ADD, {ReplyNum}) ->
<<?MSG_GM_ADD:16, 
ReplyNum>>
;

%% id=3  
pkg_msg(?MSG_GM_LEV, {ReplyNum}) ->
<<?MSG_GM_LEV:16, 
ReplyNum>>
;

%% id=4  
pkg_msg(?MSG_GM_ADD_ITEM, {ReplyNum}) ->
<<?MSG_GM_ADD_ITEM:16, 
ReplyNum>>
;

%% id=6  
pkg_msg(?MSG_GM_STRING_CMD, {ReplyNum, String}) ->
<<?MSG_GM_STRING_CMD:16, 
ReplyNum,
    (byte_size(String)), String/binary>>
;

%% id=7  
pkg_msg(?MSG_GM_TASK, {ReplyNum}) ->
<<?MSG_GM_TASK:16, 
ReplyNum>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_GM_ADD, Acc0) ->
<<MoneyType,
Money:64,
Acc1/binary>> = Acc0,
 {{MoneyType,Money}, Acc1};

%% id = 3  
unpkg_msg(?MSG_GM_LEV, Acc0) ->
<<Lev,
Acc1/binary>> = Acc0,
 {{Lev}, Acc1};

%% id = 4  
unpkg_msg(?MSG_GM_ADD_ITEM, Acc0) ->
<<ItemBid:32,
ItemCount:16,
Bind,
Acc1/binary>> = Acc0,
 {{ItemBid,ItemCount,Bind}, Acc1};

%% id = 5  
unpkg_msg(?MSG_GM_MAIL, Acc0) ->
<<ItemNum,
AssetsNum,
Acc1/binary>> = Acc0,
 {{ItemNum,AssetsNum}, Acc1};

%% id = 6  
unpkg_msg(?MSG_GM_STRING_CMD, Acc0) ->
<<StringLen, String:StringLen/binary,
Acc1/binary>> = Acc0,
 {{String}, Acc1};

%% id = 7  
unpkg_msg(?MSG_GM_TASK, Acc0) ->
<<Task,
Acc1/binary>> = Acc0,
 {{Task}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_GM_ADD) -> <<"MSG_GM_ADD">>; %% high 11, id 2
to_s(?MSG_GM_LEV) -> <<"MSG_GM_LEV">>; %% high 11, id 3
to_s(?MSG_GM_ADD_ITEM) -> <<"MSG_GM_ADD_ITEM">>; %% high 11, id 4
to_s(?MSG_GM_MAIL) -> <<"MSG_GM_MAIL">>; %% high 11, id 5
to_s(?MSG_GM_STRING_CMD) -> <<"MSG_GM_STRING_CMD">>; %% high 11, id 6
to_s(?MSG_GM_TASK) -> <<"MSG_GM_TASK">>; %% high 11, id 7
to_s(_) -> <<"unknown msg">>.
