%% Auto generated by sproto from gm.sproto
%% Don't edit it.

-define(MSG_GM_CMD, 2817). %% hight:11 id1
-define(MSG_GM_ADD, 2818). %% hight:11 id2
-define(MSG_GM_LEV, 2819). %% hight:11 id3
-define(MSG_GM_ADD_ITEM, 2820). %% hight:11 id4
-define(MSG_GM_MAIL, 2821). %% hight:11 id5
-define(MSG_GM_STRING_CMD, 2822). %% hight:11 id6
-define(MSG_GM_TASK, 2823). %% hight:11 id7
