%% Auto generated by sproto from gongcheng.sproto
%% Don't edit it.

-module(gongcheng_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("gongcheng_sproto.hrl").

%% id=1  
pkg_msg(?MSG_GONGCHENG_STAR, {IsOK}) ->
<<?MSG_GONGCHENG_STAR:16, 
IsOK>>
;

%% id=2  
pkg_msg(?MSG_GONGCHENG_COMPLETE, {JiFen, PlayerName, PlayerLevel, Career, CombatPower, PrizeInfo, BestPrize}) ->
<<?MSG_GONGCHENG_COMPLETE:16, 
JiFen:32,
    (byte_size(PlayerName)), PlayerName/binary,
    PlayerLevel,
    Career,
    CombatPower:32,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary ,
    (length(BestPrize)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- BestPrize]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_GONGCHENG_STAR, Acc0) ->
<<NpcId:16,
Type,
Acc1/binary>> = Acc0,
 {{NpcId,Type}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_GONGCHENG_STAR) -> <<"MSG_GONGCHENG_STAR">>; %% high 44, id 1
to_s(?MSG_GONGCHENG_COMPLETE) -> <<"MSG_GONGCHENG_COMPLETE">>; %% high 44, id 2
to_s(_) -> <<"unknown msg">>.
