%% Auto generated by sproto from guild.sproto
%% Don't edit it.

-module(guild_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("guild_sproto.hrl").

%% id=1  
pkg_msg(?MSG_GUILD_DATA_LIST, {GuildMsg}) ->
<<?MSG_GUILD_DATA_LIST:16, 
(length(GuildMsg)):16, (iolist_to_binary([<<
Totem_id,
    Border_id,
    Lv,
    (byte_size(Guild_name)), Guild_name/binary,
    (byte_size(Master_name)), Master_name/binary,
    Master_id:64,
    Totle_player,
    Guild_id:32,
    Is_apply>>
|| {Totem_id, Border_id, Lv, Guild_name, Master_name, Master_id, Totle_player, Guild_id, Is_apply} <- GuildMsg]))/binary >>
;

%% id=2  
pkg_msg(?MSG_GUILD_MEMBER_LIST, {GuildMemberMsg}) ->
<<?MSG_GUILD_MEMBER_LIST:16, 
(length(GuildMemberMsg)):16, (iolist_to_binary([<<
Player_id:64,
    Player_level,
    Job_id,
    (byte_size(Player_name)), Player_name/binary,
    Position_id,
    Combat_power:32,
    Contribution_value:32,
    Is_friend,
    Is_online>>
|| {Player_id, Player_level, Job_id, Player_name, Position_id, Combat_power, Contribution_value, Is_friend, Is_online} <- GuildMemberMsg]))/binary >>
;

%% id=3  
pkg_msg(?MSG_GUILD_EVENT_LIST, {GuildEventMsg}) ->
<<?MSG_GUILD_EVENT_LIST:16, 
(length(GuildEventMsg)):16, (iolist_to_binary([<<
Id,
    Time:32,
    Player_id:64,
    (byte_size(Player_name)), Player_name/binary,
    Position>>
|| {Id, Time, Player_id, Player_name, Position} <- GuildEventMsg]))/binary >>
;

%% id=5  
pkg_msg(?MSG_GUILD_INFO, {Totem_id, Border_id, Guild_lv, Guild_name, Master_name, Master_id, Totle_player, Guild_id, Guild_rank, Notice, Notice_time, Guild_exp, Position, Role_lv, Role_exp, Contribution_value, Building_info_list, Tech_info_list}) ->
<<?MSG_GUILD_INFO:16, 
Totem_id,
    Border_id,
    Guild_lv,
    (byte_size(Guild_name)), Guild_name/binary,
    (byte_size(Master_name)), Master_name/binary,
    Master_id:64,
    Totle_player,
    Guild_id:32,
    Guild_rank:16,
    (byte_size(Notice)), Notice/binary,
    Notice_time:32,
    Guild_exp:32,
    Position,
    Role_lv,
    Role_exp:32,
    Contribution_value:32,
    (length(Building_info_list)):16, (iolist_to_binary([<<
Building_type,
    Building_daily_task_count,
    Building_lv,
    Building_exp:32>>
|| {Building_type, Building_daily_task_count, Building_lv, Building_exp} <- Building_info_list]))/binary ,
    (length(Tech_info_list)):16, (iolist_to_binary([<<
Tech_id,
    Tech_lv>>
|| {Tech_id, Tech_lv} <- Tech_info_list]))/binary >>
;

%% id=6  
pkg_msg(?MSG_GUILD_APPLY_LIST, {GuildApplyMsg}) ->
<<?MSG_GUILD_APPLY_LIST:16, 
(length(GuildApplyMsg)):16, (iolist_to_binary([<<
Player_id:64,
    Job_id,
    Lv,
    (byte_size(Name)), Name/binary,
    Combat_power:32,
    Is_online>>
|| {Player_id, Job_id, Lv, Name, Combat_power, Is_online} <- GuildApplyMsg]))/binary >>
;

%% id=101  
pkg_msg(?MSG_GUILD_CREATE, {}) ->
<<?MSG_GUILD_CREATE:16>> 
;

%% id=102  
pkg_msg(?MSG_GUILD_UPDATE_NOTICE, {}) ->
<<?MSG_GUILD_UPDATE_NOTICE:16>> 
;

%% id=103  
pkg_msg(?MSG_GUILD_POSITION, {To_player_id, Position_id}) ->
<<?MSG_GUILD_POSITION:16, 
To_player_id:64,
    Position_id>>
;

%% id=104  
pkg_msg(?MSG_GUILD_PLAYERDEL, {To_player_id}) ->
<<?MSG_GUILD_PLAYERDEL:16, 
To_player_id:64>>
;

%% id=105  
pkg_msg(?MSG_GUILD_ROLE_APPLY, {Type}) ->
<<?MSG_GUILD_ROLE_APPLY:16, 
Type>>
;

%% id=106  
pkg_msg(?MSG_GUILD_ROLES_APPLY, {Type}) ->
<<?MSG_GUILD_ROLES_APPLY:16, 
Type>>
;

%% id=107  
pkg_msg(?MSG_GUILD_BUILDING_ADDEXP, {Building_id, Building_lv, Building_exp, BuildingType_lv, BuildingType_exp}) ->
<<?MSG_GUILD_BUILDING_ADDEXP:16, 
Building_id,
    Building_lv,
    Building_exp:32,
    BuildingType_lv,
    BuildingType_exp:32>>
;

%% id=108  
pkg_msg(?MSG_GUILD_OUT, {}) ->
<<?MSG_GUILD_OUT:16>> 
;

%% id=109  
pkg_msg(?MSG_GUILD_APPLY, {Guild_id}) ->
<<?MSG_GUILD_APPLY:16, 
Guild_id:32>>
;

%% id=110  
pkg_msg(?MSG_GUILD_SEARCH, {Rank, Totem_id, Border_id, Lv, Name, Master_name, Totle_player, Guild_id, Is_apply}) ->
<<?MSG_GUILD_SEARCH:16, 
Rank:16,
    Totem_id,
    Border_id,
    Lv,
    (byte_size(Name)), Name/binary,
    (byte_size(Master_name)), Master_name/binary,
    Totle_player,
    Guild_id:32,
    Is_apply>>
;

%% id=111  
pkg_msg(?MSG_GUILD_BUY_ITEM, {}) ->
<<?MSG_GUILD_BUY_ITEM:16>> 
;

%% id=112  
pkg_msg(?MSG_GUILD_TECH_LVUP, {Tech_id}) ->
<<?MSG_GUILD_TECH_LVUP:16, 
Tech_id>>
;

%% id=201  
pkg_msg(?MSG_GUILD_PUSH_ROLEEXP, {Role_lv, Role_exp, Role_contribution, Player_position_id}) ->
<<?MSG_GUILD_PUSH_ROLEEXP:16, 
Role_lv,
    Role_exp:32,
    Role_contribution:32,
    Player_position_id>>
;

%% id=203  
pkg_msg(?MSG_GUILD_PUSH_JOIN_GUILD, {}) ->
<<?MSG_GUILD_PUSH_JOIN_GUILD:16>> 
;

%% id=204  
pkg_msg(?MSG_GUILD_PUSH_REMOVE_GUILD, {}) ->
<<?MSG_GUILD_PUSH_REMOVE_GUILD:16>> 
;

%% id=205  
pkg_msg(?MSG_GUILD_PUSH_GUILD_MEMBER_JOIN, {GuildMemberMsg}) ->
<<?MSG_GUILD_PUSH_GUILD_MEMBER_JOIN:16, 
(length(GuildMemberMsg)):16, (iolist_to_binary([<<
Player_id:64,
    Player_level,
    Job_id,
    (byte_size(Player_name)), Player_name/binary,
    Position_id,
    Combat_power:32,
    Contribution_value:32,
    Is_friend,
    Is_online>>
|| {Player_id, Player_level, Job_id, Player_name, Position_id, Combat_power, Contribution_value, Is_friend, Is_online} <- GuildMemberMsg]))/binary >>
;

%% id=206  
pkg_msg(?MSG_GUILD_PUSH_GUILD_MEMBER_QUIT, {Player_id}) ->
<<?MSG_GUILD_PUSH_GUILD_MEMBER_QUIT:16, 
Player_id:64>>
;

%% id=207  
pkg_msg(?PUSH_GUILD_MEMBER_POSITION, {Player_id, Position_id}) ->
<<?PUSH_GUILD_MEMBER_POSITION:16, 
Player_id:64,
    Position_id>>
;

%% id=208  
pkg_msg(?PUSH_GUILD_BUILDING_ADD_EXP, {Daily_task_count}) ->
<<?PUSH_GUILD_BUILDING_ADD_EXP:16, 
(length(Daily_task_count)):16, (iolist_to_binary([<<
Building_type,
    Building_daily_task_count>>
|| {Building_type, Building_daily_task_count} <- Daily_task_count]))/binary >>
;

%% id=11  
pkg_msg(?MSG_GUILD_BOSS_INFO, {Id, Exp, Hp, End_time, Has_challage_count, Has_donate_count, Has_call_count}) ->
<<?MSG_GUILD_BOSS_INFO:16, 
Id:16,
    Exp:32,
    Hp:32,
    End_time:32,
    Has_challage_count:16,
    Has_donate_count:16,
    Has_call_count:16>>
;

%% id=12  
pkg_msg(?MSG_GUILD_BOSS_DONATE, {Id, Exp, Donate_count, Ret}) ->
<<?MSG_GUILD_BOSS_DONATE:16, 
Id:16,
    Exp:32,
    Donate_count:16,
    Ret>>
;

%% id=13  
pkg_msg(?MSG_GUILD_BOSS_PHASE, {Id, Ret}) ->
<<?MSG_GUILD_BOSS_PHASE:16, 
Id:16,
    Ret>>
;

%% id=14  
pkg_msg(?MSG_GUILD_BOSS_CALL, {Id, Dt, Call_count, Ret}) ->
<<?MSG_GUILD_BOSS_CALL:16, 
Id:16,
    Dt:32,
    Call_count:16,
    Ret>>
;

%% id=15  
pkg_msg(?MSG_GUILD_BOSS_DAMAGE, {Id, Cur_hp, Damage}) ->
<<?MSG_GUILD_BOSS_DAMAGE:16, 
Id:16,
    Cur_hp:32,
    (length(Damage)):16, (iolist_to_binary([<<
Index,
    PlayerCarrer,
    (byte_size(PlayerName)), PlayerName/binary,
    Damage:32>>
|| {Index, PlayerCarrer, PlayerName, Damage} <- Damage]))/binary >>
;

%% id=16  
pkg_msg(?MSG_GUILD_BOSS_COMPELE, {Id, Killer, Ret}) ->
<<?MSG_GUILD_BOSS_COMPELE:16, 
Id:16,
    Killer:64,
    Ret>>
;

%% id=17  
pkg_msg(?MSG_GUILD_BOSS_CHALLENGE, {Id, Cur_hp, Ret}) ->
<<?MSG_GUILD_BOSS_CHALLENGE:16, 
Id:16,
    Cur_hp:32,
    Ret>>
;

%% id=18  
pkg_msg(?MSG_GUILD_BOSS_COMPELE_PRIZE, {Is_succeed, MyPrize, PlayerPrize}) ->
<<?MSG_GUILD_BOSS_COMPELE_PRIZE:16, 
Is_succeed,
    (begin {Index, PlayerCarrer, PlayerName, Player_level, Damage, PrizeInfo}=MyPrize, <<
Index,
    PlayerCarrer,
    (byte_size(PlayerName)), PlayerName/binary,
    Player_level,
    Damage:32,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
 end)/binary,
    (length(PlayerPrize)):16, (iolist_to_binary([<<
Index,
    PlayerCarrer,
    (byte_size(PlayerName)), PlayerName/binary,
    Player_level,
    Damage:32,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
|| {Index, PlayerCarrer, PlayerName, Player_level, Damage, PrizeInfo} <- PlayerPrize]))/binary >>
;

%% id=20  
pkg_msg(?MSG_GUILD_BOSS_BUY_REVIVE, {Ret}) ->
<<?MSG_GUILD_BOSS_BUY_REVIVE:16, 
Ret>>
;

%% id=21  
pkg_msg(?MSG_GUILD_APPLY_UPDATE, {Num}) ->
<<?MSG_GUILD_APPLY_UPDATE:16, 
Num>>
;

%% id=22  
pkg_msg(?MSG_GUILD_SAINT_EXCHANGE, {PrizeInfo}) ->
<<?MSG_GUILD_SAINT_EXCHANGE:16, 
(length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=23  
pkg_msg(?MSG_GUILD_SAINT_EXCHANGE_ALL, {PrizeInfo}) ->
<<?MSG_GUILD_SAINT_EXCHANGE_ALL:16, 
(length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=24  
pkg_msg(?MSG_GUILD_SAINT_EXCHANGE_STATUS, {Saint_status}) ->
<<?MSG_GUILD_SAINT_EXCHANGE_STATUS:16, 
(length(Saint_status)):16, (iolist_to_binary([<<
Saint_id,
    Status>>
|| {Saint_id, Status} <- Saint_status]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_GUILD_DATA_LIST, Acc0) ->
<<PageStart:16,
PageEnd:16,
Acc1/binary>> = Acc0,
 {{PageStart,PageEnd}, Acc1};

%% id = 2  
unpkg_msg(?MSG_GUILD_MEMBER_LIST, Acc0) ->
{{}, Acc0};

%% id = 3  
unpkg_msg(?MSG_GUILD_EVENT_LIST, Acc0) ->
<<PageStart,
PageEnd,
Acc1/binary>> = Acc0,
 {{PageStart,PageEnd}, Acc1};

%% id = 5  
unpkg_msg(?MSG_GUILD_INFO, Acc0) ->
{{}, Acc0};

%% id = 6  
unpkg_msg(?MSG_GUILD_APPLY_LIST, Acc0) ->
{{}, Acc0};

%% id = 101  
unpkg_msg(?MSG_GUILD_CREATE, Acc0) ->
<<NameLen, Name:NameLen/binary,
Totem_id,
Border_id,
Acc1/binary>> = Acc0,
 {{Name,Totem_id,Border_id}, Acc1};

%% id = 102  
unpkg_msg(?MSG_GUILD_UPDATE_NOTICE, Acc0) ->
<<NoticeLen, Notice:NoticeLen/binary,
Acc1/binary>> = Acc0,
 {{Notice}, Acc1};

%% id = 103  
unpkg_msg(?MSG_GUILD_POSITION, Acc0) ->
<<To_player_id:64,
Position_id,
Acc1/binary>> = Acc0,
 {{To_player_id,Position_id}, Acc1};

%% id = 104  
unpkg_msg(?MSG_GUILD_PLAYERDEL, Acc0) ->
<<To_player_id:64,
Acc1/binary>> = Acc0,
 {{To_player_id}, Acc1};

%% id = 105  
unpkg_msg(?MSG_GUILD_ROLE_APPLY, Acc0) ->
<<Type,
To_player_id:64,
Acc1/binary>> = Acc0,
 {{Type,To_player_id}, Acc1};

%% id = 106  
unpkg_msg(?MSG_GUILD_ROLES_APPLY, Acc0) ->
<<Type,
Acc1/binary>> = Acc0,
 {{Type}, Acc1};

%% id = 107  
unpkg_msg(?MSG_GUILD_BUILDING_ADDEXP, Acc0) ->
<<Building_id,
Cost_type,
Acc1/binary>> = Acc0,
 {{Building_id,Cost_type}, Acc1};

%% id = 108  
unpkg_msg(?MSG_GUILD_OUT, Acc0) ->
{{}, Acc0};

%% id = 109  
unpkg_msg(?MSG_GUILD_APPLY, Acc0) ->
<<Guild_id:32,
Acc1/binary>> = Acc0,
 {{Guild_id}, Acc1};

%% id = 110  
unpkg_msg(?MSG_GUILD_SEARCH, Acc0) ->
<<Guild_id:32,
Acc1/binary>> = Acc0,
 {{Guild_id}, Acc1};

%% id = 111  
unpkg_msg(?MSG_GUILD_BUY_ITEM, Acc0) ->
<<Item_id:32,
Item_num,
Acc1/binary>> = Acc0,
 {{Item_id,Item_num}, Acc1};

%% id = 112  
unpkg_msg(?MSG_GUILD_TECH_LVUP, Acc0) ->
<<Tech_id,
Cost_type,
Acc1/binary>> = Acc0,
 {{Tech_id,Cost_type}, Acc1};

%% id = 11  
unpkg_msg(?MSG_GUILD_BOSS_INFO, Acc0) ->
{{}, Acc0};

%% id = 12  
unpkg_msg(?MSG_GUILD_BOSS_DONATE, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 13  
unpkg_msg(?MSG_GUILD_BOSS_PHASE, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 14  
unpkg_msg(?MSG_GUILD_BOSS_CALL, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 15  
unpkg_msg(?MSG_GUILD_BOSS_DAMAGE, Acc0) ->
<<Id:16,
Damage:32,
Acc1/binary>> = Acc0,
 {{Id,Damage}, Acc1};

%% id = 16  
unpkg_msg(?MSG_GUILD_BOSS_COMPELE, Acc0) ->
{{}, Acc0};

%% id = 17  
unpkg_msg(?MSG_GUILD_BOSS_CHALLENGE, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 18  
unpkg_msg(?MSG_GUILD_BOSS_COMPELE_PRIZE, Acc0) ->
{{}, Acc0};

%% id = 20  
unpkg_msg(?MSG_GUILD_BOSS_BUY_REVIVE, Acc0) ->
{{}, Acc0};

%% id = 21  
unpkg_msg(?MSG_GUILD_APPLY_UPDATE, Acc0) ->
{{}, Acc0};

%% id = 22  
unpkg_msg(?MSG_GUILD_SAINT_EXCHANGE, Acc0) ->
<<TechnologyId,
Acc1/binary>> = Acc0,
 {{TechnologyId}, Acc1};

%% id = 23  
unpkg_msg(?MSG_GUILD_SAINT_EXCHANGE_ALL, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_GUILD_DATA_LIST) -> <<"MSG_GUILD_DATA_LIST">>; %% high 22, id 1
to_s(?MSG_GUILD_MEMBER_LIST) -> <<"MSG_GUILD_MEMBER_LIST">>; %% high 22, id 2
to_s(?MSG_GUILD_EVENT_LIST) -> <<"MSG_GUILD_EVENT_LIST">>; %% high 22, id 3
to_s(?MSG_GUILD_INFO) -> <<"MSG_GUILD_INFO">>; %% high 22, id 5
to_s(?MSG_GUILD_APPLY_LIST) -> <<"MSG_GUILD_APPLY_LIST">>; %% high 22, id 6
to_s(?MSG_GUILD_CREATE) -> <<"MSG_GUILD_CREATE">>; %% high 22, id 101
to_s(?MSG_GUILD_UPDATE_NOTICE) -> <<"MSG_GUILD_UPDATE_NOTICE">>; %% high 22, id 102
to_s(?MSG_GUILD_POSITION) -> <<"MSG_GUILD_POSITION">>; %% high 22, id 103
to_s(?MSG_GUILD_PLAYERDEL) -> <<"MSG_GUILD_PLAYERDEL">>; %% high 22, id 104
to_s(?MSG_GUILD_ROLE_APPLY) -> <<"MSG_GUILD_ROLE_APPLY">>; %% high 22, id 105
to_s(?MSG_GUILD_ROLES_APPLY) -> <<"MSG_GUILD_ROLES_APPLY">>; %% high 22, id 106
to_s(?MSG_GUILD_BUILDING_ADDEXP) -> <<"MSG_GUILD_BUILDING_ADDEXP">>; %% high 22, id 107
to_s(?MSG_GUILD_OUT) -> <<"MSG_GUILD_OUT">>; %% high 22, id 108
to_s(?MSG_GUILD_APPLY) -> <<"MSG_GUILD_APPLY">>; %% high 22, id 109
to_s(?MSG_GUILD_SEARCH) -> <<"MSG_GUILD_SEARCH">>; %% high 22, id 110
to_s(?MSG_GUILD_BUY_ITEM) -> <<"MSG_GUILD_BUY_ITEM">>; %% high 22, id 111
to_s(?MSG_GUILD_TECH_LVUP) -> <<"MSG_GUILD_TECH_LVUP">>; %% high 22, id 112
to_s(?MSG_GUILD_PUSH_ROLEEXP) -> <<"MSG_GUILD_PUSH_ROLEEXP">>; %% high 22, id 201
to_s(?MSG_GUILD_PUSH_JOIN_GUILD) -> <<"MSG_GUILD_PUSH_JOIN_GUILD">>; %% high 22, id 203
to_s(?MSG_GUILD_PUSH_REMOVE_GUILD) -> <<"MSG_GUILD_PUSH_REMOVE_GUILD">>; %% high 22, id 204
to_s(?MSG_GUILD_PUSH_GUILD_MEMBER_JOIN) -> <<"MSG_GUILD_PUSH_GUILD_MEMBER_JOIN">>; %% high 22, id 205
to_s(?MSG_GUILD_PUSH_GUILD_MEMBER_QUIT) -> <<"MSG_GUILD_PUSH_GUILD_MEMBER_QUIT">>; %% high 22, id 206
to_s(?PUSH_GUILD_MEMBER_POSITION) -> <<"PUSH_GUILD_MEMBER_POSITION">>; %% high 22, id 207
to_s(?PUSH_GUILD_BUILDING_ADD_EXP) -> <<"PUSH_GUILD_BUILDING_ADD_EXP">>; %% high 22, id 208
to_s(?MSG_GUILD_BOSS_INFO) -> <<"MSG_GUILD_BOSS_INFO">>; %% high 22, id 11
to_s(?MSG_GUILD_BOSS_DONATE) -> <<"MSG_GUILD_BOSS_DONATE">>; %% high 22, id 12
to_s(?MSG_GUILD_BOSS_PHASE) -> <<"MSG_GUILD_BOSS_PHASE">>; %% high 22, id 13
to_s(?MSG_GUILD_BOSS_CALL) -> <<"MSG_GUILD_BOSS_CALL">>; %% high 22, id 14
to_s(?MSG_GUILD_BOSS_DAMAGE) -> <<"MSG_GUILD_BOSS_DAMAGE">>; %% high 22, id 15
to_s(?MSG_GUILD_BOSS_COMPELE) -> <<"MSG_GUILD_BOSS_COMPELE">>; %% high 22, id 16
to_s(?MSG_GUILD_BOSS_CHALLENGE) -> <<"MSG_GUILD_BOSS_CHALLENGE">>; %% high 22, id 17
to_s(?MSG_GUILD_BOSS_COMPELE_PRIZE) -> <<"MSG_GUILD_BOSS_COMPELE_PRIZE">>; %% high 22, id 18
to_s(?MSG_GUILD_BOSS_BUY_REVIVE) -> <<"MSG_GUILD_BOSS_BUY_REVIVE">>; %% high 22, id 20
to_s(?MSG_GUILD_APPLY_UPDATE) -> <<"MSG_GUILD_APPLY_UPDATE">>; %% high 22, id 21
to_s(?MSG_GUILD_SAINT_EXCHANGE) -> <<"MSG_GUILD_SAINT_EXCHANGE">>; %% high 22, id 22
to_s(?MSG_GUILD_SAINT_EXCHANGE_ALL) -> <<"MSG_GUILD_SAINT_EXCHANGE_ALL">>; %% high 22, id 23
to_s(?MSG_GUILD_SAINT_EXCHANGE_STATUS) -> <<"MSG_GUILD_SAINT_EXCHANGE_STATUS">>; %% high 22, id 24
to_s(_) -> <<"unknown msg">>.
