%% Auto generated by sproto from guild_mining.sproto
%% Don't edit it.

-define(MSG_GUILD_MINING_BUY_COUNT, 13570). %% hight:53 id2
-define(MSG_GUILD_MINING_ZHAOJI, 13571). %% hight:53 id3
-define(MSG_GUILD_MINING_INFO_SEND, 13572). %% hight:53 id4
-define(MSG_GUILD_MINING_KIND, 13573). %% hight:53 id5
