%% Auto generated by sproto from guild_mining.sproto
%% Don't edit it.

-module(guild_mining_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("guild_mining_sproto.hrl").

%% id=2  
pkg_msg(?MSG_GUILD_MINING_BUY_COUNT, {Sign}) ->
<<?MSG_GUILD_MINING_BUY_COUNT:16, 
Sign>>
;

%% id=3  
pkg_msg(?MSG_GUILD_MINING_ZHAOJI, {Sign}) ->
<<?MSG_GUILD_MINING_ZHAOJI:16, 
Sign>>
;

%% id=4  
pkg_msg(?MSG_GUILD_MINING_INFO_SEND, {PlayerBin, End_time, Mining_count, Buyed_count}) ->
<<?MSG_GUILD_MINING_INFO_SEND:16, 
PlayerBin/binary,
    End_time:32,
    Mining_count,
    Buyed_count>>
;

%% id=5  
pkg_msg(?MSG_GUILD_MINING_KIND, {Sign}) ->
<<?MSG_GUILD_MINING_KIND:16, 
Sign>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_GUILD_MINING_BUY_COUNT, Acc0) ->
<<Buy_count,
Acc1/binary>> = Acc0,
 {{Buy_count}, Acc1};

%% id = 3  
unpkg_msg(?MSG_GUILD_MINING_ZHAOJI, Acc0) ->
{{}, Acc0};

%% id = 4  
unpkg_msg(?MSG_GUILD_MINING_INFO_SEND, Acc0) ->
{{}, Acc0};

%% id = 5  
unpkg_msg(?MSG_GUILD_MINING_KIND, Acc0) ->
<<Mining_kind,
Seat,
Acc1/binary>> = Acc0,
 {{Mining_kind,Seat}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_GUILD_MINING_BUY_COUNT) -> <<"MSG_GUILD_MINING_BUY_COUNT">>; %% high 53, id 2
to_s(?MSG_GUILD_MINING_ZHAOJI) -> <<"MSG_GUILD_MINING_ZHAOJI">>; %% high 53, id 3
to_s(?MSG_GUILD_MINING_INFO_SEND) -> <<"MSG_GUILD_MINING_INFO_SEND">>; %% high 53, id 4
to_s(?MSG_GUILD_MINING_KIND) -> <<"MSG_GUILD_MINING_KIND">>; %% high 53, id 5
to_s(_) -> <<"unknown msg">>.
