%% Auto generated by sproto from honest_user.sproto
%% Don't edit it.

-module(honest_user_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("honest_user_sproto.hrl").

%% id=1  
pkg_msg(?MSG_HONEST_USER_GET_INFO, {State1, State2}) ->
<<?MSG_HONEST_USER_GET_INFO:16, 
State1,
    State2>>
;

%% id=2  
pkg_msg(?MSG_HONEST_USER_GET_PRIZE, {Activity_index, Result}) ->
<<?MSG_HONEST_USER_GET_PRIZE:16, 
Activity_index,
    Result>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_HONEST_USER_GET_INFO, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_HONEST_USER_GET_PRIZE, Acc0) ->
<<Activity_index,
Acc1/binary>> = Acc0,
 {{Activity_index}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_HONEST_USER_GET_INFO) -> <<"MSG_HONEST_USER_GET_INFO">>; %% high 40, id 1
to_s(?MSG_HONEST_USER_GET_PRIZE) -> <<"MSG_HONEST_USER_GET_PRIZE">>; %% high 40, id 2
to_s(_) -> <<"unknown msg">>.
