%% Auto generated by sproto from impact_ranking_list.sproto
%% Don't edit it.

-define(MSG_IMPACT_RANKING_LIST_BUY_PRIZE, 13057). %% hight:51 id1
-define(MSG_IMPACT_RANKING_LIST_SUIT_INFO, 13058). %% hight:51 id2
-define(MSG_IMPACT_RANK_BUY_LIST_INFO, 13059). %% hight:51 id3
