%% Auto generated by sproto from item.sproto
%% Don't edit it.

-module(item_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("item_sproto.hrl").

%% id=1  
pkg_msg(?MSG_ITEM_BUCKET_PUSH_DEL_IDS, {BucketType, DelItemL}) ->
<<?MSG_ITEM_BUCKET_PUSH_DEL_IDS:16, 
BucketType,
    (length(DelItemL)):16, (iolist_to_binary([<<ItemId:32>> || ItemId <- DelItemL]))/binary>>
;

%% id=2  
pkg_msg(?MSG_ITEM_BUCKET_PUSH_CHG, {PushType, BucketType, ItemChangeL}) ->
<<?MSG_ITEM_BUCKET_PUSH_CHG:16, 
PushType,
    BucketType,
    (length(ItemChangeL)):16, (iolist_to_binary([<<
ItemId:32,
    ItemVal>>
|| {ItemId, ItemVal} <- ItemChangeL]))/binary >>
;

%% id=3  
pkg_msg(?MSG_ITEM_BUCKET_ASSETS, {BucketType, AssetsInfoL}) ->
<<?MSG_ITEM_BUCKET_ASSETS:16, 
BucketType,
    (length(AssetsInfoL)):16, (iolist_to_binary([<<
AssetsId:32,
    AssetsVal>>
|| {AssetsId, AssetsVal} <- AssetsInfoL]))/binary >>
;

%% id=4  
pkg_msg(?MSG_ITEM_BUCKET_ADD_ITEMS, {AddType, BucketType, ItemL}) ->
<<?MSG_ITEM_BUCKET_ADD_ITEMS:16, 
AddType,
    BucketType,
    (length(ItemL)):16, (iolist_to_binary([<<
Id:32,
    Bid:32,
    Pos,
    Qly,
    Qua:16,
    Bind,
    IsJd,
    SuitId:32,
    QhLev,
    Power:32,
    (length(ExtraAttr)):16, (iolist_to_binary([<<
ExtraModId,
    (length(Attr)):16, (iolist_to_binary([<<
AttrCode,
    AttrVal:32,
    AttrPer>>
|| {AttrCode, AttrVal, AttrPer} <- Attr]))/binary >>
|| {ExtraModId, Attr} <- ExtraAttr]))/binary ,
    (length(GemInfo)):16, (iolist_to_binary([<<GemId:32>> || GemId <- GemInfo]))/binary,
    (length(ItemEx)):16, (iolist_to_binary([<<
Key,
    Val:32>>
|| {Key, Val} <- ItemEx]))/binary ,
    (length(SkillChanges)):16, (iolist_to_binary([<<Id:32>> || Id <- SkillChanges]))/binary,
    (length(JDListMax)):16, (iolist_to_binary([<<Max:32>> || Max <- JDListMax]))/binary,
    (length(JDListMin)):16, (iolist_to_binary([<<Min:32>> || Min <- JDListMin]))/binary,
    Fumo:16,
    (length(FumoAttrList)):16, (iolist_to_binary([<<
TypeId,
    AttrId,
    AttrVal:32>>
|| {TypeId, AttrId, AttrVal} <- FumoAttrList]))/binary >>
|| {Id, Bid, Pos, Qly, Qua, Bind, IsJd, SuitId, QhLev, Power, ExtraAttr, GemInfo, ItemEx, SkillChanges, JDListMax, JDListMin, Fumo, FumoAttrList} <- ItemL]))/binary >>
;

%% id=5  
pkg_msg(?MSG_ITEM_BUCKET_ALL_INFO, {BucketType, UnlockSize, UT, ItemL}) ->
<<?MSG_ITEM_BUCKET_ALL_INFO:16, 
BucketType,
    UnlockSize:32,
    UT:32,
    (length(ItemL)):16, (iolist_to_binary([<<
Id:32,
    Bid:32,
    Pos,
    Qly,
    Qua:16,
    Bind,
    IsJd,
    SuitId:32,
    QhLev,
    Power:32,
    (length(ExtraAttr)):16, (iolist_to_binary([<<
ExtraModId,
    (length(Attr)):16, (iolist_to_binary([<<
AttrCode,
    AttrVal:32,
    AttrPer>>
|| {AttrCode, AttrVal, AttrPer} <- Attr]))/binary >>
|| {ExtraModId, Attr} <- ExtraAttr]))/binary ,
    (length(GemInfo)):16, (iolist_to_binary([<<GemId:32>> || GemId <- GemInfo]))/binary,
    (length(ItemEx)):16, (iolist_to_binary([<<
Key,
    Val:32>>
|| {Key, Val} <- ItemEx]))/binary ,
    (length(SkillChanges)):16, (iolist_to_binary([<<Id:32>> || Id <- SkillChanges]))/binary,
    (length(JDListMax)):16, (iolist_to_binary([<<Max:32>> || Max <- JDListMax]))/binary,
    (length(JDListMin)):16, (iolist_to_binary([<<Min:32>> || Min <- JDListMin]))/binary,
    Fumo:16,
    (length(FumoAttrList)):16, (iolist_to_binary([<<
TypeId,
    AttrId,
    AttrVal:32>>
|| {TypeId, AttrId, AttrVal} <- FumoAttrList]))/binary >>
|| {Id, Bid, Pos, Qly, Qua, Bind, IsJd, SuitId, QhLev, Power, ExtraAttr, GemInfo, ItemEx, SkillChanges, JDListMax, JDListMin, Fumo, FumoAttrList} <- ItemL]))/binary >>
;

%% id=6  
pkg_msg(?MSG_ITEM_BUCKET_DEL, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_DEL:16, 
ReplyNum>>
;

%% id=7  
pkg_msg(?MSG_ITEM_BUCKET_SORT, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_SORT:16, 
ReplyNum>>
;

%% id=8  
pkg_msg(?MSG_ITEM_BUCKET_MOVE, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_MOVE:16, 
ReplyNum>>
;

%% id=9  
pkg_msg(?MSG_ITEM_BUCKET_SPLIT, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_SPLIT:16, 
ReplyNum>>
;

%% id=10  
pkg_msg(?MSG_ITEM_BUCKET_MOVE_CROSS, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_MOVE_CROSS:16, 
ReplyNum>>
;

%% id=12  
pkg_msg(?MSG_ITEM_BUCKET_UNLOCK, {ReplyNum, BucketType, UnlockType, UT}) ->
<<?MSG_ITEM_BUCKET_UNLOCK:16, 
ReplyNum,
    BucketType,
    UnlockType,
    UT:32>>
;

%% id=13  
pkg_msg(?MSG_ITEM_BUCKET_MERGE, {ReplyNum}) ->
<<?MSG_ITEM_BUCKET_MERGE:16, 
ReplyNum>>
;

%% id=14  
pkg_msg(?MSG_ITEM_USE, {ReplyNum}) ->
<<?MSG_ITEM_USE:16, 
ReplyNum>>
;

%% id=16  
pkg_msg(?MSG_GIFT_ITEM_USE, {Item_list}) ->
<<?MSG_GIFT_ITEM_USE:16, 
(length(Item_list)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Item_list]))/binary >>
;

%% id=15  
pkg_msg(?MSG_ITEM_NEW_ADD_NUM, {AddNum}) ->
<<?MSG_ITEM_NEW_ADD_NUM:16, 
AddNum:32>>
;

%% id=17  
pkg_msg(?MSG_ITEM_UNBIND, {ReplyNum, ItemId}) ->
<<?MSG_ITEM_UNBIND:16, 
ReplyNum,
    ItemId:32>>
;

%% id=18  
pkg_msg(?MSG_ITEM_NEW_ITEM, {ItemList}) ->
<<?MSG_ITEM_NEW_ITEM:16, 
(length(ItemList)):16, (iolist_to_binary([<<ItemId:64>> || ItemId <- ItemList]))/binary>>
;

%% id=19  
pkg_msg(?MSG_GOODS_COMPOUND, {ReplyNum}) ->
<<?MSG_GOODS_COMPOUND:16, 
ReplyNum>>
;
pkg_msg(Id, _) -> ok.



%% id = 3  
unpkg_msg(?MSG_ITEM_BUCKET_ASSETS, Acc0) ->
<<BucketType,
Acc1/binary>> = Acc0,
 {{BucketType}, Acc1};

%% id = 5  
unpkg_msg(?MSG_ITEM_BUCKET_ALL_INFO, Acc0) ->
<<BucketType,
Acc1/binary>> = Acc0,
 {{BucketType}, Acc1};

%% id = 6  
unpkg_msg(?MSG_ITEM_BUCKET_DEL, Acc0) ->
<<BucketType,
ItemId:32,
Acc1/binary>> = Acc0,
 {{BucketType,ItemId}, Acc1};

%% id = 7  
unpkg_msg(?MSG_ITEM_BUCKET_SORT, Acc0) ->
<<BucketType,
Acc1/binary>> = Acc0,
 {{BucketType}, Acc1};

%% id = 8  
unpkg_msg(?MSG_ITEM_BUCKET_MOVE, Acc0) ->
<<BucketType,
Id:32,
Pos,
Acc1/binary>> = Acc0,
 {{BucketType,Id,Pos}, Acc1};

%% id = 9  
unpkg_msg(?MSG_ITEM_BUCKET_SPLIT, Acc0) ->
<<BucketType,
Id:32,
Count:16,
Acc1/binary>> = Acc0,
 {{BucketType,Id,Count}, Acc1};

%% id = 10  
unpkg_msg(?MSG_ITEM_BUCKET_MOVE_CROSS, Acc0) ->
<<SBucketType,
Id:32,
DBucketType,
Pos,
Acc1/binary>> = Acc0,
 {{SBucketType,Id,DBucketType,Pos}, Acc1};

%% id = 12  
unpkg_msg(?MSG_ITEM_BUCKET_UNLOCK, Acc0) ->
<<BucketType,
UnlockType,
Acc1/binary>> = Acc0,
 {{BucketType,UnlockType}, Acc1};

%% id = 13  
unpkg_msg(?MSG_ITEM_BUCKET_MERGE, Acc0) ->
<<BucketType,
SItemId:32,
DItemId:32,
Acc1/binary>> = Acc0,
 {{BucketType,SItemId,DItemId}, Acc1};

%% id = 14  
unpkg_msg(?MSG_ITEM_USE, Acc0) ->
<<ItemId:32,
ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemId,ItemCount}, Acc1};

%% id = 16  
unpkg_msg(?MSG_GIFT_ITEM_USE, Acc0) ->
<<ItemId:32,
ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemId,ItemCount}, Acc1};

%% id = 17  
unpkg_msg(?MSG_ITEM_UNBIND, Acc0) ->
<<ItemId:32,
Acc1/binary>> = Acc0,
 {{ItemId}, Acc1};

%% id = 19  
unpkg_msg(?MSG_GOODS_COMPOUND, Acc0) ->
<<ItemBid:32,
ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemBid,ItemCount}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_ITEM_BUCKET_PUSH_DEL_IDS) -> <<"MSG_ITEM_BUCKET_PUSH_DEL_IDS">>; %% high 3, id 1
to_s(?MSG_ITEM_BUCKET_PUSH_CHG) -> <<"MSG_ITEM_BUCKET_PUSH_CHG">>; %% high 3, id 2
to_s(?MSG_ITEM_BUCKET_ASSETS) -> <<"MSG_ITEM_BUCKET_ASSETS">>; %% high 3, id 3
to_s(?MSG_ITEM_BUCKET_ADD_ITEMS) -> <<"MSG_ITEM_BUCKET_ADD_ITEMS">>; %% high 3, id 4
to_s(?MSG_ITEM_BUCKET_ALL_INFO) -> <<"MSG_ITEM_BUCKET_ALL_INFO">>; %% high 3, id 5
to_s(?MSG_ITEM_BUCKET_DEL) -> <<"MSG_ITEM_BUCKET_DEL">>; %% high 3, id 6
to_s(?MSG_ITEM_BUCKET_SORT) -> <<"MSG_ITEM_BUCKET_SORT">>; %% high 3, id 7
to_s(?MSG_ITEM_BUCKET_MOVE) -> <<"MSG_ITEM_BUCKET_MOVE">>; %% high 3, id 8
to_s(?MSG_ITEM_BUCKET_SPLIT) -> <<"MSG_ITEM_BUCKET_SPLIT">>; %% high 3, id 9
to_s(?MSG_ITEM_BUCKET_MOVE_CROSS) -> <<"MSG_ITEM_BUCKET_MOVE_CROSS">>; %% high 3, id 10
to_s(?MSG_ITEM_BUCKET_UNLOCK) -> <<"MSG_ITEM_BUCKET_UNLOCK">>; %% high 3, id 12
to_s(?MSG_ITEM_BUCKET_MERGE) -> <<"MSG_ITEM_BUCKET_MERGE">>; %% high 3, id 13
to_s(?MSG_ITEM_USE) -> <<"MSG_ITEM_USE">>; %% high 3, id 14
to_s(?MSG_GIFT_ITEM_USE) -> <<"MSG_GIFT_ITEM_USE">>; %% high 3, id 16
to_s(?MSG_ITEM_NEW_ADD_NUM) -> <<"MSG_ITEM_NEW_ADD_NUM">>; %% high 3, id 15
to_s(?MSG_ITEM_UNBIND) -> <<"MSG_ITEM_UNBIND">>; %% high 3, id 17
to_s(?MSG_ITEM_NEW_ITEM) -> <<"MSG_ITEM_NEW_ITEM">>; %% high 3, id 18
to_s(?MSG_GOODS_COMPOUND) -> <<"MSG_GOODS_COMPOUND">>; %% high 3, id 19
to_s(_) -> <<"unknown msg">>.
