%% Auto generated by sproto from item.sproto
%% Don't edit it.

-define(MSG_ITEM_BUCKET_PUSH_DEL_IDS, 769). %% hight:3 id1
-define(MSG_ITEM_BUCKET_PUSH_CHG, 770). %% hight:3 id2
-define(MSG_ITEM_BUCKET_ASSETS, 771). %% hight:3 id3
-define(MSG_ITEM_BUCKET_ADD_ITEMS, 772). %% hight:3 id4
-define(MSG_ITEM_BUCKET_ALL_INFO, 773). %% hight:3 id5
-define(MSG_ITEM_BUCKET_DEL, 774). %% hight:3 id6
-define(MSG_ITEM_BUCKET_SORT, 775). %% hight:3 id7
-define(MSG_ITEM_BUCKET_MOVE, 776). %% hight:3 id8
-define(MSG_ITEM_BUCKET_SPLIT, 777). %% hight:3 id9
-define(MSG_ITEM_BUCKET_MOVE_CROSS, 778). %% hight:3 id10
-define(MSG_ITEM_BUCKET_ONE_KEY_MOVE_CROSS, 779). %% hight:3 id11
-define(MSG_ITEM_BUCKET_UNLOCK, 780). %% hight:3 id12
-define(MSG_ITEM_BUCKET_MERGE, 781). %% hight:3 id13
-define(MSG_ITEM_USE, 782). %% hight:3 id14
-define(MSG_GIFT_ITEM_USE, 784). %% hight:3 id16
-define(MSG_ITEM_NEW_ADD_NUM, 783). %% hight:3 id15
-define(MSG_ITEM_UNBIND, 785). %% hight:3 id17
-define(MSG_ITEM_NEW_ITEM, 786). %% hight:3 id18
-define(MSG_GOODS_COMPOUND, 787). %% hight:3 id19
