%% Auto generated by sproto from login_prize.sproto
%% Don't edit it.

-define(MSG_LOGIN_DAY_DATA_SC, 7937). %% hight:31 id1
-define(MSG_ROLL_ITEM_DATA_SC, 7938). %% hight:31 id2
-define(MSG_ROLL_ITEM_UPDATE_SC, 7939). %% hight:31 id3
-define(MSG_SIGNIN_REWARD_CS, 7940). %% hight:31 id4
-define(MSG_LEVEL_REWARD_CS, 7941). %% hight:31 id5
-define(MSG_ROLL_LOTTERY_CS, 7942). %% hight:31 id6
-define(MSG_SIGN, 7943). %% hight:31 id7
-define(MSG_SUPPLY_SIGN, 7944). %% hight:31 id8
-define(MSG_PUSH_SIGN_INFO, 7945). %% hight:31 id9
