%% Auto generated by sproto from mail.sproto
%% Don't edit it.

-module(mail_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("mail_sproto.hrl").

%% id=1  
pkg_msg(?MSG_MAIL_LOAD_ALL, {MailInfoL, NewTime}) ->
<<?MSG_MAIL_LOAD_ALL:16, 
(length(MailInfoL)):16, (iolist_to_binary([<<
Id:64,
    From_id:64,
    (byte_size(From)), From/binary,
    (byte_size(Subject)):16, Subject/binary,
    (byte_size(Body)):16, Body/binary,
    Cdate:32,
    Auto_delete_sec:32,
    (length(ItemInfoL)):16, (iolist_to_binary([<<
Id:32,
    Bid:32,
    Pos,
    Qly,
    Qua:16,
    Bind,
    IsJd,
    SuitId:32,
    QhLev,
    Power:32,
    (length(ExtraAttr)):16, (iolist_to_binary([<<
ExtraModId,
    (length(Attr)):16, (iolist_to_binary([<<
AttrCode,
    AttrVal:32,
    AttrPer>>
|| {AttrCode, AttrVal, AttrPer} <- Attr]))/binary >>
|| {ExtraModId, Attr} <- ExtraAttr]))/binary ,
    (length(GemInfo)):16, (iolist_to_binary([<<GemId:32>> || GemId <- GemInfo]))/binary,
    (length(ItemEx)):16, (iolist_to_binary([<<
Key,
    Val:32>>
|| {Key, Val} <- ItemEx]))/binary ,
    (length(SkillChanges)):16, (iolist_to_binary([<<Id:32>> || Id <- SkillChanges]))/binary,
    (length(JDListMax)):16, (iolist_to_binary([<<Max:32>> || Max <- JDListMax]))/binary,
    (length(JDListMin)):16, (iolist_to_binary([<<Min:32>> || Min <- JDListMin]))/binary,
    Fumo:16,
    (length(FumoAttrList)):16, (iolist_to_binary([<<
TypeId,
    AttrId,
    AttrVal:32>>
|| {TypeId, AttrId, AttrVal} <- FumoAttrList]))/binary >>
|| {Id, Bid, Pos, Qly, Qua, Bind, IsJd, SuitId, QhLev, Power, ExtraAttr, GemInfo, ItemEx, SkillChanges, JDListMax, JDListMin, Fumo, FumoAttrList} <- ItemInfoL]))/binary ,
    (length(AssetsL)):16, (iolist_to_binary([<<
AssetsId:32,
    AssetsVal:32>>
|| {AssetsId, AssetsVal} <- AssetsL]))/binary ,
    ExState,
    State>>
|| {Id, From_id, From, Subject, Body, Cdate, Auto_delete_sec, ItemInfoL, AssetsL, ExState, State} <- MailInfoL]))/binary ,
    NewTime:32>>
;

%% id=4  
pkg_msg(?MSG_MAIL_PUSH_DELETE, {DelMailIdL}) ->
<<?MSG_MAIL_PUSH_DELETE:16, 
(length(DelMailIdL)):16, (iolist_to_binary([<<DelMailId:64>> || DelMailId <- DelMailIdL]))/binary>>
;

%% id=5  
pkg_msg(?MSG_MAIL_GET_PRIZE, {ReplyNum}) ->
<<?MSG_MAIL_GET_PRIZE:16, 
ReplyNum>>
;

%% id=6  
pkg_msg(?MSG_MAIL_ONE_KEY_GET_PRIZE, {MailId}) ->
<<?MSG_MAIL_ONE_KEY_GET_PRIZE:16, 
MailId:64>>
;

%% id=7  
pkg_msg(?MSG_MAIL_NEW, {MailInfo}) ->
<<?MSG_MAIL_NEW:16, 
(begin {Id, From_id, From, Subject, Body, Cdate, Auto_delete_sec, ItemInfoL, AssetsL, ExState, State}=MailInfo, <<
Id:64,
    From_id:64,
    (byte_size(From)), From/binary,
    (byte_size(Subject)):16, Subject/binary,
    (byte_size(Body)):16, Body/binary,
    Cdate:32,
    Auto_delete_sec:32,
    (length(ItemInfoL)):16, (iolist_to_binary([<<
Id:32,
    Bid:32,
    Pos,
    Qly,
    Qua:16,
    Bind,
    IsJd,
    SuitId:32,
    QhLev,
    Power:32,
    (length(ExtraAttr)):16, (iolist_to_binary([<<
ExtraModId,
    (length(Attr)):16, (iolist_to_binary([<<
AttrCode,
    AttrVal:32,
    AttrPer>>
|| {AttrCode, AttrVal, AttrPer} <- Attr]))/binary >>
|| {ExtraModId, Attr} <- ExtraAttr]))/binary ,
    (length(GemInfo)):16, (iolist_to_binary([<<GemId:32>> || GemId <- GemInfo]))/binary,
    (length(ItemEx)):16, (iolist_to_binary([<<
Key,
    Val:32>>
|| {Key, Val} <- ItemEx]))/binary ,
    (length(SkillChanges)):16, (iolist_to_binary([<<Id:32>> || Id <- SkillChanges]))/binary,
    (length(JDListMax)):16, (iolist_to_binary([<<Max:32>> || Max <- JDListMax]))/binary,
    (length(JDListMin)):16, (iolist_to_binary([<<Min:32>> || Min <- JDListMin]))/binary,
    Fumo:16,
    (length(FumoAttrList)):16, (iolist_to_binary([<<
TypeId,
    AttrId,
    AttrVal:32>>
|| {TypeId, AttrId, AttrVal} <- FumoAttrList]))/binary >>
|| {Id, Bid, Pos, Qly, Qua, Bind, IsJd, SuitId, QhLev, Power, ExtraAttr, GemInfo, ItemEx, SkillChanges, JDListMax, JDListMin, Fumo, FumoAttrList} <- ItemInfoL]))/binary ,
    (length(AssetsL)):16, (iolist_to_binary([<<
AssetsId:32,
    AssetsVal:32>>
|| {AssetsId, AssetsVal} <- AssetsL]))/binary ,
    ExState,
    State>>
 end)/binary>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_MAIL_LOAD_ALL, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_MAIL_READ, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 3  
unpkg_msg(?MSG_MAIL_DELETE, Acc0) ->
<<L__delIdL:16, Acc1/binary>> = Acc0,
{DelIdL, Acc2} = 
unpkg_list_u64(L__delIdL, Acc1, []),
{{DelIdL}, Acc2};

%% id = 5  
unpkg_msg(?MSG_MAIL_GET_PRIZE, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 6  
unpkg_msg(?MSG_MAIL_ONE_KEY_GET_PRIZE, Acc0) ->
{{}, Acc0};

%% id = 8  
unpkg_msg(?MSG_MAIL_NEW_TIME, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_MAIL_LOAD_ALL) -> <<"MSG_MAIL_LOAD_ALL">>; %% high 6, id 1
to_s(?MSG_MAIL_READ) -> <<"MSG_MAIL_READ">>; %% high 6, id 2
to_s(?MSG_MAIL_DELETE) -> <<"MSG_MAIL_DELETE">>; %% high 6, id 3
to_s(?MSG_MAIL_PUSH_DELETE) -> <<"MSG_MAIL_PUSH_DELETE">>; %% high 6, id 4
to_s(?MSG_MAIL_GET_PRIZE) -> <<"MSG_MAIL_GET_PRIZE">>; %% high 6, id 5
to_s(?MSG_MAIL_ONE_KEY_GET_PRIZE) -> <<"MSG_MAIL_ONE_KEY_GET_PRIZE">>; %% high 6, id 6
to_s(?MSG_MAIL_NEW) -> <<"MSG_MAIL_NEW">>; %% high 6, id 7
to_s(?MSG_MAIL_NEW_TIME) -> <<"MSG_MAIL_NEW_TIME">>; %% high 6, id 8
to_s(_) -> <<"unknown msg">>.
unpkg_list_u64(0, Bin, List) -> {lists:reverse(List), Bin};
unpkg_list_u64(Len, Bin, List) -> 
 <<E:64,Bin1/binary>> = Bin,
unpkg_list_u64(Len-1, Bin1, [E|List]).
