%% Auto generated by sproto from mail.sproto
%% Don't edit it.

-define(MSG_MAIL_LOAD_ALL, 1537). %% hight:6 id1
-define(MSG_MAIL_READ, 1538). %% hight:6 id2
-define(MSG_MAIL_DELETE, 1539). %% hight:6 id3
-define(MSG_MAIL_PUSH_DELETE, 1540). %% hight:6 id4
-define(MSG_MAIL_GET_PRIZE, 1541). %% hight:6 id5
-define(MSG_MAIL_ONE_KEY_GET_PRIZE, 1542). %% hight:6 id6
-define(MSG_MAIL_NEW, 1543). %% hight:6 id7
-define(MSG_MAIL_NEW_TIME, 1544). %% hight:6 id8
