%% Auto generated by sproto from main_instance.sproto
%% Don't edit it.

-module(main_instance_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("main_instance_sproto.hrl").

%% id=1  
pkg_msg(?MSG_MAIN_INSTANCE_INFO, {Info}) ->
<<?MSG_MAIN_INSTANCE_INFO:16, 
Info/binary>>
;

%% id=4  
pkg_msg(?MSG_MAIN_INSTANCE_CLEAN_TIMES, {PrizeList}) ->
<<?MSG_MAIN_INSTANCE_CLEAN_TIMES:16, 
(length(PrizeList)):16, (iolist_to_binary([<<
(length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
|| {PrizeInfo} <- PrizeList]))/binary >>
;

%% id=5  
pkg_msg(?MSG_MAIN_INSTANCE_CLEAN, {PrizeInfo}) ->
<<?MSG_MAIN_INSTANCE_CLEAN:16, 
(length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary >>
;

%% id=6  
pkg_msg(?MSG_MAIN_INSTANCE_COMPLETE, {Id, PassTimeSrc, Lianjicount, Shoujicount, ReliveNum, Fenshu, Coin, No1FenShu, No1Name, No1Job, SelfRank, CanGetPrize, PrizeInfo, Firstninestarpassprizeinfo, Lianjiprize, Shoujiprize, Passtimeprize, Reliveprize, CardItemList}) ->
<<?MSG_MAIN_INSTANCE_COMPLETE:16, 
Id:16,
    PassTimeSrc:32,
    Lianjicount:16,
    Shoujicount:16,
    ReliveNum:16,
    Fenshu:16,
    Coin:16,
    No1FenShu:16,
    (byte_size(No1Name)), No1Name/binary,
    No1Job,
    SelfRank,
    CanGetPrize,
    (length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary ,
    (length(Firstninestarpassprizeinfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Firstninestarpassprizeinfo]))/binary ,
    (length(Lianjiprize)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Lianjiprize]))/binary ,
    (length(Shoujiprize)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Shoujiprize]))/binary ,
    (length(Passtimeprize)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Passtimeprize]))/binary ,
    (length(Reliveprize)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Reliveprize]))/binary ,
    (length(CardItemList)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- CardItemList]))/binary >>
;

%% id=12  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_CREATE, {TeamId}) ->
<<?MSG_MAIN_INSTANCE_TEAM_CREATE:16, 
TeamId:32>>
;

%% id=13  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_LEAVE, {Id}) ->
<<?MSG_MAIN_INSTANCE_TEAM_LEAVE:16, 
Id:64>>
;

%% id=15  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_QUICK_JOIN, {Id, TeamId, MembersInfo}) ->
<<?MSG_MAIN_INSTANCE_TEAM_QUICK_JOIN:16, 
Id:16,
    TeamId:32,
    (length(MembersInfo)):16, (iolist_to_binary([<<
Id:64,
    (byte_size(Name)), Name/binary,
    Level,
    Combar_power:32,
    Carrer,
    Hp:32>>
|| {Id, Name, Level, Combar_power, Carrer, Hp} <- MembersInfo]))/binary >>
;

%% id=16  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_KICKOUT, {Id}) ->
<<?MSG_MAIN_INSTANCE_TEAM_KICKOUT:16, 
Id:64>>
;

%% id=17  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_MEMBER_JOIN, {JoinMemberInfo}) ->
<<?MSG_MAIN_INSTANCE_TEAM_MEMBER_JOIN:16, 
(begin {Id, Name, Level, Combar_power, Carrer, Hp}=JoinMemberInfo, <<
Id:64,
    (byte_size(Name)), Name/binary,
    Level,
    Combar_power:32,
    Carrer,
    Hp:32>>
 end)/binary>>
;

%% id=18  
pkg_msg(?MSG_MAIN_INSTANCE_TEAM_DISSOLVE, {}) ->
<<?MSG_MAIN_INSTANCE_TEAM_DISSOLVE:16>> 
;

%% id=19  
pkg_msg(?MSG_MAIN_INSTANCE_LAYER_COMPLETE, {}) ->
<<?MSG_MAIN_INSTANCE_LAYER_COMPLETE:16>> 
;

%% id=20  
pkg_msg(?MSG_MAIN_INSTANCE_RAND_START, {ReplyNum, Id}) ->
<<?MSG_MAIN_INSTANCE_RAND_START:16, 
ReplyNum,
    Id:16>>
;

%% id=22  
pkg_msg(?MSG_MAIN_INSTANCE_DOOR_ACTIVE, {X, Y, Target}) ->
<<?MSG_MAIN_INSTANCE_DOOR_ACTIVE:16, 
X:16,
    Y:16,
    Target:16>>
;

%% id=41  
pkg_msg(?MSG_MAIN_INSTANCE_RANK_INFO, {Info}) ->
<<?MSG_MAIN_INSTANCE_RANK_INFO:16, 
Info/binary>>
;

%% id=42  
pkg_msg(?MSG_MAIN_INSTANCE_SHOP, {}) ->
<<?MSG_MAIN_INSTANCE_SHOP:16>> 
;

%% id=43  
pkg_msg(?MSG_MAIN_INSTANCE_CHAPTER_STAR_PRIZE, {}) ->
<<?MSG_MAIN_INSTANCE_CHAPTER_STAR_PRIZE:16>> 
;

%% id=44  
pkg_msg(?MSG_MAIN_INSTANCE_TRANSPORT_DOOR_ACTIVE, {DoorId}) ->
<<?MSG_MAIN_INSTANCE_TRANSPORT_DOOR_ACTIVE:16, 
DoorId:16>>
;

%% id=45  
pkg_msg(?MSG_MAIN_INSTANCE_MEMBERS_INFO, {Id, Hp, MaxHp, Level}) ->
<<?MSG_MAIN_INSTANCE_MEMBERS_INFO:16, 
Id:64,
    Hp:32,
    MaxHp:32,
    Level>>
;

%% id=46  
pkg_msg(?MSG_MAIN_INSTANCE_NOTIFY_COMPLETE, {}) ->
<<?MSG_MAIN_INSTANCE_NOTIFY_COMPLETE:16>> 
;

%% id=47  
pkg_msg(?MSG_MAIN_INSTANCE_NOTIFY_TEAM_MASTER, {Id}) ->
<<?MSG_MAIN_INSTANCE_NOTIFY_TEAM_MASTER:16, 
Id:64>>
;

%% id=48  
pkg_msg(?MSG_MAIN_INSTANCE_ID_INFO, {PlayerId, AgentId}) ->
<<?MSG_MAIN_INSTANCE_ID_INFO:16, 
PlayerId:64,
    AgentId:16/signed>>
;

%% id=49  
pkg_msg(?MSG_MAIN_INSTANCE_CHALLENGE_INFO, {Info}) ->
<<?MSG_MAIN_INSTANCE_CHALLENGE_INFO:16, 
Info/binary>>
;

%% id=50  
pkg_msg(?MSG_MAIN_INSTANCE_BUY_CHALLENGE_TIMES, {Id, Buy_challenge_times, Remain_challenge_times}) ->
<<?MSG_MAIN_INSTANCE_BUY_CHALLENGE_TIMES:16, 
Id:16,
    Buy_challenge_times:16,
    Remain_challenge_times:16>>
;

%% id=51  
pkg_msg(?MSG_PUSH_ROOM_CLEAN_LIST, {Clean_room_list}) ->
<<?MSG_PUSH_ROOM_CLEAN_LIST:16, 
(length(Clean_room_list)):16, (iolist_to_binary([<<Id:16>> || Id <- Clean_room_list]))/binary>>
;

%% id=52  
pkg_msg(?MSG_MAIN_INSTANCE_OPEN_CARD, {Card}) ->
<<?MSG_MAIN_INSTANCE_OPEN_CARD:16, 
(length(Card)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- Card]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_MAIN_INSTANCE_SINGLE_START, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 3  
unpkg_msg(?MSG_MAIN_INSTANCE_ENTER_NEXT, Acc0) ->
{{}, Acc0};

%% id = 4  
unpkg_msg(?MSG_MAIN_INSTANCE_CLEAN_TIMES, Acc0) ->
<<Id:16,
Times,
Open_card,
Acc1/binary>> = Acc0,
 {{Id,Times,Open_card}, Acc1};

%% id = 5  
unpkg_msg(?MSG_MAIN_INSTANCE_CLEAN, Acc0) ->
<<Id:16,
Open_card,
Acc1/binary>> = Acc0,
 {{Id,Open_card}, Acc1};

%% id = 12  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_CREATE, Acc0) ->
<<Id:16,
IsAllowMidwayJoin,
Acc1/binary>> = Acc0,
 {{Id,IsAllowMidwayJoin}, Acc1};

%% id = 13  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_LEAVE, Acc0) ->
{{}, Acc0};

%% id = 14  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_START, Acc0) ->
{{}, Acc0};

%% id = 15  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_QUICK_JOIN, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 16  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_KICKOUT, Acc0) ->
<<Id:64,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 18  
unpkg_msg(?MSG_MAIN_INSTANCE_TEAM_DISSOLVE, Acc0) ->
{{}, Acc0};

%% id = 20  
unpkg_msg(?MSG_MAIN_INSTANCE_RAND_START, Acc0) ->
<<ItemId:32,
Acc1/binary>> = Acc0,
 {{ItemId}, Acc1};

%% id = 23  
unpkg_msg(?MSG_INSTANCE_ENTER_NEXT_LAYER, Acc0) ->
<<Target:16,
Is_last_scene,
Acc1/binary>> = Acc0,
 {{Target,Is_last_scene}, Acc1};

%% id = 40  
unpkg_msg(?MSG_MAIN_INSTANCE_CLIENT_START, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 41  
unpkg_msg(?MSG_MAIN_INSTANCE_RANK_INFO, Acc0) ->
<<Sceneid:16,
Index,
Count,
Acc1/binary>> = Acc0,
 {{Sceneid,Index,Count}, Acc1};

%% id = 42  
unpkg_msg(?MSG_MAIN_INSTANCE_SHOP, Acc0) ->
<<Goodsid:32,
Count,
Acc1/binary>> = Acc0,
 {{Goodsid,Count}, Acc1};

%% id = 43  
unpkg_msg(?MSG_MAIN_INSTANCE_CHAPTER_STAR_PRIZE, Acc0) ->
<<City_id,
Sub,
Is_get_index,
Acc1/binary>> = Acc0,
 {{City_id,Sub,Is_get_index}, Acc1};

%% id = 50  
unpkg_msg(?MSG_MAIN_INSTANCE_BUY_CHALLENGE_TIMES, Acc0) ->
<<Id:16,
Num:16,
Acc1/binary>> = Acc0,
 {{Id,Num}, Acc1};

%% id = 52  
unpkg_msg(?MSG_MAIN_INSTANCE_OPEN_CARD, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_MAIN_INSTANCE_INFO) -> <<"MSG_MAIN_INSTANCE_INFO">>; %% high 16, id 1
to_s(?MSG_MAIN_INSTANCE_SINGLE_START) -> <<"MSG_MAIN_INSTANCE_SINGLE_START">>; %% high 16, id 2
to_s(?MSG_MAIN_INSTANCE_ENTER_NEXT) -> <<"MSG_MAIN_INSTANCE_ENTER_NEXT">>; %% high 16, id 3
to_s(?MSG_MAIN_INSTANCE_CLEAN_TIMES) -> <<"MSG_MAIN_INSTANCE_CLEAN_TIMES">>; %% high 16, id 4
to_s(?MSG_MAIN_INSTANCE_CLEAN) -> <<"MSG_MAIN_INSTANCE_CLEAN">>; %% high 16, id 5
to_s(?MSG_MAIN_INSTANCE_COMPLETE) -> <<"MSG_MAIN_INSTANCE_COMPLETE">>; %% high 16, id 6
to_s(?MSG_MAIN_INSTANCE_TEAM_CREATE) -> <<"MSG_MAIN_INSTANCE_TEAM_CREATE">>; %% high 16, id 12
to_s(?MSG_MAIN_INSTANCE_TEAM_LEAVE) -> <<"MSG_MAIN_INSTANCE_TEAM_LEAVE">>; %% high 16, id 13
to_s(?MSG_MAIN_INSTANCE_TEAM_START) -> <<"MSG_MAIN_INSTANCE_TEAM_START">>; %% high 16, id 14
to_s(?MSG_MAIN_INSTANCE_TEAM_QUICK_JOIN) -> <<"MSG_MAIN_INSTANCE_TEAM_QUICK_JOIN">>; %% high 16, id 15
to_s(?MSG_MAIN_INSTANCE_TEAM_KICKOUT) -> <<"MSG_MAIN_INSTANCE_TEAM_KICKOUT">>; %% high 16, id 16
to_s(?MSG_MAIN_INSTANCE_TEAM_MEMBER_JOIN) -> <<"MSG_MAIN_INSTANCE_TEAM_MEMBER_JOIN">>; %% high 16, id 17
to_s(?MSG_MAIN_INSTANCE_TEAM_DISSOLVE) -> <<"MSG_MAIN_INSTANCE_TEAM_DISSOLVE">>; %% high 16, id 18
to_s(?MSG_MAIN_INSTANCE_LAYER_COMPLETE) -> <<"MSG_MAIN_INSTANCE_LAYER_COMPLETE">>; %% high 16, id 19
to_s(?MSG_MAIN_INSTANCE_RAND_START) -> <<"MSG_MAIN_INSTANCE_RAND_START">>; %% high 16, id 20
to_s(?MSG_MAIN_INSTANCE_DOOR_ACTIVE) -> <<"MSG_MAIN_INSTANCE_DOOR_ACTIVE">>; %% high 16, id 22
to_s(?MSG_INSTANCE_ENTER_NEXT_LAYER) -> <<"MSG_INSTANCE_ENTER_NEXT_LAYER">>; %% high 16, id 23
to_s(?MSG_MAIN_INSTANCE_CLIENT_START) -> <<"MSG_MAIN_INSTANCE_CLIENT_START">>; %% high 16, id 40
to_s(?MSG_MAIN_INSTANCE_RANK_INFO) -> <<"MSG_MAIN_INSTANCE_RANK_INFO">>; %% high 16, id 41
to_s(?MSG_MAIN_INSTANCE_SHOP) -> <<"MSG_MAIN_INSTANCE_SHOP">>; %% high 16, id 42
to_s(?MSG_MAIN_INSTANCE_CHAPTER_STAR_PRIZE) -> <<"MSG_MAIN_INSTANCE_CHAPTER_STAR_PRIZE">>; %% high 16, id 43
to_s(?MSG_MAIN_INSTANCE_TRANSPORT_DOOR_ACTIVE) -> <<"MSG_MAIN_INSTANCE_TRANSPORT_DOOR_ACTIVE">>; %% high 16, id 44
to_s(?MSG_MAIN_INSTANCE_MEMBERS_INFO) -> <<"MSG_MAIN_INSTANCE_MEMBERS_INFO">>; %% high 16, id 45
to_s(?MSG_MAIN_INSTANCE_NOTIFY_COMPLETE) -> <<"MSG_MAIN_INSTANCE_NOTIFY_COMPLETE">>; %% high 16, id 46
to_s(?MSG_MAIN_INSTANCE_NOTIFY_TEAM_MASTER) -> <<"MSG_MAIN_INSTANCE_NOTIFY_TEAM_MASTER">>; %% high 16, id 47
to_s(?MSG_MAIN_INSTANCE_ID_INFO) -> <<"MSG_MAIN_INSTANCE_ID_INFO">>; %% high 16, id 48
to_s(?MSG_MAIN_INSTANCE_CHALLENGE_INFO) -> <<"MSG_MAIN_INSTANCE_CHALLENGE_INFO">>; %% high 16, id 49
to_s(?MSG_MAIN_INSTANCE_BUY_CHALLENGE_TIMES) -> <<"MSG_MAIN_INSTANCE_BUY_CHALLENGE_TIMES">>; %% high 16, id 50
to_s(?MSG_PUSH_ROOM_CLEAN_LIST) -> <<"MSG_PUSH_ROOM_CLEAN_LIST">>; %% high 16, id 51
to_s(?MSG_MAIN_INSTANCE_OPEN_CARD) -> <<"MSG_MAIN_INSTANCE_OPEN_CARD">>; %% high 16, id 52
to_s(_) -> <<"unknown msg">>.
