%% Auto generated by sproto from mall.sproto
%% Don't edit it.

-module(mall_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("mall_sproto.hrl").

%% id=1  
pkg_msg(?MSG_MALL_SHOPPING, {Reply_num}) ->
<<?MSG_MALL_SHOPPING:16, 
Reply_num>>
;

%% id=2  
pkg_msg(?MSG_MALL_TIME_INFOS, {Time_infos}) ->
<<?MSG_MALL_TIME_INFOS:16, 
(length(Time_infos)):16, (iolist_to_binary([<<
Shopping_id:32,
    Time:64>>
|| {Shopping_id, Time} <- Time_infos]))/binary >>
;

%% id=3  
pkg_msg(?MSG_MALL_ID_INFOS, {Item_infos}) ->
<<?MSG_MALL_ID_INFOS:16, 
(length(Item_infos)):16, (iolist_to_binary([<<
Shopping_id:32,
    Number:16>>
|| {Shopping_id, Number} <- Item_infos]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_MALL_SHOPPING, Acc0) ->
<<Shopping_id:32,
Item_num:16,
Acc1/binary>> = Acc0,
 {{Shopping_id,Item_num}, Acc1};

%% id = 2  
unpkg_msg(?MSG_MALL_TIME_INFOS, Acc0) ->
<<L__shopping_ids:16, Acc1/binary>> = Acc0,
{Shopping_ids, Acc2} = 
unpkg_list_u32(L__shopping_ids, Acc1, []),
{{Shopping_ids}, Acc2};

%% id = 3  
unpkg_msg(?MSG_MALL_ID_INFOS, Acc0) ->
<<L__shopping_ids:16, Acc1/binary>> = Acc0,
{Shopping_ids, Acc2} = 
unpkg_list_u32(L__shopping_ids, Acc1, []),
{{Shopping_ids}, Acc2};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_MALL_SHOPPING) -> <<"MSG_MALL_SHOPPING">>; %% high 26, id 1
to_s(?MSG_MALL_TIME_INFOS) -> <<"MSG_MALL_TIME_INFOS">>; %% high 26, id 2
to_s(?MSG_MALL_ID_INFOS) -> <<"MSG_MALL_ID_INFOS">>; %% high 26, id 3
to_s(_) -> <<"unknown msg">>.
unpkg_list_u32(0, Bin, List) -> {lists:reverse(List), Bin};
unpkg_list_u32(Len, Bin, List) -> 
 <<E:32,Bin1/binary>> = Bin,
unpkg_list_u32(Len-1, Bin1, [E|List]).
