%% Auto generated by sproto from mall.sproto
%% Don't edit it.

-define(MSG_MALL_SHOPPING, 6657). %% hight:26 id1
-define(MSG_MALL_TIME_INFOS, 6658). %% hight:26 id2
-define(MSG_MALL_ID_INFOS, 6659). %% hight:26 id3
