%% Auto generated by sproto from nine_lottery.sproto
%% Don't edit it.

-define(MSG_NINE_LOTTERY_INFO, 12289). %% hight:48 id1
-define(MSG_NINE_LOTTERY_GET_PRIZE, 12290). %% hight:48 id2
-define(MSG_NINE_LOTTERY_RECORD, 12291). %% hight:48 id3
