%% Auto generated by sproto from nine_lottery.sproto
%% Don't edit it.

-module(nine_lottery_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("nine_lottery_sproto.hrl").

%% id=1  
pkg_msg(?MSG_NINE_LOTTERY_INFO, {LotteryList}) ->
<<?MSG_NINE_LOTTERY_INFO:16, 
(length(LotteryList)):16, (iolist_to_binary([<<
Idx,
    (length(Rewards)):16, (iolist_to_binary([<<
ItemId:32,
    Num:32>>
|| {ItemId, Num} <- Rewards]))/binary ,
    Count:16>>
|| {Idx, Rewards, Count} <- LotteryList]))/binary >>
;

%% id=2  
pkg_msg(?MSG_NINE_LOTTERY_GET_PRIZE, {Idx, Rewards}) ->
<<?MSG_NINE_LOTTERY_GET_PRIZE:16, 
Idx,
    (length(Rewards)):16, (iolist_to_binary([<<
ItemId:32,
    Num:32,
    IsSuper>>
|| {ItemId, Num, IsSuper} <- Rewards]))/binary >>
;

%% id=3  
pkg_msg(?MSG_NINE_LOTTERY_RECORD, {PageData}) ->
<<?MSG_NINE_LOTTERY_RECORD:16, 
(length(PageData)):16, (iolist_to_binary([<<
Time:64,
    Id:64,
    (byte_size(Name)), Name/binary,
    (length(ItemTpL)):16, (iolist_to_binary([<<
ItemBid:32,
    Count:32>>
|| {ItemBid, Count} <- ItemTpL]))/binary >>
|| {Time, Id, Name, ItemTpL} <- PageData]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_NINE_LOTTERY_INFO, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_NINE_LOTTERY_GET_PRIZE, Acc0) ->
<<Count,
Acc1/binary>> = Acc0,
 {{Count}, Acc1};

%% id = 3  
unpkg_msg(?MSG_NINE_LOTTERY_RECORD, Acc0) ->
<<Type,
Acc1/binary>> = Acc0,
 {{Type}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_NINE_LOTTERY_INFO) -> <<"MSG_NINE_LOTTERY_INFO">>; %% high 48, id 1
to_s(?MSG_NINE_LOTTERY_GET_PRIZE) -> <<"MSG_NINE_LOTTERY_GET_PRIZE">>; %% high 48, id 2
to_s(?MSG_NINE_LOTTERY_RECORD) -> <<"MSG_NINE_LOTTERY_RECORD">>; %% high 48, id 3
to_s(_) -> <<"unknown msg">>.
