%% Auto generated by sproto from open_server_happy.sproto
%% Don't edit it.

-module(open_server_happy_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("open_server_happy_sproto.hrl").

%% id=1  
pkg_msg(?MSG_OPEN_SERVER_HAPPY_INIT_CLIENT, {Day, TaskList}) ->
<<?MSG_OPEN_SERVER_HAPPY_INIT_CLIENT:16, 
Day,
    (length(TaskList)):16, (iolist_to_binary([<<
TaskId:16,
    TaskNum,
    FinishTaskNum,
    IsGetPrize>>
|| {TaskId, TaskNum, FinishTaskNum, IsGetPrize} <- TaskList]))/binary >>
;

%% id=2  
pkg_msg(?MSG_GET_TASK_PRIZE, {ReplyNum}) ->
<<?MSG_GET_TASK_PRIZE:16, 
ReplyNum>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_GET_TASK_PRIZE, Acc0) ->
<<Day,
TaskId:16,
Acc1/binary>> = Acc0,
 {{Day,TaskId}, Acc1};

%% id = 3  
unpkg_msg(?MSG_OPEN_SERVER_HAPPY_BOARD, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_OPEN_SERVER_HAPPY_INIT_CLIENT) -> <<"MSG_OPEN_SERVER_HAPPY_INIT_CLIENT">>; %% high 46, id 1
to_s(?MSG_GET_TASK_PRIZE) -> <<"MSG_GET_TASK_PRIZE">>; %% high 46, id 2
to_s(?MSG_OPEN_SERVER_HAPPY_BOARD) -> <<"MSG_OPEN_SERVER_HAPPY_BOARD">>; %% high 46, id 3
to_s(_) -> <<"unknown msg">>.
