%% Auto generated by sproto from open_server_happy.sproto
%% Don't edit it.

-define(MSG_OPEN_SERVER_HAPPY_INIT_CLIENT, 11777). %% hight:46 id1
-define(MSG_GET_TASK_PRIZE, 11778). %% hight:46 id2
-define(MSG_OPEN_SERVER_HAPPY_BOARD, 11779). %% hight:46 id3
