%% Auto generated by sproto from pet.sproto
%% Don't edit it.

-define(MSG_PET_LIST, 4865). %% hight:19 id1
-define(MSG_PET_SEAL, 4866). %% hight:19 id2
-define(MSG_PET_SKILL_STUDY, 4867). %% hight:19 id3
-define(MSG_PET_SKILL_FORGET, 4868). %% hight:19 id4
-define(MSG_PET_SKILL_UPLEVEL, 4869). %% hight:19 id5
-define(MSG_PET_ADVANCE, 4870). %% hight:19 id6
-define(MSG_PET_UPLEVEL, 4871). %% hight:19 id7
-define(MSG_PET_TREASURE, 4872). %% hight:19 id8
-define(MSG_PET_CANCEL_TREASURE, 4873). %% hight:19 id9
-define(MSG_PET_SKILL_POS_OPEN, 4874). %% hight:19 id10
-define(MSG_PET_STATE, 4875). %% hight:19 id11
-define(MSG_PET_ATTR_CHANGE, 4876). %% hight:19 id12
-define(MSG_PET_TREASURE_LIST, 4877). %% hight:19 id13
-define(MSG_PET_TREASURE_LOG_LIST, 4878). %% hight:19 id14
-define(MSG_PUSH_PET_TREASURE_FINISH, 4879). %% hight:19 id15
-define(MSG_PET_EGG_DATA, 4880). %% hight:19 id16
