%% Auto generated by sproto from pet_new.sproto
%% Don't edit it.

-define(MSG_PET_NEW_PET_LIST, 11009). %% hight:43 id1
-define(MSG_PET_NEW_UPGRADE, 11010). %% hight:43 id2
-define(MSG_PET_NEW_ADVANCE, 11011). %% hight:43 id3
-define(MSG_PET_NEW_UPGRADE_SKILL, 11012). %% hight:43 id4
-define(MSG_PET_NEW_DEL, 11013). %% hight:43 id5
-define(MSG_PET_NEW_UPDATE_AND_ADD, 11014). %% hight:43 id6
-define(MSG_PET_NEW_PASSIVITY_SKILL_INLAY, 11015). %% hight:43 id7
-define(MSG_PET_NEW_SHANGZHEN, 11016). %% hight:43 id8
-define(MSG_PET_NEW_GAN, 11017). %% hight:43 id9
-define(MSG_PET_NEW_FENGYIN, 11018). %% hight:43 id10
-define(MSG_PET_NEW_SHANGZHEN_LIST, 11019). %% hight:43 id11
