%% Auto generated by sproto from phase_achievement.sproto
%% Don't edit it.

-define(MSG_PHASE_ACHIEVEMENT_LIST, 9985). %% hight:39 id1
-define(MSG_PHASE_ACHIEVEMENT_PROGRESS, 9986). %% hight:39 id2
-define(MSG_PHASE_ACHIEVEMENT_GET_PRIZE, 9987). %% hight:39 id3
