%% Auto generated by sproto from rank.sproto
%% Don't edit it.

-define(MSG_RANK_LEV, 6145). %% hight:24 id1
-define(MSG_RANK_POWER, 6146). %% hight:24 id2
-define(MSG_RANK_ARENA, 6147). %% hight:24 id3
-define(MSG_RANK_PET, 6148). %% hight:24 id4
-define(MSG_RANK_GUILD, 6149). %% hight:24 id5
-define(MSG_RANK_FRIEND, 6150). %% hight:24 id6
-define(MSG_RANK_ACCOMPLISHMENT, 6151). %% hight:24 id7
-define(MSG_RANK_SHENMO, 6152). %% hight:24 id8
-define(MSG_RANK_DAILY_1, 6153). %% hight:24 id9
-define(MSG_RANK_DAILY_2, 6154). %% hight:24 id10
-define(MSG_RANK_ABYSS, 6155). %% hight:24 id11
-define(MSG_RANK_SKY_KILL_MONSTER, 6156). %% hight:24 id12
-define(MSG_RANK_SKY_KILL_PLAYER, 6157). %% hight:24 id13
-define(MSG_RANK_SUIT, 6158). %% hight:24 id14
-define(MSG_RANK_GUILD_BOSS, 6159). %% hight:24 id15
-define(MSG_RANK_GWGC, 6160). %% hight:24 id16
-define(MSG_RANK_BOUNTY, 6161). %% hight:24 id17
-define(MSG_RANK_PET_NEW, 6162). %% hight:24 id18
-define(MSG_RANK_SUIT_NEW, 6163). %% hight:24 id19
-define(MSG_RANK_RIDE, 6164). %% hight:24 id20
-define(MSG_RANK_DAILY_4, 6165). %% hight:24 id21
-define(MSG_RANK_DAILY_5, 6166). %% hight:24 id22
