%% Auto generated by sproto from recharge_reward.sproto
%% Don't edit it.

-module(recharge_reward_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("recharge_reward_sproto.hrl").

%% id=1  
pkg_msg(?MSG_RECHARGE_REWARD_INFO, {Recharge, Reward_status}) ->
<<?MSG_RECHARGE_REWARD_INFO:16, 
Recharge:32,
    (length(Reward_status)):16, (iolist_to_binary([<<
Id:16,
    Status>>
|| {Id, Status} <- Reward_status]))/binary >>
;

%% id=2  
pkg_msg(?MSG_RECHARGE_REWARD_GET_PRIZE, {Replynum}) ->
<<?MSG_RECHARGE_REWARD_GET_PRIZE:16, 
Replynum>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_RECHARGE_REWARD_GET_PRIZE, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_RECHARGE_REWARD_INFO) -> <<"MSG_RECHARGE_REWARD_INFO">>; %% high 49, id 1
to_s(?MSG_RECHARGE_REWARD_GET_PRIZE) -> <<"MSG_RECHARGE_REWARD_GET_PRIZE">>; %% high 49, id 2
to_s(_) -> <<"unknown msg">>.
