%% Auto generated by sproto from ride.sproto
%% Don't edit it.

-module(ride_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("ride_sproto.hrl").

%% id=1  
pkg_msg(?MSG_RIDE_LIST, {Ride_list}) ->
<<?MSG_RIDE_LIST:16, 
(length(Ride_list)):16, (iolist_to_binary([<<
Ride_id:16,
    Level>>
|| {Ride_id, Level} <- Ride_list]))/binary >>
;

%% id=2  
pkg_msg(?MSG_RIDE_DATA, {Ride}) ->
<<?MSG_RIDE_DATA:16, 
(begin {Ride_id, Level}=Ride, <<
Ride_id:16,
    Level>>
 end)/binary>>
;

%% id=3  
pkg_msg(?MSG_RIDE_SOUL_DATA, {Ride_soul}) ->
<<?MSG_RIDE_SOUL_DATA:16, 
(begin {Id, Exp, Happy, Grade, Out_cd, Out_num}=Ride_soul, <<
Id:16,
    Exp:16,
    Happy:16,
    Grade:16,
    Out_cd:32,
    Out_num>>
 end)/binary>>
;

%% id=4  
pkg_msg(?MSG_RIDE_ACTIVATE, {Ride_id}) ->
<<?MSG_RIDE_ACTIVATE:16, 
Ride_id:16>>
;

%% id=5  
pkg_msg(?MSG_RIDE_EVOLVE, {Ride_id, Level}) ->
<<?MSG_RIDE_EVOLVE:16, 
Ride_id:16,
    Level>>
;

%% id=6  
pkg_msg(?MSG_RIDE_UPLEVEL, {Exp, Level}) ->
<<?MSG_RIDE_UPLEVEL:16, 
Exp:16,
    Level>>
;

%% id=7  
pkg_msg(?MSG_RIDE_ADVANCE, {Grade}) ->
<<?MSG_RIDE_ADVANCE:16, 
Grade:16>>
;

%% id=8  
pkg_msg(?MSG_RIDE_CHANGE, {PrizeInfo, Out_cd, Out_num}) ->
<<?MSG_RIDE_CHANGE:16, 
(length(PrizeInfo)):16, (iolist_to_binary([<<
ItemId:32,
    ItemCount:32>>
|| {ItemId, ItemCount} <- PrizeInfo]))/binary ,
    Out_cd:32,
    Out_num>>
;

%% id=9  
pkg_msg(?MSG_RIDE_FEED, {Happy}) ->
<<?MSG_RIDE_FEED:16, 
Happy:16>>
;

%% id=10  
pkg_msg(?MSG_RIDE_TORIDE, {RideId}) ->
<<?MSG_RIDE_TORIDE:16, 
RideId:16>>
;

%% id=11  
pkg_msg(?MSG_RIDE_HAPPY, {Happy}) ->
<<?MSG_RIDE_HAPPY:16, 
Happy:16>>
;

%% id=12  
pkg_msg(?MSG_RIDE_UPLEVEL_NEW, {Exp, Level, Double_count, Use_item_count}) ->
<<?MSG_RIDE_UPLEVEL_NEW:16, 
Exp:16,
    Level,
    Double_count:16,
    Use_item_count:16>>
;

%% id=13  
pkg_msg(?MSG_RIDE_FEED_NEW, {Happy, Use_item_count}) ->
<<?MSG_RIDE_FEED_NEW:16, 
Happy:16,
    Use_item_count:16>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_RIDE_LIST, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_RIDE_DATA, Acc0) ->
<<Ride_id:16,
Acc1/binary>> = Acc0,
 {{Ride_id}, Acc1};

%% id = 3  
unpkg_msg(?MSG_RIDE_SOUL_DATA, Acc0) ->
{{}, Acc0};

%% id = 4  
unpkg_msg(?MSG_RIDE_ACTIVATE, Acc0) ->
<<Ride_id:16,
Acc1/binary>> = Acc0,
 {{Ride_id}, Acc1};

%% id = 5  
unpkg_msg(?MSG_RIDE_EVOLVE, Acc0) ->
<<Ride_id:16,
Acc1/binary>> = Acc0,
 {{Ride_id}, Acc1};

%% id = 6  
unpkg_msg(?MSG_RIDE_UPLEVEL, Acc0) ->
{{}, Acc0};

%% id = 7  
unpkg_msg(?MSG_RIDE_ADVANCE, Acc0) ->
{{}, Acc0};

%% id = 8  
unpkg_msg(?MSG_RIDE_CHANGE, Acc0) ->
{{}, Acc0};

%% id = 9  
unpkg_msg(?MSG_RIDE_FEED, Acc0) ->
{{}, Acc0};

%% id = 10  
unpkg_msg(?MSG_RIDE_TORIDE, Acc0) ->
<<RideId:16,
Acc1/binary>> = Acc0,
 {{RideId}, Acc1};

%% id = 11  
unpkg_msg(?MSG_RIDE_HAPPY, Acc0) ->
{{}, Acc0};

%% id = 12  
unpkg_msg(?MSG_RIDE_UPLEVEL_NEW, Acc0) ->
<<ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemCount}, Acc1};

%% id = 13  
unpkg_msg(?MSG_RIDE_FEED_NEW, Acc0) ->
<<ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemCount}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_RIDE_LIST) -> <<"MSG_RIDE_LIST">>; %% high 42, id 1
to_s(?MSG_RIDE_DATA) -> <<"MSG_RIDE_DATA">>; %% high 42, id 2
to_s(?MSG_RIDE_SOUL_DATA) -> <<"MSG_RIDE_SOUL_DATA">>; %% high 42, id 3
to_s(?MSG_RIDE_ACTIVATE) -> <<"MSG_RIDE_ACTIVATE">>; %% high 42, id 4
to_s(?MSG_RIDE_EVOLVE) -> <<"MSG_RIDE_EVOLVE">>; %% high 42, id 5
to_s(?MSG_RIDE_UPLEVEL) -> <<"MSG_RIDE_UPLEVEL">>; %% high 42, id 6
to_s(?MSG_RIDE_ADVANCE) -> <<"MSG_RIDE_ADVANCE">>; %% high 42, id 7
to_s(?MSG_RIDE_CHANGE) -> <<"MSG_RIDE_CHANGE">>; %% high 42, id 8
to_s(?MSG_RIDE_FEED) -> <<"MSG_RIDE_FEED">>; %% high 42, id 9
to_s(?MSG_RIDE_TORIDE) -> <<"MSG_RIDE_TORIDE">>; %% high 42, id 10
to_s(?MSG_RIDE_HAPPY) -> <<"MSG_RIDE_HAPPY">>; %% high 42, id 11
to_s(?MSG_RIDE_UPLEVEL_NEW) -> <<"MSG_RIDE_UPLEVEL_NEW">>; %% high 42, id 12
to_s(?MSG_RIDE_FEED_NEW) -> <<"MSG_RIDE_FEED_NEW">>; %% high 42, id 13
to_s(_) -> <<"unknown msg">>.
