%% Auto generated by sproto from ride.sproto
%% Don't edit it.

-define(MSG_RIDE_LIST, 10753). %% hight:42 id1
-define(MSG_RIDE_DATA, 10754). %% hight:42 id2
-define(MSG_RIDE_SOUL_DATA, 10755). %% hight:42 id3
-define(MSG_RIDE_ACTIVATE, 10756). %% hight:42 id4
-define(MSG_RIDE_EVOLVE, 10757). %% hight:42 id5
-define(MSG_RIDE_UPLEVEL, 10758). %% hight:42 id6
-define(MSG_RIDE_ADVANCE, 10759). %% hight:42 id7
-define(MSG_RIDE_CHANGE, 10760). %% hight:42 id8
-define(MSG_RIDE_FEED, 10761). %% hight:42 id9
-define(MSG_RIDE_TORIDE, 10762). %% hight:42 id10
-define(MSG_RIDE_HAPPY, 10763). %% hight:42 id11
-define(MSG_RIDE_UPLEVEL_NEW, 10764). %% hight:42 id12
-define(MSG_RIDE_FEED_NEW, 10765). %% hight:42 id13
