%% Auto generated by sproto from scene.sproto
%% Don't edit it.

-module(scene_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("scene_sproto.hrl").

%% id=1  
pkg_msg(?MSG_SCENE_PLAYER_ENTER_REQUEST, {SceneId, PosX, PosY, Dir, Flag}) ->
<<?MSG_SCENE_PLAYER_ENTER_REQUEST:16, 
SceneId:16,
    PosX:16,
    PosY:16,
    Dir,
    Flag>>
;

%% id=2  
pkg_msg(?MSG_SCENE_PLAYER_ENTER, {Idx, Party}) ->
<<?MSG_SCENE_PLAYER_ENTER:16, 
Idx:16/signed,
    Party:16>>
;

%% id=3  
pkg_msg(?MSG_SCENE_ENTER_VIEW, {PlayerAgents, MonAgents}) ->
<<?MSG_SCENE_ENTER_VIEW:16, 
(length(PlayerAgents)):16, (iolist_to_binary([<<
Idx:16/signed,
    Dic,
    PosX:16,
    PosY:16,
    PosH:16,
    (begin {XSpeed, YSpeed, HSpeed}=MoveSpeed, <<
XSpeed:16,
    YSpeed:16,
    HSpeed:16>>
 end)/binary,
    (begin {XOffset, YOffset, HOffset}=MoveVector, <<
XOffset/signed,
    YOffset/signed,
    HOffset/signed>>
 end)/binary,
    Hp:32,
    Max_hp:32,
    Mp:32,
    Max_mp:32,
    Other/binary,
    (length(Efts)):16, (iolist_to_binary([<<Id:16>> || Id <- Efts]))/binary,
    CardId:32,
    RideId:16,
    Party:16,
    Ai_flag>>
|| {Idx, Dic, PosX, PosY, PosH, MoveSpeed, MoveVector, Hp, Max_hp, Mp, Max_mp, Other, Efts, CardId, RideId, Party, Ai_flag} <- PlayerAgents]))/binary ,
    (length(MonAgents)):16, (iolist_to_binary([<<
Idx:16/signed,
    Dic,
    PosX:16,
    PosY:16,
    PosH:16,
    (begin {XSpeed, YSpeed, HSpeed}=MoveSpeed, <<
XSpeed:16,
    YSpeed:16,
    HSpeed:16>>
 end)/binary,
    (begin {XOffset, YOffset, HOffset}=MoveVector, <<
XOffset/signed,
    YOffset/signed,
    HOffset/signed>>
 end)/binary,
    Level:16,
    Hp:32,
    Max_hp:32,
    Other/binary,
    Party:16,
    Ai_flag>>
|| {Idx, Dic, PosX, PosY, PosH, MoveSpeed, MoveVector, Level, Hp, Max_hp, Other, Party, Ai_flag} <- MonAgents]))/binary >>
;

%% id=4  
pkg_msg(?MSG_SCENE_LEAVE_VIEW, {IdxList}) ->
<<?MSG_SCENE_LEAVE_VIEW:16, 
IdxList/binary>>
;

%% id=24  
pkg_msg(?MSG_SCENE_PLAYER_SWITCH_MOVE_MODE, {Idx, Mode}) ->
<<?MSG_SCENE_PLAYER_SWITCH_MOVE_MODE:16, 
Idx:16/signed,
    Mode>>
;

%% id=5  
pkg_msg(?MSG_SCENE_MOVE, {Idx, PosX, PosY, PosH, MoveVector, SpeedVector}) ->
<<?MSG_SCENE_MOVE:16, 
Idx:16/signed,
    PosX:16,
    PosY:16,
    PosH:16,
    (begin {XOffset, YOffset, HOffset}=MoveVector, <<
XOffset/signed,
    YOffset/signed,
    HOffset/signed>>
 end)/binary,
    (begin {XSpeed, YSpeed, HSpeed}=SpeedVector, <<
XSpeed:16,
    YSpeed:16,
    HSpeed:16>>
 end)/binary>>
;

%% id=6  
pkg_msg(?MSG_SCENE_MOVE_STOP, {Idx, PosX, PosY, PosH}) ->
<<?MSG_SCENE_MOVE_STOP:16, 
Idx:16/signed,
    PosX:16,
    PosY:16,
    PosH:16>>
;

%% id=7  
pkg_msg(?MSG_SCENE_JUMP, {Idx, Dir, PosX, PosY, PosZ}) ->
<<?MSG_SCENE_JUMP:16, 
Idx:16/signed,
    Dir,
    PosX:16,
    PosY:16,
    PosZ:16>>
;

%% id=8  
pkg_msg(?MSG_SCENE_RELEASE_SKILL, {Idx, SkillId, SpellId, Dir, PosX, PosY, PosZ}) ->
<<?MSG_SCENE_RELEASE_SKILL:16, 
Idx:16/signed,
    SkillId:32,
    SpellId:32,
    Dir,
    PosX:16,
    PosY:16,
    PosZ:16>>
;

%% id=9  
pkg_msg(?MSG_SCENE_RELEASE_SKILL_JUDGE, {Info}) ->
<<?MSG_SCENE_RELEASE_SKILL_JUDGE:16, 
Info/binary>>
;

%% id=10  
pkg_msg(?MSG_SCENE_RELIVE, {Idx, PosX, PosY}) ->
<<?MSG_SCENE_RELIVE:16, 
Idx:16/signed,
    PosX:16,
    PosY:16>>
;

%% id=36  
pkg_msg(?MSG_SCENE_CLIENT_RELIVE, {ReplyNum}) ->
<<?MSG_SCENE_CLIENT_RELIVE:16, 
ReplyNum>>
;

%% id=37  
pkg_msg(?MSG_SCENE_CLIENT_ADD_HP_MP, {ReplyNum}) ->
<<?MSG_SCENE_CLIENT_ADD_HP_MP:16, 
ReplyNum>>
;

%% id=11  
pkg_msg(?MSG_SCENE_DROP_ITEMS, {Items}) ->
<<?MSG_SCENE_DROP_ITEMS:16, 
(length(Items)):16, (iolist_to_binary([<<
DropId:16,
    PosX:16,
    PosY:16,
    ItemId:32>>
|| {DropId, PosX, PosY, ItemId} <- Items]))/binary >>
;

%% id=12  
pkg_msg(?MSG_SCENE_DROP_ITEMS_REMOVE, {DropId}) ->
<<?MSG_SCENE_DROP_ITEMS_REMOVE:16, 
DropId:16>>
;

%% id=13  
pkg_msg(?MSG_SCENE_AGENT_DATA_CHANGE, {Idx, DataType, Value}) ->
<<?MSG_SCENE_AGENT_DATA_CHANGE:16, 
Idx:16/signed,
    DataType,
    Value:32>>
;

%% id=14  
pkg_msg(?MSG_SCENE_ADD_BUFF, {Idx, BuffId, TimetampMsec}) ->
<<?MSG_SCENE_ADD_BUFF:16, 
Idx:16/signed,
    BuffId:32,
    TimetampMsec:32>>
;

%% id=15  
pkg_msg(?MSG_SCENE_DEL_BUFF, {Idx, BuffId}) ->
<<?MSG_SCENE_DEL_BUFF:16, 
Idx:16/signed,
    BuffId:32>>
;

%% id=27  
pkg_msg(?MSG_SCENE_LARGE_MOVE, {SceneId, PosX, PosY}) ->
<<?MSG_SCENE_LARGE_MOVE:16, 
SceneId:16,
    PosX:16,
    PosY:16>>
;

%% id=30  
pkg_msg(?MSG_SCENE_ADD_HP_MP, {}) ->
<<?MSG_SCENE_ADD_HP_MP:16>> 
;

%% id=32  
pkg_msg(?MSG_SCENE_DEVICE_RELEASE_SKILL, {DeviceId}) ->
<<?MSG_SCENE_DEVICE_RELEASE_SKILL:16, 
DeviceId>>
;

%% id=33  
pkg_msg(?MSG_SCENE_DEVICE_RELEASE_SKILL_JUDGE, {Info}) ->
<<?MSG_SCENE_DEVICE_RELEASE_SKILL_JUDGE:16, 
Info/binary>>
;

%% id=34  
pkg_msg(?MSG_SCENE_DEVICE_DESTROY, {DeviceId}) ->
<<?MSG_SCENE_DEVICE_DESTROY:16, 
DeviceId>>
;

%% id=42  
pkg_msg(?MSG_SCENE_CLIENT_DROP_BY_MONSTER, {Client_id, Drop_list}) ->
<<?MSG_SCENE_CLIENT_DROP_BY_MONSTER:16, 
Client_id:16,
    (length(Drop_list)):16, (iolist_to_binary([<<
Drop_id,
    Item_bid:32,
    Item_quality,
    Item_num:32>>
|| {Drop_id, Item_bid, Item_quality, Item_num} <- Drop_list]))/binary >>
;

%% id=43  
pkg_msg(?MSG_SCENE_CLIENT_PICKUP_DROP, {}) ->
<<?MSG_SCENE_CLIENT_PICKUP_DROP:16>> 
;

%% id=60  
pkg_msg(?MSG_SCENE_PLAY_EFFECTS, {Effects_id, Msg}) ->
<<?MSG_SCENE_PLAY_EFFECTS:16, 
Effects_id,
    (byte_size(Msg)), Msg/binary>>
;

%% id=61  
pkg_msg(?MSG_CREATE_DIG_RES_SC, {Res}) ->
<<?MSG_CREATE_DIG_RES_SC:16, 
(length(Res)):16, (iolist_to_binary([<<
Bid:32>>
|| {Bid} <- Res]))/binary >>
;

%% id=62  
pkg_msg(?MSG_DELETE_DIG_RES_SC, {Res}) ->
<<?MSG_DELETE_DIG_RES_SC:16, 
(length(Res)):16, (iolist_to_binary([<<
Uid:32>>
|| {Uid} <- Res]))/binary >>
;

%% id=63  
pkg_msg(?MSG_SCENE_AGENT_UPDATE_EQU, {Agent_id, Career, Equ_1_bid, Equ_2_bid, Equ_3_bid, Equ_4_bid, Equ_5_bid, Equ_6_bid, Equ_7_bid, Equ_8_bid, Equ_9_bid, Equ_10_bid}) ->
<<?MSG_SCENE_AGENT_UPDATE_EQU:16, 
Agent_id:16/signed,
    Career,
    Equ_1_bid:32,
    Equ_2_bid:32,
    Equ_3_bid:32,
    Equ_4_bid:32,
    Equ_5_bid:32,
    Equ_6_bid:32,
    Equ_7_bid:32,
    Equ_8_bid:32,
    Equ_9_bid:32,
    Equ_10_bid:32>>
;

%% id=64  
pkg_msg(?MSG_SCENE_AGENT_UPDATE_TITLE, {Agent_id, Title_id}) ->
<<?MSG_SCENE_AGENT_UPDATE_TITLE:16, 
Agent_id:16/signed,
    Title_id:16>>
;

%% id=65  
pkg_msg(?MSG_SCENE_AGENT_UPDATE_GUILD, {Agent_id, Guild_name, Boder_id, Totem_id}) ->
<<?MSG_SCENE_AGENT_UPDATE_GUILD:16, 
Agent_id:16/signed,
    (byte_size(Guild_name)), Guild_name/binary,
    Boder_id,
    Totem_id>>
;

%% id=66  
pkg_msg(?MSG_SCENE_EFFECT_UPDATE, {Agent_id, Effect}) ->
<<?MSG_SCENE_EFFECT_UPDATE:16, 
Agent_id:16/signed,
    (length(Effect)):16, (iolist_to_binary([<<Ids:16>> || Ids <- Effect]))/binary>>
;

%% id=67  
pkg_msg(?MSG_SCENE_INS_RESET_HP_CD, {}) ->
<<?MSG_SCENE_INS_RESET_HP_CD:16>> 
;

%% id=68  
pkg_msg(?MSG_SCENE_INS_RESET_USE_COUNT, {Count}) ->
<<?MSG_SCENE_INS_RESET_USE_COUNT:16, 
Count>>
;

%% id=69  
pkg_msg(?MSG_SCENE_SHAPESHIFT_UPDATE, {Agent_id, Career, CardId}) ->
<<?MSG_SCENE_SHAPESHIFT_UPDATE:16, 
Agent_id:16/signed,
    Career,
    CardId:32>>
;

%% id=70  
pkg_msg(?MSG_SCENE_AREA_STATE, {Scene_id, X, Y, Z, W, H, Can_walk}) ->
<<?MSG_SCENE_AREA_STATE:16, 
Scene_id:32,
    X:32,
    Y:32,
    Z:32,
    W:32,
    H:32,
    Can_walk>>
;

%% id=71  
pkg_msg(?MSG_SCENE_RELEASE_SKILL_END, {}) ->
<<?MSG_SCENE_RELEASE_SKILL_END:16>> 
;

%% id=72  
pkg_msg(?MSG_SCENE_BREAK_SKILL, {}) ->
<<?MSG_SCENE_BREAK_SKILL:16>> 
;

%% id=73  
pkg_msg(?MSG_SCENE_SEND_LOCK_AREA, {X1, X2}) ->
<<?MSG_SCENE_SEND_LOCK_AREA:16, 
X1:16,
    X2:16>>
;

%% id=74  
pkg_msg(?MSG_SCENE_SEND_TALKS_ID, {Agent_id, TalksId}) ->
<<?MSG_SCENE_SEND_TALKS_ID:16, 
Agent_id:16/signed,
    TalksId:32>>
;

%% id=75  
pkg_msg(?MSG_SCENE_RIDE_UPDATE, {Agent_id, RideId}) ->
<<?MSG_SCENE_RIDE_UPDATE:16, 
Agent_id:16/signed,
    RideId:16>>
;

%% id=76  
pkg_msg(?MSG_SCENE_AGENT_DIE, {Agent_id}) ->
<<?MSG_SCENE_AGENT_DIE:16, 
Agent_id:16/signed>>
;

%% id=77  
pkg_msg(?MSG_SCENE_MONSTER_AGENT_SYNC, {}) ->
<<?MSG_SCENE_MONSTER_AGENT_SYNC:16>> 
;

%% id=81  
pkg_msg(?MSG_SCENE_RESET_VIEW, {PlayerAgents, MonAgents}) ->
<<?MSG_SCENE_RESET_VIEW:16, 
(length(PlayerAgents)):16, (iolist_to_binary([<<
Idx:16/signed,
    Dic,
    PosX:16,
    PosY:16,
    PosH:16,
    (begin {XSpeed, YSpeed, HSpeed}=MoveSpeed, <<
XSpeed:16,
    YSpeed:16,
    HSpeed:16>>
 end)/binary,
    (begin {XOffset, YOffset, HOffset}=MoveVector, <<
XOffset/signed,
    YOffset/signed,
    HOffset/signed>>
 end)/binary,
    Hp:32,
    Max_hp:32,
    Mp:32,
    Max_mp:32,
    Other/binary,
    (length(Efts)):16, (iolist_to_binary([<<Id:16>> || Id <- Efts]))/binary,
    CardId:32,
    RideId:16,
    Party:16,
    Ai_flag>>
|| {Idx, Dic, PosX, PosY, PosH, MoveSpeed, MoveVector, Hp, Max_hp, Mp, Max_mp, Other, Efts, CardId, RideId, Party, Ai_flag} <- PlayerAgents]))/binary ,
    (length(MonAgents)):16, (iolist_to_binary([<<
Idx:16/signed,
    Dic,
    PosX:16,
    PosY:16,
    PosH:16,
    (begin {XSpeed, YSpeed, HSpeed}=MoveSpeed, <<
XSpeed:16,
    YSpeed:16,
    HSpeed:16>>
 end)/binary,
    (begin {XOffset, YOffset, HOffset}=MoveVector, <<
XOffset/signed,
    YOffset/signed,
    HOffset/signed>>
 end)/binary,
    Level:16,
    Hp:32,
    Max_hp:32,
    Other/binary,
    Party:16,
    Ai_flag>>
|| {Idx, Dic, PosX, PosY, PosH, MoveSpeed, MoveVector, Level, Hp, Max_hp, Other, Party, Ai_flag} <- MonAgents]))/binary >>
;

%% id=82  
pkg_msg(?MSG_SCENE_BUFF_DAMAGE, {AgentId, HitHp, ResHp}) ->
<<?MSG_SCENE_BUFF_DAMAGE:16, 
AgentId:16/signed,
    HitHp:32,
    ResHp:32>>
;

%% id=83  
pkg_msg(?MSG_SCENE_MONSTER_GONGCHENG_LIST, {Info}) ->
<<?MSG_SCENE_MONSTER_GONGCHENG_LIST:16, 
(length(Info)):16, (iolist_to_binary([<<
Npcid:16,
    X:16,
    Y:16,
    Staus>>
|| {Npcid, X, Y, Staus} <- Info]))/binary >>
;

%% id=84  
pkg_msg(?MSG_SCENE_MONSTER_GONGCHENG_DELETE, {NpcId}) ->
<<?MSG_SCENE_MONSTER_GONGCHENG_DELETE:16, 
NpcId:16>>
;

%% id=85  
pkg_msg(?MSG_SCENE_MONSTER_GONGCHENG_DELETE_CHANGE_STATUS, {NpcId, Staus}) ->
<<?MSG_SCENE_MONSTER_GONGCHENG_DELETE_CHANGE_STATUS:16, 
NpcId:16,
    Staus>>
;

%% id=86  
pkg_msg(?MSG_SCENE_BROADCAST_ACTIVITY, {IsStart, ActivityId, BroadcastId}) ->
<<?MSG_SCENE_BROADCAST_ACTIVITY:16, 
IsStart,
    ActivityId,
    BroadcastId:16>>
;

%% id=87  
pkg_msg(?MSG_SCENE_NAVIGATION, {AgentId, PlayerId, Type, Npc_id}) ->
<<?MSG_SCENE_NAVIGATION:16, 
AgentId:16/signed,
    PlayerId:64,
    Type,
    Npc_id:32>>
;

%% id=88  
pkg_msg(?MSG_SCENE_DOUBLE_PRIZE_ACTIVITY, {ActivityInfo}) ->
<<?MSG_SCENE_DOUBLE_PRIZE_ACTIVITY:16, 
ActivityInfo/binary>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_SCENE_PLAYER_ENTER_REQUEST, Acc0) ->
<<SceneId:16,
Acc1/binary>> = Acc0,
 {{SceneId}, Acc1};

%% id = 2  
unpkg_msg(?MSG_SCENE_PLAYER_ENTER, Acc0) ->
{{}, Acc0};

%% id = 54  
unpkg_msg(?MSG_SCENE_GOTO_LAST_CITY, Acc0) ->
{{}, Acc0};

%% id = 22  
unpkg_msg(?MSG_SCENE_PLAYER_MOVE, Acc0) ->
<<Idx:16/signed,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
{MoveVector, Acc2} = unpkg_move_vector__(Acc1)
,
{{Idx,PosX,PosY,PosZ,MoveVector}, Acc2};

%% id = 24  
unpkg_msg(?MSG_SCENE_PLAYER_SWITCH_MOVE_MODE, Acc0) ->
<<Idx:16/signed,
Mode,
Acc1/binary>> = Acc0,
 {{Idx,Mode}, Acc1};

%% id = 23  
unpkg_msg(?MSG_SCENE_PLAYER_MOVE_STOP, Acc0) ->
<<Idx:16/signed,
PosX:16,
PosY:16,
PosH:16,
Acc1/binary>> = Acc0,
 {{Idx,PosX,PosY,PosH}, Acc1};

%% id = 7  
unpkg_msg(?MSG_SCENE_JUMP, Acc0) ->
<<Idx:16/signed,
Dir,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
 {{Idx,Dir,PosX,PosY,PosZ}, Acc1};

%% id = 8  
unpkg_msg(?MSG_SCENE_RELEASE_SKILL, Acc0) ->
<<Idx:16/signed,
SkillId:32,
SpellId:32,
Dir,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
 {{Idx,SkillId,SpellId,Dir,PosX,PosY,PosZ}, Acc1};

%% id = 10  
unpkg_msg(?MSG_SCENE_RELIVE, Acc0) ->
<<Type,
AgentIdx:16/signed,
Acc1/binary>> = Acc0,
 {{Type,AgentIdx}, Acc1};

%% id = 36  
unpkg_msg(?MSG_SCENE_CLIENT_RELIVE, Acc0) ->
{{}, Acc0};

%% id = 37  
unpkg_msg(?MSG_SCENE_CLIENT_ADD_HP_MP, Acc0) ->
{{}, Acc0};

%% id = 16  
unpkg_msg(?MSG_SCENE_DOOR_TRANSPORT, Acc0) ->
<<DoorId:16,
Acc1/binary>> = Acc0,
 {{DoorId}, Acc1};

%% id = 19  
unpkg_msg(?MSG_SCENE_PICKUP_DROP_ITEMS, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 30  
unpkg_msg(?MSG_SCENE_ADD_HP_MP, Acc0) ->
<<ButtonId,
Acc1/binary>> = Acc0,
 {{ButtonId}, Acc1};

%% id = 31  
unpkg_msg(?MSG_SCENE_RESIZE_VIEW, Acc0) ->
<<Wxr,
Wyr,
Acc1/binary>> = Acc0,
 {{Wxr,Wyr}, Acc1};

%% id = 35  
unpkg_msg(?MSG_SCENE_MONSTER_ENTER_SHOW, Acc0) ->
<<Id:16,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 39  
unpkg_msg(?MSG_SCENE_CLIENT_PLAYER_DIE, Acc0) ->
{{}, Acc0};

%% id = 40  
unpkg_msg(?MSG_SCENE_CLIENT_RELEASE_ANGER_SKILL, Acc0) ->
{{}, Acc0};

%% id = 41  
unpkg_msg(?MSG_SCENE_CLIENT_KILL_MONSTER, Acc0) ->
<<Monster_id:32,
Is_kill_self,
Acc1/binary>> = Acc0,
 {{Monster_id,Is_kill_self}, Acc1};

%% id = 42  
unpkg_msg(?MSG_SCENE_CLIENT_DROP_BY_MONSTER, Acc0) ->
<<Client_id:16,
Tag_id,
Acc1/binary>> = Acc0,
 {{Client_id,Tag_id}, Acc1};

%% id = 43  
unpkg_msg(?MSG_SCENE_CLIENT_PICKUP_DROP, Acc0) ->
<<Drop_id,
Acc1/binary>> = Acc0,
 {{Drop_id}, Acc1};

%% id = 51  
unpkg_msg(?MSG_SCENE_INSTANCE_CLIENT_KILL_MON, Acc0) ->
<<Is_ins_complete,
Wave_num:16,
Max_double_hit:16,
Shoujicount:16,
Passtime:16,
Relive_num:16,
AbyssPercent,
AbyssScore:32,
MonsterBin/binary>> = Acc0,
 {{Is_ins_complete,Wave_num,Max_double_hit,Shoujicount,Passtime,Relive_num,AbyssPercent,AbyssScore,MonsterBin}, <<>>};

%% id = 60  
unpkg_msg(?MSG_SCENE_PLAY_EFFECTS, Acc0) ->
{{}, Acc0};

%% id = 67  
unpkg_msg(?MSG_SCENE_INS_RESET_HP_CD, Acc0) ->
{{}, Acc0};

%% id = 68  
unpkg_msg(?MSG_SCENE_INS_RESET_USE_COUNT, Acc0) ->
{{}, Acc0};

%% id = 70  
unpkg_msg(?MSG_SCENE_AREA_STATE, Acc0) ->
{{}, Acc0};

%% id = 71  
unpkg_msg(?MSG_SCENE_RELEASE_SKILL_END, Acc0) ->
<<Idx:16/signed,
SkillId:32,
SpellId:32,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
 {{Idx,SkillId,SpellId,PosX,PosY,PosZ}, Acc1};

%% id = 72  
unpkg_msg(?MSG_SCENE_BREAK_SKILL, Acc0) ->
<<Idx:16/signed,
BreakerId:16/signed,
SkillId:32,
SpellId:32,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
 {{Idx,BreakerId,SkillId,SpellId,PosX,PosY,PosZ}, Acc1};

%% id = 77  
unpkg_msg(?MSG_SCENE_MONSTER_AGENT_SYNC, Acc0) ->
<<MonsterId:16/signed,
PosX:16,
PosY:16,
PosZ:16,
Acc1/binary>> = Acc0,
 {{MonsterId,PosX,PosY,PosZ}, Acc1};

%% id = 78  
unpkg_msg(?MSG_SCENE_AGENT_BE_HIT, Acc0) ->
<<AgentHitId:16/signed,
SkillId:32,
SkillDuanId:32,
Dir,
ReleaseX:16,
ReleaseY:16,
ReleaseZ:16,
L__agents:16, Acc1/binary>> = Acc0,
{Agents, Acc2} = unpkg_list_struct__(L__agents, Acc1, [], fun unpkg_ano_s__0/1)
,
{{AgentHitId,SkillId,SkillDuanId,Dir,ReleaseX,ReleaseY,ReleaseZ,Agents}, Acc2};

%% id = 79  
unpkg_msg(?MSG_SCENE_RELEASE_EMITS, Acc0) ->
<<AgentId:16/signed,
EmitsId:32,
X:16,
Y:16,
Z:16,
Dir,
DelayTime:32,
SkillId:32,
SkillDuanId:32,
Acc1/binary>> = Acc0,
 {{AgentId,EmitsId,X,Y,Z,Dir,DelayTime,SkillId,SkillDuanId}, Acc1};

%% id = 80  
unpkg_msg(?MSG_SCENE_EMITS_DIE, Acc0) ->
<<AgentId:16/signed,
Acc1/binary>> = Acc0,
 {{AgentId}, Acc1};

%% id = 87  
unpkg_msg(?MSG_SCENE_NAVIGATION, Acc0) ->
<<AgentId:16/signed,
PlayerId:64,
Type,
Npc_id1:32,
Npc_id2:32,
L__point:16, Acc1/binary>> = Acc0,
{Point, Acc2} = unpkg_list_struct__(L__point, Acc1, [], fun unpkg_ano_s__1/1)
,
{{AgentId,PlayerId,Type,Npc_id1,Npc_id2,Point}, Acc2};

%% id = 89  
unpkg_msg(?MSG_SCENE_AGENT_STATE_CHANGE, Acc0) ->
<<AgentId:16/signed,
State,
Acc1/binary>> = Acc0,
 {{AgentId,State}, Acc1};
unpkg_msg(Id, _) -> ok.


unpkg_move_vector__(Acc0) ->
<<XOffset/signed,
YOffset/signed,
HOffset/signed,
Acc1/binary>> = Acc0,
 {{XOffset,YOffset,HOffset}, Acc1}.
unpkg_ano_s__0(Acc0) ->
<<AgentBeHitId:16/signed,
X:16,
Y:16,
Z:16,
Xl:16,
Xr:16,
Ht,
Hd,
Acc1/binary>> = Acc0,
 {{AgentBeHitId,X,Y,Z,Xl,Xr,Ht,Hd}, Acc1}.
unpkg_ano_s__1(Acc0) ->
<<X:16,
Y:16,
Z:16,
Acc1/binary>> = Acc0,
 {{X,Y,Z}, Acc1}.


to_s(?MSG_SCENE_PLAYER_ENTER_REQUEST) -> <<"MSG_SCENE_PLAYER_ENTER_REQUEST">>; %% high 2, id 1
to_s(?MSG_SCENE_PLAYER_ENTER) -> <<"MSG_SCENE_PLAYER_ENTER">>; %% high 2, id 2
to_s(?MSG_SCENE_GOTO_LAST_CITY) -> <<"MSG_SCENE_GOTO_LAST_CITY">>; %% high 2, id 54
to_s(?MSG_SCENE_ENTER_VIEW) -> <<"MSG_SCENE_ENTER_VIEW">>; %% high 2, id 3
to_s(?MSG_SCENE_LEAVE_VIEW) -> <<"MSG_SCENE_LEAVE_VIEW">>; %% high 2, id 4
to_s(?MSG_SCENE_PLAYER_MOVE) -> <<"MSG_SCENE_PLAYER_MOVE">>; %% high 2, id 22
to_s(?MSG_SCENE_PLAYER_SWITCH_MOVE_MODE) -> <<"MSG_SCENE_PLAYER_SWITCH_MOVE_MODE">>; %% high 2, id 24
to_s(?MSG_SCENE_MOVE) -> <<"MSG_SCENE_MOVE">>; %% high 2, id 5
to_s(?MSG_SCENE_PLAYER_MOVE_STOP) -> <<"MSG_SCENE_PLAYER_MOVE_STOP">>; %% high 2, id 23
to_s(?MSG_SCENE_MOVE_STOP) -> <<"MSG_SCENE_MOVE_STOP">>; %% high 2, id 6
to_s(?MSG_SCENE_JUMP) -> <<"MSG_SCENE_JUMP">>; %% high 2, id 7
to_s(?MSG_SCENE_RELEASE_SKILL) -> <<"MSG_SCENE_RELEASE_SKILL">>; %% high 2, id 8
to_s(?MSG_SCENE_RELEASE_SKILL_JUDGE) -> <<"MSG_SCENE_RELEASE_SKILL_JUDGE">>; %% high 2, id 9
to_s(?MSG_SCENE_RELIVE) -> <<"MSG_SCENE_RELIVE">>; %% high 2, id 10
to_s(?MSG_SCENE_CLIENT_RELIVE) -> <<"MSG_SCENE_CLIENT_RELIVE">>; %% high 2, id 36
to_s(?MSG_SCENE_CLIENT_ADD_HP_MP) -> <<"MSG_SCENE_CLIENT_ADD_HP_MP">>; %% high 2, id 37
to_s(?MSG_SCENE_DROP_ITEMS) -> <<"MSG_SCENE_DROP_ITEMS">>; %% high 2, id 11
to_s(?MSG_SCENE_DROP_ITEMS_REMOVE) -> <<"MSG_SCENE_DROP_ITEMS_REMOVE">>; %% high 2, id 12
to_s(?MSG_SCENE_AGENT_DATA_CHANGE) -> <<"MSG_SCENE_AGENT_DATA_CHANGE">>; %% high 2, id 13
to_s(?MSG_SCENE_ADD_BUFF) -> <<"MSG_SCENE_ADD_BUFF">>; %% high 2, id 14
to_s(?MSG_SCENE_DEL_BUFF) -> <<"MSG_SCENE_DEL_BUFF">>; %% high 2, id 15
to_s(?MSG_SCENE_DOOR_TRANSPORT) -> <<"MSG_SCENE_DOOR_TRANSPORT">>; %% high 2, id 16
to_s(?MSG_SCENE_PICKUP_DROP_ITEMS) -> <<"MSG_SCENE_PICKUP_DROP_ITEMS">>; %% high 2, id 19
to_s(?MSG_SCENE_LARGE_MOVE) -> <<"MSG_SCENE_LARGE_MOVE">>; %% high 2, id 27
to_s(?MSG_SCENE_ADD_HP_MP) -> <<"MSG_SCENE_ADD_HP_MP">>; %% high 2, id 30
to_s(?MSG_SCENE_RESIZE_VIEW) -> <<"MSG_SCENE_RESIZE_VIEW">>; %% high 2, id 31
to_s(?MSG_SCENE_DEVICE_RELEASE_SKILL) -> <<"MSG_SCENE_DEVICE_RELEASE_SKILL">>; %% high 2, id 32
to_s(?MSG_SCENE_DEVICE_RELEASE_SKILL_JUDGE) -> <<"MSG_SCENE_DEVICE_RELEASE_SKILL_JUDGE">>; %% high 2, id 33
to_s(?MSG_SCENE_DEVICE_DESTROY) -> <<"MSG_SCENE_DEVICE_DESTROY">>; %% high 2, id 34
to_s(?MSG_SCENE_MONSTER_ENTER_SHOW) -> <<"MSG_SCENE_MONSTER_ENTER_SHOW">>; %% high 2, id 35
to_s(?MSG_SCENE_CLIENT_PLAYER_DIE) -> <<"MSG_SCENE_CLIENT_PLAYER_DIE">>; %% high 2, id 39
to_s(?MSG_SCENE_CLIENT_RELEASE_ANGER_SKILL) -> <<"MSG_SCENE_CLIENT_RELEASE_ANGER_SKILL">>; %% high 2, id 40
to_s(?MSG_SCENE_CLIENT_KILL_MONSTER) -> <<"MSG_SCENE_CLIENT_KILL_MONSTER">>; %% high 2, id 41
to_s(?MSG_SCENE_CLIENT_DROP_BY_MONSTER) -> <<"MSG_SCENE_CLIENT_DROP_BY_MONSTER">>; %% high 2, id 42
to_s(?MSG_SCENE_CLIENT_PICKUP_DROP) -> <<"MSG_SCENE_CLIENT_PICKUP_DROP">>; %% high 2, id 43
to_s(?MSG_SCENE_INSTANCE_CLIENT_KILL_MON) -> <<"MSG_SCENE_INSTANCE_CLIENT_KILL_MON">>; %% high 2, id 51
to_s(?MSG_SCENE_PLAY_EFFECTS) -> <<"MSG_SCENE_PLAY_EFFECTS">>; %% high 2, id 60
to_s(?MSG_CREATE_DIG_RES_SC) -> <<"MSG_CREATE_DIG_RES_SC">>; %% high 2, id 61
to_s(?MSG_DELETE_DIG_RES_SC) -> <<"MSG_DELETE_DIG_RES_SC">>; %% high 2, id 62
to_s(?MSG_SCENE_AGENT_UPDATE_EQU) -> <<"MSG_SCENE_AGENT_UPDATE_EQU">>; %% high 2, id 63
to_s(?MSG_SCENE_AGENT_UPDATE_TITLE) -> <<"MSG_SCENE_AGENT_UPDATE_TITLE">>; %% high 2, id 64
to_s(?MSG_SCENE_AGENT_UPDATE_GUILD) -> <<"MSG_SCENE_AGENT_UPDATE_GUILD">>; %% high 2, id 65
to_s(?MSG_SCENE_EFFECT_UPDATE) -> <<"MSG_SCENE_EFFECT_UPDATE">>; %% high 2, id 66
to_s(?MSG_SCENE_INS_RESET_HP_CD) -> <<"MSG_SCENE_INS_RESET_HP_CD">>; %% high 2, id 67
to_s(?MSG_SCENE_INS_RESET_USE_COUNT) -> <<"MSG_SCENE_INS_RESET_USE_COUNT">>; %% high 2, id 68
to_s(?MSG_SCENE_SHAPESHIFT_UPDATE) -> <<"MSG_SCENE_SHAPESHIFT_UPDATE">>; %% high 2, id 69
to_s(?MSG_SCENE_AREA_STATE) -> <<"MSG_SCENE_AREA_STATE">>; %% high 2, id 70
to_s(?MSG_SCENE_RELEASE_SKILL_END) -> <<"MSG_SCENE_RELEASE_SKILL_END">>; %% high 2, id 71
to_s(?MSG_SCENE_BREAK_SKILL) -> <<"MSG_SCENE_BREAK_SKILL">>; %% high 2, id 72
to_s(?MSG_SCENE_SEND_LOCK_AREA) -> <<"MSG_SCENE_SEND_LOCK_AREA">>; %% high 2, id 73
to_s(?MSG_SCENE_SEND_TALKS_ID) -> <<"MSG_SCENE_SEND_TALKS_ID">>; %% high 2, id 74
to_s(?MSG_SCENE_RIDE_UPDATE) -> <<"MSG_SCENE_RIDE_UPDATE">>; %% high 2, id 75
to_s(?MSG_SCENE_AGENT_DIE) -> <<"MSG_SCENE_AGENT_DIE">>; %% high 2, id 76
to_s(?MSG_SCENE_MONSTER_AGENT_SYNC) -> <<"MSG_SCENE_MONSTER_AGENT_SYNC">>; %% high 2, id 77
to_s(?MSG_SCENE_AGENT_BE_HIT) -> <<"MSG_SCENE_AGENT_BE_HIT">>; %% high 2, id 78
to_s(?MSG_SCENE_RELEASE_EMITS) -> <<"MSG_SCENE_RELEASE_EMITS">>; %% high 2, id 79
to_s(?MSG_SCENE_EMITS_DIE) -> <<"MSG_SCENE_EMITS_DIE">>; %% high 2, id 80
to_s(?MSG_SCENE_RESET_VIEW) -> <<"MSG_SCENE_RESET_VIEW">>; %% high 2, id 81
to_s(?MSG_SCENE_BUFF_DAMAGE) -> <<"MSG_SCENE_BUFF_DAMAGE">>; %% high 2, id 82
to_s(?MSG_SCENE_MONSTER_GONGCHENG_LIST) -> <<"MSG_SCENE_MONSTER_GONGCHENG_LIST">>; %% high 2, id 83
to_s(?MSG_SCENE_MONSTER_GONGCHENG_DELETE) -> <<"MSG_SCENE_MONSTER_GONGCHENG_DELETE">>; %% high 2, id 84
to_s(?MSG_SCENE_MONSTER_GONGCHENG_DELETE_CHANGE_STATUS) -> <<"MSG_SCENE_MONSTER_GONGCHENG_DELETE_CHANGE_STATUS">>; %% high 2, id 85
to_s(?MSG_SCENE_BROADCAST_ACTIVITY) -> <<"MSG_SCENE_BROADCAST_ACTIVITY">>; %% high 2, id 86
to_s(?MSG_SCENE_NAVIGATION) -> <<"MSG_SCENE_NAVIGATION">>; %% high 2, id 87
to_s(?MSG_SCENE_DOUBLE_PRIZE_ACTIVITY) -> <<"MSG_SCENE_DOUBLE_PRIZE_ACTIVITY">>; %% high 2, id 88
to_s(?MSG_SCENE_AGENT_STATE_CHANGE) -> <<"MSG_SCENE_AGENT_STATE_CHANGE">>; %% high 2, id 89
to_s(_) -> <<"unknown msg">>.
unpkg_list_struct__(0, Bin, List, _Fn) -> {lists:reverse(List), Bin};
unpkg_list_struct__(L, Bin, List, Fn) -> {E, Bin1} = Fn(Bin), unpkg_list_struct__(L-1, Bin1, [E|List], Fn).
