%% Auto generated by sproto from seller.sproto
%% Don't edit it.

-module(seller_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("seller_sproto.hrl").

%% id=11  
pkg_msg(?SELLER_DATA, {Next_time_refresh, SellerItem}) ->
<<?SELLER_DATA:16, 
Next_time_refresh:32,
    (length(SellerItem)):16, (iolist_to_binary([<<
Seller_id,
    Count>>
|| {Seller_id, Count} <- SellerItem]))/binary >>
;

%% id=12  
pkg_msg(?MSG_SELLER_SHOPPING, {}) ->
<<?MSG_SELLER_SHOPPING:16>> 
;

%% id=101  
pkg_msg(?MSG_SELLER_SHOPPING_HISTORY, {SellerHistory}) ->
<<?MSG_SELLER_SHOPPING_HISTORY:16, 
(length(SellerHistory)):16, (iolist_to_binary([<<
Time:32,
    Player_id:64,
    (byte_size(Name)), Name/binary,
    Item_bid:32,
    Item_count:16>>
|| {Time, Player_id, Name, Item_bid, Item_count} <- SellerHistory]))/binary >>
;

%% id=1  
pkg_msg(?PUSH_SELLER_SHOPPING_DATA, {Time, Player_id, Name, Item_bid, Item_count}) ->
<<?PUSH_SELLER_SHOPPING_DATA:16, 
Time:32,
    Player_id:64,
    (byte_size(Name)), Name/binary,
    Item_bid:32,
    Item_count:16>>
;
pkg_msg(Id, _) -> ok.



%% id = 11  
unpkg_msg(?SELLER_DATA, Acc0) ->
<<Type,
Acc1/binary>> = Acc0,
 {{Type}, Acc1};

%% id = 12  
unpkg_msg(?MSG_SELLER_SHOPPING, Acc0) ->
<<Item_id:32,
Item_num:16,
Acc1/binary>> = Acc0,
 {{Item_id,Item_num}, Acc1};

%% id = 101  
unpkg_msg(?MSG_SELLER_SHOPPING_HISTORY, Acc0) ->
<<PageStart,
PageEnd,
Acc1/binary>> = Acc0,
 {{PageStart,PageEnd}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?SELLER_DATA) -> <<"SELLER_DATA">>; %% high 25, id 11
to_s(?MSG_SELLER_SHOPPING) -> <<"MSG_SELLER_SHOPPING">>; %% high 25, id 12
to_s(?MSG_SELLER_SHOPPING_HISTORY) -> <<"MSG_SELLER_SHOPPING_HISTORY">>; %% high 25, id 101
to_s(?PUSH_SELLER_SHOPPING_DATA) -> <<"PUSH_SELLER_SHOPPING_DATA">>; %% high 25, id 1
to_s(_) -> <<"unknown msg">>.
