%% Auto generated by sproto from seller.sproto
%% Don't edit it.

-define(SELLER_DATA, 6411). %% hight:25 id11
-define(MSG_SELLER_SHOPPING, 6412). %% hight:25 id12
-define(MSG_SELLER_SHOPPING_HISTORY, 6501). %% hight:25 id101
-define(PUSH_SELLER_SHOPPING_DATA, 6401). %% hight:25 id1
