%% Auto generated by sproto from server_login_prize.sproto
%% Don't edit it.

-module(server_login_prize_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("server_login_prize_sproto.hrl").

%% id=1  
pkg_msg(?MSG_INIT_MESSAGE, {List}) ->
<<?MSG_INIT_MESSAGE:16, 
(length(List)):16, (iolist_to_binary([<<
Day,
    IsGetPrize>>
|| {Day, IsGetPrize} <- List]))/binary >>
;

%% id=2  
pkg_msg(?MSG_GET_PRIZE, {ReplyNum}) ->
<<?MSG_GET_PRIZE:16, 
ReplyNum>>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_INIT_MESSAGE, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_GET_PRIZE, Acc0) ->
<<Day,
Acc1/binary>> = Acc0,
 {{Day}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_INIT_MESSAGE) -> <<"MSG_INIT_MESSAGE">>; %% high 52, id 1
to_s(?MSG_GET_PRIZE) -> <<"MSG_GET_PRIZE">>; %% high 52, id 2
to_s(_) -> <<"unknown msg">>.
