%% Auto generated by sproto from shop.sproto
%% Don't edit it.

-define(MSG_SHOP_BUY, 2561). %% hight:10 id1
-define(MSG_SHOP_SELL, 2562). %% hight:10 id2
-define(MSG_SHOP_BUY_BACK, 2563). %% hight:10 id3
-define(MSG_SHOP_BUY_BACK_LIST, 2564). %% hight:10 id4
