%% Auto generated by sproto from shop.sproto
%% Don't edit it.

-module(shop_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("shop_sproto.hrl").

%% id=1  
pkg_msg(?MSG_SHOP_BUY, {ReplyNum}) ->
<<?MSG_SHOP_BUY:16, 
ReplyNum>>
;

%% id=2  
pkg_msg(?MSG_SHOP_SELL, {ReplyNum}) ->
<<?MSG_SHOP_SELL:16, 
ReplyNum>>
;

%% id=3  
pkg_msg(?MSG_SHOP_BUY_BACK, {ReplyNum}) ->
<<?MSG_SHOP_BUY_BACK:16, 
ReplyNum>>
;

%% id=4  
pkg_msg(?MSG_SHOP_BUY_BACK_LIST, {ItemPriceL}) ->
<<?MSG_SHOP_BUY_BACK_LIST:16, 
(length(ItemPriceL)):16, (iolist_to_binary([<<
(begin {Id, Bid, Pos, Qly, Qua, Bind, IsJd, SuitId, QhLev, Power, ExtraAttr, GemInfo, ItemEx, SkillChanges, JDListMax, JDListMin, Fumo, FumoAttrList}=ItemInfo, <<
Id:32,
    Bid:32,
    Pos,
    Qly,
    Qua:16,
    Bind,
    IsJd,
    SuitId:32,
    QhLev,
    Power:32,
    (length(ExtraAttr)):16, (iolist_to_binary([<<
ExtraModId,
    (length(Attr)):16, (iolist_to_binary([<<
AttrCode,
    AttrVal:32,
    AttrPer>>
|| {AttrCode, AttrVal, AttrPer} <- Attr]))/binary >>
|| {ExtraModId, Attr} <- ExtraAttr]))/binary ,
    (length(GemInfo)):16, (iolist_to_binary([<<GemId:32>> || GemId <- GemInfo]))/binary,
    (length(ItemEx)):16, (iolist_to_binary([<<
Key,
    Val:32>>
|| {Key, Val} <- ItemEx]))/binary ,
    (length(SkillChanges)):16, (iolist_to_binary([<<Id:32>> || Id <- SkillChanges]))/binary,
    (length(JDListMax)):16, (iolist_to_binary([<<Max:32>> || Max <- JDListMax]))/binary,
    (length(JDListMin)):16, (iolist_to_binary([<<Min:32>> || Min <- JDListMin]))/binary,
    Fumo:16,
    (length(FumoAttrList)):16, (iolist_to_binary([<<
TypeId,
    AttrId,
    AttrVal:32>>
|| {TypeId, AttrId, AttrVal} <- FumoAttrList]))/binary >>
 end)/binary,
    ItemPrice:32>>
|| {ItemInfo, ItemPrice} <- ItemPriceL]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_SHOP_BUY, Acc0) ->
<<ShopType,
ButId:32,
ItemCount:16,
Acc1/binary>> = Acc0,
 {{ShopType,ButId,ItemCount}, Acc1};

%% id = 2  
unpkg_msg(?MSG_SHOP_SELL, Acc0) ->
<<ItemId:32,
ItemCount:16,
Acc1/binary>> = Acc0,
 {{ItemId,ItemCount}, Acc1};

%% id = 3  
unpkg_msg(?MSG_SHOP_BUY_BACK, Acc0) ->
<<BackPos,
Acc1/binary>> = Acc0,
 {{BackPos}, Acc1};

%% id = 4  
unpkg_msg(?MSG_SHOP_BUY_BACK_LIST, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_SHOP_BUY) -> <<"MSG_SHOP_BUY">>; %% high 10, id 1
to_s(?MSG_SHOP_SELL) -> <<"MSG_SHOP_SELL">>; %% high 10, id 2
to_s(?MSG_SHOP_BUY_BACK) -> <<"MSG_SHOP_BUY_BACK">>; %% high 10, id 3
to_s(?MSG_SHOP_BUY_BACK_LIST) -> <<"MSG_SHOP_BUY_BACK_LIST">>; %% high 10, id 4
to_s(_) -> <<"unknown msg">>.
