%% Auto generated by sproto from sinks_state.sproto
%% Don't edit it.

-module(sinks_state_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("sinks_state_sproto.hrl").

%% id=1  
pkg_msg(?MSG_INIT_SINK_DATA_SC, {Bits}) ->
<<?MSG_INIT_SINK_DATA_SC:16, 
Bits/binary>>
;

%% id=2  
pkg_msg(?MSG_SYNC_SINK_ITEM_SC, {Sink}) ->
<<?MSG_SYNC_SINK_ITEM_SC:16, 
(length(Sink)):16, (iolist_to_binary([<<
Item:16>>
|| {Item} <- Sink]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_INIT_SINK_DATA_SC, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_INIT_SINK_DATA_SC) -> <<"MSG_INIT_SINK_DATA_SC">>; %% high 30, id 1
to_s(?MSG_SYNC_SINK_ITEM_SC) -> <<"MSG_SYNC_SINK_ITEM_SC">>; %% high 30, id 2
to_s(_) -> <<"unknown msg">>.
