%% Auto generated by sproto from skill.sproto
%% Don't edit it.

-module(skill_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("skill_sproto.hrl").

%% id=1  
pkg_msg(?MSG_SKILL_INIT_CLIENT, {DressedInfo, Skill_group_select}) ->
<<?MSG_SKILL_INIT_CLIENT:16, 
(length(DressedInfo)):16, (iolist_to_binary([<<
Index,
    Id:32>>
|| {Index, Id} <- DressedInfo]))/binary ,
    Skill_group_select>>
;

%% id=2  
pkg_msg(?MSG_SKILL_DRESS_LONG_WEN, {OldLongWenId, NewLongWenId}) ->
<<?MSG_SKILL_DRESS_LONG_WEN:16, 
OldLongWenId:32,
    NewLongWenId:32>>
;

%% id=3  
pkg_msg(?MSG_SKILL_GET_LONG_WEN, {LongWenIds}) ->
<<?MSG_SKILL_GET_LONG_WEN:16, 
(length(LongWenIds)):16, (iolist_to_binary([<<
LongWenId:32,
    Level,
    IsUse>>
|| {LongWenId, Level, IsUse} <- LongWenIds]))/binary >>
;

%% id=4  
pkg_msg(?MSG_SKILL_DRESS_SKILL, {SkillId, Index}) ->
<<?MSG_SKILL_DRESS_SKILL:16, 
SkillId:32,
    Index>>
;

%% id=5  
pkg_msg(?MSG_SKILL_UNDRESS_SKILL, {Group_id, Skill_index}) ->
<<?MSG_SKILL_UNDRESS_SKILL:16, 
Group_id,
    (length(Skill_index)):16, (iolist_to_binary([<<
Index>>
|| {Index} <- Skill_index]))/binary >>
;

%% id=6  
pkg_msg(?MSG_SKILL_UPGRADE_LONG_WEN, {LongWenId, Level}) ->
<<?MSG_SKILL_UPGRADE_LONG_WEN:16, 
LongWenId:32,
    Level>>
;

%% id=7  
pkg_msg(?MSG_SKILL_CHANGE_USE_SKILL_GROUP, {}) ->
<<?MSG_SKILL_CHANGE_USE_SKILL_GROUP:16>> 
;

%% id=8  
pkg_msg(?MSG_SKILL_RESET_LONG_WEN, {SkillId, ResetNum, LongWenIds}) ->
<<?MSG_SKILL_RESET_LONG_WEN:16, 
SkillId:32,
    ResetNum:16,
    (length(LongWenIds)):16, (iolist_to_binary([<<LongWenId:32>> || LongWenId <- LongWenIds]))/binary>>
;

%% id=9  
pkg_msg(?MSG_SKILL_RESET_LONG_WEN_STATUS, {Skill_resets}) ->
<<?MSG_SKILL_RESET_LONG_WEN_STATUS:16, 
(length(Skill_resets)):16, (iolist_to_binary([<<
Id:32,
    Num:16>>
|| {Id, Num} <- Skill_resets]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_SKILL_INIT_CLIENT, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_SKILL_DRESS_LONG_WEN, Acc0) ->
<<LongWenId:32,
Acc1/binary>> = Acc0,
 {{LongWenId}, Acc1};

%% id = 3  
unpkg_msg(?MSG_SKILL_GET_LONG_WEN, Acc0) ->
{{}, Acc0};

%% id = 4  
unpkg_msg(?MSG_SKILL_DRESS_SKILL, Acc0) ->
<<SkillId:32,
Index,
Acc1/binary>> = Acc0,
 {{SkillId,Index}, Acc1};

%% id = 6  
unpkg_msg(?MSG_SKILL_UPGRADE_LONG_WEN, Acc0) ->
<<LongWenId:32,
Level,
Acc1/binary>> = Acc0,
 {{LongWenId,Level}, Acc1};

%% id = 7  
unpkg_msg(?MSG_SKILL_CHANGE_USE_SKILL_GROUP, Acc0) ->
<<Skill_group,
Acc1/binary>> = Acc0,
 {{Skill_group}, Acc1};

%% id = 8  
unpkg_msg(?MSG_SKILL_RESET_LONG_WEN, Acc0) ->
<<SkillId:32,
Acc1/binary>> = Acc0,
 {{SkillId}, Acc1};

%% id = 9  
unpkg_msg(?MSG_SKILL_RESET_LONG_WEN_STATUS, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_SKILL_INIT_CLIENT) -> <<"MSG_SKILL_INIT_CLIENT">>; %% high 7, id 1
to_s(?MSG_SKILL_DRESS_LONG_WEN) -> <<"MSG_SKILL_DRESS_LONG_WEN">>; %% high 7, id 2
to_s(?MSG_SKILL_GET_LONG_WEN) -> <<"MSG_SKILL_GET_LONG_WEN">>; %% high 7, id 3
to_s(?MSG_SKILL_DRESS_SKILL) -> <<"MSG_SKILL_DRESS_SKILL">>; %% high 7, id 4
to_s(?MSG_SKILL_UNDRESS_SKILL) -> <<"MSG_SKILL_UNDRESS_SKILL">>; %% high 7, id 5
to_s(?MSG_SKILL_UPGRADE_LONG_WEN) -> <<"MSG_SKILL_UPGRADE_LONG_WEN">>; %% high 7, id 6
to_s(?MSG_SKILL_CHANGE_USE_SKILL_GROUP) -> <<"MSG_SKILL_CHANGE_USE_SKILL_GROUP">>; %% high 7, id 7
to_s(?MSG_SKILL_RESET_LONG_WEN) -> <<"MSG_SKILL_RESET_LONG_WEN">>; %% high 7, id 8
to_s(?MSG_SKILL_RESET_LONG_WEN_STATUS) -> <<"MSG_SKILL_RESET_LONG_WEN_STATUS">>; %% high 7, id 9
to_s(_) -> <<"unknown msg">>.
