%% Auto generated by sproto from skill.sproto
%% Don't edit it.

-define(MSG_SKILL_INIT_CLIENT, 1793). %% hight:7 id1
-define(MSG_SKILL_DRESS_LONG_WEN, 1794). %% hight:7 id2
-define(MSG_SKILL_GET_LONG_WEN, 1795). %% hight:7 id3
-define(MSG_SKILL_DRESS_SKILL, 1796). %% hight:7 id4
-define(MSG_SKILL_UNDRESS_SKILL, 1797). %% hight:7 id5
-define(MSG_SKILL_UPGRADE_LONG_WEN, 1798). %% hight:7 id6
-define(MSG_SKILL_CHANGE_USE_SKILL_GROUP, 1799). %% hight:7 id7
-define(MSG_SKILL_RESET_LONG_WEN, 1800). %% hight:7 id8
-define(MSG_SKILL_RESET_LONG_WEN_STATUS, 1801). %% hight:7 id9
