%% Auto generated by sproto from sky_ins.sproto
%% Don't edit it.

-define(MSG_SKY_INS_BOX_LEVEL, 8449). %% hight:33 id1
-define(MSG_ENTER_CLIENT_INS, 8450). %% hight:33 id2
-define(MSG_SKY_INS_RANK, 8451). %% hight:33 id3
-define(PUSH_KILL_COUNT, 8459). %% hight:33 id11
-define(PUSH_ACTIVITY_END, 8460). %% hight:33 id12
-define(PUSH_ACTIVITY_END_PRIZE, 8461). %% hight:33 id13
