%% Auto generated by sproto from sky_ins.sproto
%% Don't edit it.

-module(sky_ins_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("sky_ins_sproto.hrl").

%% id=1  
pkg_msg(?MSG_SKY_INS_BOX_LEVEL, {Box_level}) ->
<<?MSG_SKY_INS_BOX_LEVEL:16, 
Box_level>>
;

%% id=2  
pkg_msg(?MSG_ENTER_CLIENT_INS, {Ins_id}) ->
<<?MSG_ENTER_CLIENT_INS:16, 
Ins_id:16>>
;

%% id=3  
pkg_msg(?MSG_SKY_INS_RANK, {Box_rank}) ->
<<?MSG_SKY_INS_RANK:16, 
(length(Box_rank)):16, (iolist_to_binary([<<
Box_rank_id,
    PlayerCarrer,
    PlayerId:64,
    (byte_size(PlayerName)), PlayerName/binary,
    PlayerLev,
    (length(Box_drop)):16, (iolist_to_binary([<<
Item_bid:32,
    Item_num:32>>
|| {Item_bid, Item_num} <- Box_drop]))/binary >>
|| {Box_rank_id, PlayerCarrer, PlayerId, PlayerName, PlayerLev, Box_drop} <- Box_rank]))/binary >>
;

%% id=11  
pkg_msg(?PUSH_KILL_COUNT, {Kill_monster, Kill_player}) ->
<<?PUSH_KILL_COUNT:16, 
Kill_monster:16,
    Kill_player:16>>
;

%% id=12  
pkg_msg(?PUSH_ACTIVITY_END, {Kill_monster, Exp, Drop}) ->
<<?PUSH_ACTIVITY_END:16, 
Kill_monster:16,
    Exp:32,
    (length(Drop)):16, (iolist_to_binary([<<
Item_bid:32,
    Item_num:32>>
|| {Item_bid, Item_num} <- Drop]))/binary >>
;

%% id=13  
pkg_msg(?PUSH_ACTIVITY_END_PRIZE, {Kill_monster, Kill_monster_rank, Kill_player, Kill_player_rank, Exp, Drop}) ->
<<?PUSH_ACTIVITY_END_PRIZE:16, 
Kill_monster:16,
    Kill_monster_rank:16,
    Kill_player:16,
    Kill_player_rank:16,
    Exp:32,
    (length(Drop)):16, (iolist_to_binary([<<
Item_bid:32,
    Item_num:32>>
|| {Item_bid, Item_num} <- Drop]))/binary >>
;
pkg_msg(Id, _) -> ok.



%% id = 1  
unpkg_msg(?MSG_SKY_INS_BOX_LEVEL, Acc0) ->
{{}, Acc0};

%% id = 2  
unpkg_msg(?MSG_ENTER_CLIENT_INS, Acc0) ->
<<Type,
Acc1/binary>> = Acc0,
 {{Type}, Acc1};

%% id = 3  
unpkg_msg(?MSG_SKY_INS_RANK, Acc0) ->
{{}, Acc0};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_SKY_INS_BOX_LEVEL) -> <<"MSG_SKY_INS_BOX_LEVEL">>; %% high 33, id 1
to_s(?MSG_ENTER_CLIENT_INS) -> <<"MSG_ENTER_CLIENT_INS">>; %% high 33, id 2
to_s(?MSG_SKY_INS_RANK) -> <<"MSG_SKY_INS_RANK">>; %% high 33, id 3
to_s(?PUSH_KILL_COUNT) -> <<"PUSH_KILL_COUNT">>; %% high 33, id 11
to_s(?PUSH_ACTIVITY_END) -> <<"PUSH_ACTIVITY_END">>; %% high 33, id 12
to_s(?PUSH_ACTIVITY_END_PRIZE) -> <<"PUSH_ACTIVITY_END_PRIZE">>; %% high 33, id 13
to_s(_) -> <<"unknown msg">>.
