%% Auto generated by sproto from task.sproto
%% Don't edit it.

-module(task_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("task_sproto.hrl").

%% id=1  
pkg_msg(?MSG_TASK_INIT_CLIENT, {Task}) ->
<<?MSG_TASK_INIT_CLIENT:16, 
(length(Task)):16, (iolist_to_binary([<<
(length(CompleteTasks)):16, (iolist_to_binary([<<
TaskType:16,
    TaskProgress:16>>
|| {TaskType, TaskProgress} <- CompleteTasks]))/binary ,
    (length(AcceptTasks)):16, (iolist_to_binary([<<
TaskId:16,
    GoalType,
    GoalId:32,
    Count>>
|| {TaskId, GoalType, GoalId, Count} <- AcceptTasks]))/binary >>
|| {CompleteTasks, AcceptTasks} <- Task]))/binary >>
;

%% id=2  
pkg_msg(?MSG_TASK_ACCEPT, {ReplyNum, TaskId}) ->
<<?MSG_TASK_ACCEPT:16, 
ReplyNum,
    TaskId:16>>
;

%% id=3  
pkg_msg(?MSG_TASK_PROGRESS, {TaskId, GoalType, GoalId, Count}) ->
<<?MSG_TASK_PROGRESS:16, 
TaskId:16,
    GoalType,
    GoalId:32,
    Count>>
;

%% id=4  
pkg_msg(?MSG_TASK_SUBMIT, {ReplyNum, TaskId}) ->
<<?MSG_TASK_SUBMIT:16, 
ReplyNum,
    TaskId:16>>
;

%% id=6  
pkg_msg(?MSG_TASK_FAILED, {TaskId}) ->
<<?MSG_TASK_FAILED:16, 
TaskId:16>>
;

%% id=8  
pkg_msg(?MSG_TASK_FLUSH_DAILY_STAR, {ReplyNum, DailyStar}) ->
<<?MSG_TASK_FLUSH_DAILY_STAR:16, 
ReplyNum,
    DailyStar>>
;

%% id=9  
pkg_msg(?MSG_TASK_DAILY_LIST, {DailyCount, DailyFrushCount, IsSucc, Baoxianginfo, Info}) ->
<<?MSG_TASK_DAILY_LIST:16, 
DailyCount,
    DailyFrushCount,
    IsSucc,
    Baoxianginfo/binary,
    Info/binary>>
;

%% id=10  
pkg_msg(?MSG_TASK_DAILY_PROGRESS, {TaskId, Info}) ->
<<?MSG_TASK_DAILY_PROGRESS:16, 
TaskId:16,
    Info/binary>>
;

%% id=11  
pkg_msg(?MSG_TASK_DAILY_TALK_NPC, {}) ->
<<?MSG_TASK_DAILY_TALK_NPC:16>> 
;

%% id=12  
pkg_msg(?MSG_TASK_DAILY_BAOXIANG_GET_PRIZE, {}) ->
<<?MSG_TASK_DAILY_BAOXIANG_GET_PRIZE:16>> 
;

%% id=13  
pkg_msg(?MSG_TASK_DAILY_CANCEL_TASK, {TaskId}) ->
<<?MSG_TASK_DAILY_CANCEL_TASK:16, 
TaskId:16>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_TASK_ACCEPT, Acc0) ->
<<TaskId:16,
Acc1/binary>> = Acc0,
 {{TaskId}, Acc1};

%% id = 4  
unpkg_msg(?MSG_TASK_SUBMIT, Acc0) ->
<<TaskId:16,
Acc1/binary>> = Acc0,
 {{TaskId}, Acc1};

%% id = 8  
unpkg_msg(?MSG_TASK_FLUSH_DAILY_STAR, Acc0) ->
{{}, Acc0};

%% id = 9  
unpkg_msg(?MSG_TASK_DAILY_LIST, Acc0) ->
<<Type,
Acc1/binary>> = Acc0,
 {{Type}, Acc1};

%% id = 11  
unpkg_msg(?MSG_TASK_DAILY_TALK_NPC, Acc0) ->
<<TaskId:16,
EventType,
NpcId:16,
Acc1/binary>> = Acc0,
 {{TaskId,EventType,NpcId}, Acc1};

%% id = 12  
unpkg_msg(?MSG_TASK_DAILY_BAOXIANG_GET_PRIZE, Acc0) ->
<<Index,
Acc1/binary>> = Acc0,
 {{Index}, Acc1};

%% id = 13  
unpkg_msg(?MSG_TASK_DAILY_CANCEL_TASK, Acc0) ->
<<TaskId:16,
Acc1/binary>> = Acc0,
 {{TaskId}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_TASK_INIT_CLIENT) -> <<"MSG_TASK_INIT_CLIENT">>; %% high 12, id 1
to_s(?MSG_TASK_ACCEPT) -> <<"MSG_TASK_ACCEPT">>; %% high 12, id 2
to_s(?MSG_TASK_PROGRESS) -> <<"MSG_TASK_PROGRESS">>; %% high 12, id 3
to_s(?MSG_TASK_SUBMIT) -> <<"MSG_TASK_SUBMIT">>; %% high 12, id 4
to_s(?MSG_TASK_FAILED) -> <<"MSG_TASK_FAILED">>; %% high 12, id 6
to_s(?MSG_TASK_FLUSH_DAILY_STAR) -> <<"MSG_TASK_FLUSH_DAILY_STAR">>; %% high 12, id 8
to_s(?MSG_TASK_DAILY_LIST) -> <<"MSG_TASK_DAILY_LIST">>; %% high 12, id 9
to_s(?MSG_TASK_DAILY_PROGRESS) -> <<"MSG_TASK_DAILY_PROGRESS">>; %% high 12, id 10
to_s(?MSG_TASK_DAILY_TALK_NPC) -> <<"MSG_TASK_DAILY_TALK_NPC">>; %% high 12, id 11
to_s(?MSG_TASK_DAILY_BAOXIANG_GET_PRIZE) -> <<"MSG_TASK_DAILY_BAOXIANG_GET_PRIZE">>; %% high 12, id 12
to_s(?MSG_TASK_DAILY_CANCEL_TASK) -> <<"MSG_TASK_DAILY_CANCEL_TASK">>; %% high 12, id 13
to_s(_) -> <<"unknown msg">>.
