%% Auto generated by sproto from task.sproto
%% Don't edit it.

-define(MSG_TASK_INIT_CLIENT, 3073). %% hight:12 id1
-define(MSG_TASK_ACCEPT, 3074). %% hight:12 id2
-define(MSG_TASK_PROGRESS, 3075). %% hight:12 id3
-define(MSG_TASK_SUBMIT, 3076). %% hight:12 id4
-define(MSG_TASK_DIRECT_COMPLETE, 3077). %% hight:12 id5
-define(MSG_TASK_FAILED, 3078). %% hight:12 id6
-define(MSG_TASK_GIVE_UP, 3079). %% hight:12 id7
-define(MSG_TASK_FLUSH_DAILY_STAR, 3080). %% hight:12 id8
-define(MSG_TASK_DAILY_LIST, 3081). %% hight:12 id9
-define(MSG_TASK_DAILY_PROGRESS, 3082). %% hight:12 id10
-define(MSG_TASK_DAILY_TALK_NPC, 3083). %% hight:12 id11
-define(MSG_TASK_DAILY_BAOXIANG_GET_PRIZE, 3084). %% hight:12 id12
-define(MSG_TASK_DAILY_CANCEL_TASK, 3085). %% hight:12 id13
