%% Auto generated by sproto from team.sproto
%% Don't edit it.

-define(MSG_TEAM_CREATE, 5377). %% hight:21 id1
-define(MSG_TEAM_QUIT, 5378). %% hight:21 id2
-define(MSG_TEAM_KICKOUT, 5379). %% hight:21 id3
-define(MSG_TEAM_JOIN, 5380). %% hight:21 id4
-define(MSG_TEAM_MEMBER_JOIN, 5381). %% hight:21 id5
-define(MSG_TEAM_DISSOLVE, 5382). %% hight:21 id6
-define(MSG_TEAM_GC_LIST_BY_TYPE, 5383). %% hight:21 id7
-define(MSG_TEAM_GC_SHENQING_LIST, 5384). %% hight:21 id8
-define(MSG_TEAM_GC_DEAL_SHENQING, 5385). %% hight:21 id9
-define(MSG_TEAM_GC_RE, 5386). %% hight:21 id10
-define(MSG_TEAM_GC_JOIN_MY_TAEA, 5387). %% hight:21 id11
-define(MSG_TEAM_GC_NOTICE_JOIN_MY_TEAM_OF_PLAYERS, 5388). %% hight:21 id12
-define(MSG_TEAM_GC_APPLY_JOIN, 5389). %% hight:21 id13
-define(MSG_TEAM_GC_FAST_JOIN, 5390). %% hight:21 id14
-define(MSG_TEAM_AUTO_JOIN_FLG, 5391). %% hight:21 id15
-define(MSG_TEAM_REFUSE_ASK, 5392). %% hight:21 id16
-define(MSG_TEAM_NOTICE_MASTER_REFUSE_ASK, 5393). %% hight:21 id17
-define(MSG_TEAM_INVITE, 5394). %% hight:21 id18
-define(MSG_TEAM_INVITE_RESULT, 5395). %% hight:21 id19
-define(MSG_TEAM_BE_INVITE, 5396). %% hight:21 id20
-define(MSG_TEAM_HANDLE_INVITE, 5397). %% hight:21 id21
-define(MSG_TEAM_CALL_TEAMMATE, 5398). %% hight:21 id22
-define(MSG_TEAM_GET_ALL_INFO, 5399). %% hight:21 id23
