%% Auto generated by sproto from titles.sproto
%% Don't edit it.

-module(titles_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("titles_sproto.hrl").

%% id=1  
pkg_msg(?PUSH_MSG_TITLE_INFO, {Wear_title, Titles}) ->
<<?PUSH_MSG_TITLE_INFO:16, 
Wear_title:16,
    (length(Titles)):16, (iolist_to_binary([<<Title_id:16>> || Title_id <- Titles]))/binary>>
;

%% id=2  
pkg_msg(?PUSH_MSG_ADD_TITLE, {State, Title_id}) ->
<<?PUSH_MSG_ADD_TITLE:16, 
State,
    Title_id:16>>
;

%% id=11  
pkg_msg(?MSG_TITLE_CHANGE_TITLE, {Title_id}) ->
<<?MSG_TITLE_CHANGE_TITLE:16, 
Title_id:16>>
;
pkg_msg(Id, _) -> ok.



%% id = 11  
unpkg_msg(?MSG_TITLE_CHANGE_TITLE, Acc0) ->
<<Title_id:16,
Acc1/binary>> = Acc0,
 {{Title_id}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?PUSH_MSG_TITLE_INFO) -> <<"PUSH_MSG_TITLE_INFO">>; %% high 18, id 1
to_s(?PUSH_MSG_ADD_TITLE) -> <<"PUSH_MSG_ADD_TITLE">>; %% high 18, id 2
to_s(?MSG_TITLE_CHANGE_TITLE) -> <<"MSG_TITLE_CHANGE_TITLE">>; %% high 18, id 11
to_s(_) -> <<"unknown msg">>.
