%% Auto generated by sproto from titles.sproto
%% Don't edit it.

-define(PUSH_MSG_TITLE_INFO, 4609). %% hight:18 id1
-define(PUSH_MSG_ADD_TITLE, 4610). %% hight:18 id2
-define(MSG_TITLE_CHANGE_TITLE, 4619). %% hight:18 id11
