%% Auto generated by sproto from vip_new.sproto
%% Don't edit it.

-module(vip_new_sproto).
-export([pkg_msg/2, unpkg_msg/2, to_s/1]).
-include("vip_new_sproto.hrl").

%% id=1  
pkg_msg(?MSG_VIP_NEW_INFO, {VipLevel, YongJiuCard, TotalCount, CardEndTime, VipBuyStatus, VipGiftOne, VipBuyGiftOne, PrizeStatusList, VipGiftEveryDay, IsGetMonthCard, IsGetYongJiu}) ->
<<?MSG_VIP_NEW_INFO:16, 
VipLevel,
    YongJiuCard,
    TotalCount:32,
    CardEndTime:32,
    (length(VipBuyStatus)):16, (iolist_to_binary([<<
Id:32,
    IsBuy>>
|| {Id, IsBuy} <- VipBuyStatus]))/binary ,
    (length(VipGiftOne)):16, (iolist_to_binary([<<
Viplevel,
    Status>>
|| {Viplevel, Status} <- VipGiftOne]))/binary ,
    (length(VipBuyGiftOne)):16, (iolist_to_binary([<<
Viplevel,
    Status>>
|| {Viplevel, Status} <- VipBuyGiftOne]))/binary ,
    (length(PrizeStatusList)):16, (iolist_to_binary([<<
PayPrizeId:16,
    Status>>
|| {PayPrizeId, Status} <- PrizeStatusList]))/binary ,
    VipGiftEveryDay,
    IsGetMonthCard,
    IsGetYongJiu>>
;

%% id=2  
pkg_msg(?MSG_VIP_NEW_ONE_BUY, {}) ->
<<?MSG_VIP_NEW_ONE_BUY:16>> 
;

%% id=3  
pkg_msg(?MSG_VIP_NEW_GET_PRIZE, {}) ->
<<?MSG_VIP_NEW_GET_PRIZE:16>> 
;

%% id=4  
pkg_msg(?MSG_VIP_NEW_LOCAL_BUY, {VipLevel, IsBuy}) ->
<<?MSG_VIP_NEW_LOCAL_BUY:16, 
VipLevel,
    IsBuy>>
;

%% id=5  
pkg_msg(?MSG_VIP_NEW_GET_PAY_PRIZE, {}) ->
<<?MSG_VIP_NEW_GET_PAY_PRIZE:16>> 
;

%% id=6  
pkg_msg(?MSG_VIP_NEW_SEND_COST, {DayCost, SumCost}) ->
<<?MSG_VIP_NEW_SEND_COST:16, 
DayCost:32,
    SumCost:32>>
;

%% id=7  
pkg_msg(?MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD, {}) ->
<<?MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD:16>> 
;

%% id=8  
pkg_msg(?MSG_VIP_NEW_QQ_PAY_CS, {VipLevel, IsBuy}) ->
<<?MSG_VIP_NEW_QQ_PAY_CS:16, 
VipLevel,
    IsBuy>>
;

%% id=9  
pkg_msg(?MSG_VIP_NEW_PAY_PRIZE_STATUS, {PayPrizeId}) ->
<<?MSG_VIP_NEW_PAY_PRIZE_STATUS:16, 
PayPrizeId:32>>
;

%% id=10  
pkg_msg(?MSG_VIP_NEW_FIRST_PAY_TIME, {ItemId, Time}) ->
<<?MSG_VIP_NEW_FIRST_PAY_TIME:16, 
ItemId:32,
    Time:64>>
;
pkg_msg(Id, _) -> ok.



%% id = 2  
unpkg_msg(?MSG_VIP_NEW_ONE_BUY, Acc0) ->
<<VipLevel,
Acc1/binary>> = Acc0,
 {{VipLevel}, Acc1};

%% id = 3  
unpkg_msg(?MSG_VIP_NEW_GET_PRIZE, Acc0) ->
<<Type,
VipLevel,
Acc1/binary>> = Acc0,
 {{Type,VipLevel}, Acc1};

%% id = 4  
unpkg_msg(?MSG_VIP_NEW_LOCAL_BUY, Acc0) ->
<<Id:32,
Acc1/binary>> = Acc0,
 {{Id}, Acc1};

%% id = 5  
unpkg_msg(?MSG_VIP_NEW_GET_PAY_PRIZE, Acc0) ->
<<PayPrizeId:16,
Acc1/binary>> = Acc0,
 {{PayPrizeId}, Acc1};

%% id = 7  
unpkg_msg(?MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD, Acc0) ->
<<PayId:32,
Acc1/binary>> = Acc0,
 {{PayId}, Acc1};

%% id = 8  
unpkg_msg(?MSG_VIP_NEW_QQ_PAY_CS, Acc0) ->
<<Id:32,
OpenidLen, Openid:OpenidLen/binary,
TokenLen, Token:TokenLen/binary,
PayTokenLen, PayToken:PayTokenLen/binary,
AppkeyLen, Appkey:AppkeyLen/binary,
AppidLen, Appid:AppidLen/binary,
PfLen, Pf:PfLen/binary,
PfKeyLen, PfKey:PfKeyLen/binary,
ZoneidLen, Zoneid:ZoneidLen/binary,
Account,
Record,
Acc1/binary>> = Acc0,
 {{Id,Openid,Token,PayToken,Appkey,Appid,Pf,PfKey,Zoneid,Account,Record}, Acc1};
unpkg_msg(Id, _) -> ok.




to_s(?MSG_VIP_NEW_INFO) -> <<"MSG_VIP_NEW_INFO">>; %% high 50, id 1
to_s(?MSG_VIP_NEW_ONE_BUY) -> <<"MSG_VIP_NEW_ONE_BUY">>; %% high 50, id 2
to_s(?MSG_VIP_NEW_GET_PRIZE) -> <<"MSG_VIP_NEW_GET_PRIZE">>; %% high 50, id 3
to_s(?MSG_VIP_NEW_LOCAL_BUY) -> <<"MSG_VIP_NEW_LOCAL_BUY">>; %% high 50, id 4
to_s(?MSG_VIP_NEW_GET_PAY_PRIZE) -> <<"MSG_VIP_NEW_GET_PAY_PRIZE">>; %% high 50, id 5
to_s(?MSG_VIP_NEW_SEND_COST) -> <<"MSG_VIP_NEW_SEND_COST">>; %% high 50, id 6
to_s(?MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD) -> <<"MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD">>; %% high 50, id 7
to_s(?MSG_VIP_NEW_QQ_PAY_CS) -> <<"MSG_VIP_NEW_QQ_PAY_CS">>; %% high 50, id 8
to_s(?MSG_VIP_NEW_PAY_PRIZE_STATUS) -> <<"MSG_VIP_NEW_PAY_PRIZE_STATUS">>; %% high 50, id 9
to_s(?MSG_VIP_NEW_FIRST_PAY_TIME) -> <<"MSG_VIP_NEW_FIRST_PAY_TIME">>; %% high 50, id 10
to_s(_) -> <<"unknown msg">>.
