%% Auto generated by sproto from vip_new.sproto
%% Don't edit it.

-define(MSG_VIP_NEW_INFO, 12801). %% hight:50 id1
-define(MSG_VIP_NEW_ONE_BUY, 12802). %% hight:50 id2
-define(MSG_VIP_NEW_GET_PRIZE, 12803). %% hight:50 id3
-define(MSG_VIP_NEW_LOCAL_BUY, 12804). %% hight:50 id4
-define(MSG_VIP_NEW_GET_PAY_PRIZE, 12805). %% hight:50 id5
-define(MSG_VIP_NEW_SEND_COST, 12806). %% hight:50 id6
-define(MSG_VIP_NEW_SEND_PRIZE_MONTH_YONGJIU_CARD, 12807). %% hight:50 id7
-define(MSG_VIP_NEW_QQ_PAY_CS, 12808). %% hight:50 id8
-define(MSG_VIP_NEW_PAY_PRIZE_STATUS, 12809). %% hight:50 id9
-define(MSG_VIP_NEW_FIRST_PAY_TIME, 12810). %% hight:50 id10
